-- Isolated fixture: invoice columns, constraints and effective policies observed
-- read-only on 2026-10-03. Auth/profile and Storage are explicit test stubs.
CREATE SCHEMA private;
CREATE SCHEMA auth;
CREATE SCHEMA storage;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE anon NOLOGIN;
CREATE ROLE service_role NOLOGIN BYPASSRLS;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$;
CREATE FUNCTION public.can_access_feature(feature text,action text) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT coalesce((current_setting('test.permissions',true)::jsonb->>action)::boolean,false) $$;
CREATE FUNCTION public.bamco_is_system_manager() RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT coalesce(current_setting('test.manager',true),'false')='true' $$;
CREATE TABLE public.profiles(id uuid PRIMARY KEY);
CREATE TABLE public.invoices(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,invoice_number text NOT NULL UNIQUE,title text NOT NULL,expense_type text,account_party text NOT NULL,company_name text,project_id bigint,vehicle_ref text,part_id bigint,test_ref text,total_amount numeric(18,2) NOT NULL DEFAULT 0 CHECK(total_amount>=0),currency text NOT NULL DEFAULT 'IRR',created_at_date date NOT NULL DEFAULT current_date,due_date date,status text NOT NULL DEFAULT 'initial',created_by uuid NOT NULL REFERENCES public.profiles(id),follow_up_owner_id uuid REFERENCES public.profiles(id),description text,contract_ref text,metadata jsonb NOT NULL DEFAULT '{}',updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.invoice_payments(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,invoice_id bigint NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,sequence_no integer NOT NULL,amount numeric(18,2) NOT NULL CHECK(amount>0),percent_of_total numeric(7,3),planned_date date,paid_date date,status text NOT NULL DEFAULT 'planned',document_no text,tracking_no text,payment_method text,payer_id uuid REFERENCES public.profiles(id),approver_id uuid REFERENCES public.profiles(id),notes text,receipt_path text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(invoice_id,sequence_no)
);
CREATE TABLE public.invoice_files(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,invoice_id bigint NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,file_type text NOT NULL,file_name text NOT NULL,storage_path text NOT NULL,uploaded_by uuid REFERENCES public.profiles(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE FUNCTION public.invoice_paid_amount(p_invoice_id bigint) RETURNS numeric LANGUAGE sql STABLE SET search_path='' AS $$ SELECT coalesce(sum(amount) FILTER(WHERE status='paid'),0) FROM public.invoice_payments WHERE invoice_id=p_invoice_id; $$;
CREATE FUNCTION public.platform_can_access_invoice(p_invoice_id bigint) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT public.can_access_feature('invoices','view') AND EXISTS(SELECT 1 FROM public.invoices i WHERE i.id=p_invoice_id AND (i.created_by=auth.uid() OR i.follow_up_owner_id=auth.uid() OR public.bamco_is_system_manager()));
$$;
CREATE FUNCTION private.sync_invoice_status() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE invoice_id_value bigint; total numeric; paid_value numeric; due date;
BEGIN
 invoice_id_value:=coalesce(new.invoice_id,old.invoice_id); SELECT i.total_amount,i.due_date INTO total,due FROM public.invoices i WHERE i.id=invoice_id_value; paid_value:=public.invoice_paid_amount(invoice_id_value);
 UPDATE public.invoices SET status=CASE WHEN paid_value>=coalesce(total,0) AND total>0 THEN 'settled' WHEN paid_value>0 THEN 'partially_paid' WHEN due IS NOT NULL AND due<current_date THEN 'overdue' ELSE 'awaiting_payment' END,updated_at=now() WHERE id=invoice_id_value AND status NOT IN('cancelled','returned');
 RETURN CASE WHEN tg_op='DELETE' THEN old ELSE new END;
END $$;
CREATE TRIGGER invoice_payments_status AFTER INSERT OR UPDATE OR DELETE ON public.invoice_payments FOR EACH ROW EXECUTE FUNCTION private.sync_invoice_status();
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_files ENABLE ROW LEVEL SECURITY;
CREATE POLICY invoices_feature_read ON public.invoices FOR SELECT TO authenticated USING(public.platform_can_access_invoice(id));
CREATE POLICY invoices_feature_insert ON public.invoices FOR INSERT TO authenticated WITH CHECK(public.can_access_feature('invoices','create') AND created_by=auth.uid() AND coalesce(follow_up_owner_id,created_by)=auth.uid());
CREATE POLICY invoices_feature_update ON public.invoices FOR UPDATE TO authenticated USING(public.can_access_feature('invoices','edit') AND (created_by=auth.uid() OR follow_up_owner_id=auth.uid() OR public.bamco_is_system_manager())) WITH CHECK(public.can_access_feature('invoices','edit'));
CREATE POLICY invoices_feature_delete ON public.invoices FOR DELETE TO authenticated USING(public.can_access_feature('invoices','delete') AND (created_by=auth.uid() OR public.bamco_is_system_manager()));
CREATE POLICY invoice_payments_scoped_read ON public.invoice_payments FOR SELECT TO authenticated USING(public.platform_can_access_invoice(invoice_id));
CREATE POLICY invoice_payments_scoped_insert ON public.invoice_payments FOR INSERT TO authenticated WITH CHECK(public.platform_can_access_invoice(invoice_id));
CREATE POLICY invoice_payments_scoped_update ON public.invoice_payments FOR UPDATE TO authenticated USING(public.platform_can_access_invoice(invoice_id)) WITH CHECK(public.platform_can_access_invoice(invoice_id));
CREATE POLICY invoice_payments_scoped_delete ON public.invoice_payments FOR DELETE TO authenticated USING(public.platform_can_access_invoice(invoice_id));
CREATE POLICY invoice_files_scoped_read ON public.invoice_files FOR SELECT TO authenticated USING(public.platform_can_access_invoice(invoice_id));
CREATE POLICY invoice_files_scoped_insert ON public.invoice_files FOR INSERT TO authenticated WITH CHECK(public.platform_can_access_invoice(invoice_id));
CREATE POLICY invoice_files_scoped_update ON public.invoice_files FOR UPDATE TO authenticated USING(public.platform_can_access_invoice(invoice_id)) WITH CHECK(public.platform_can_access_invoice(invoice_id));
CREATE POLICY invoice_files_scoped_delete ON public.invoice_files FOR DELETE TO authenticated USING(public.platform_can_access_invoice(invoice_id));
CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
CREATE TABLE storage.objects(id uuid DEFAULT gen_random_uuid() PRIMARY KEY,bucket_id text NOT NULL,name text NOT NULL,metadata jsonb,user_metadata jsonb,owner_id text,UNIQUE(bucket_id,name));
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
-- Deliberately overbroad: proves new bucket's restrictive guards resist old
-- unrelated permissive policies. Never deploy this fixture to Supabase.
CREATE POLICY fixture_broad_policy ON storage.objects FOR ALL TO authenticated,anon USING(true) WITH CHECK(true);
GRANT USAGE ON SCHEMA public,private,auth,storage TO authenticated,anon;
GRANT ALL ON public.invoices,public.invoice_payments,public.invoice_files TO authenticated;
GRANT SELECT ON public.profiles TO authenticated;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON storage.objects TO authenticated,anon;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA auth,public,private TO authenticated,anon;
