-- Source-derived project policies/triggers plus explicit synthetic supporting schema.
-- Organization/routing and project-delete approval-proof dependencies remain stubs.
create schema private;create schema auth;create role authenticated;create role anon;create role service_role bypassrls;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create function auth.role() returns text language sql stable as $$select current_user::text$$;
 create table public.profiles(id uuid primary key,active boolean default true,role text default 'owner');
 create table public.organization_units(id bigint primary key);create table public.organization_roles(id bigint primary key);
 create table public.organization_positions(id bigint primary key,role_id bigint,active boolean);
 create table public.organization_position_assignments(user_id uuid,position_id bigint,is_primary boolean,valid_from date,valid_to date);
 create table public.app_features(feature_key text primary key,active boolean default true);
 create table public.feature_access_grants(id bigint generated by default as identity primary key,feature_key text,subject_kind text,user_id uuid,role_id bigint,resource_type text,resource_id text,effect text default 'allow',can_view boolean default false,can_create boolean default false,can_edit boolean default false,can_delete boolean default false,can_export boolean default false,can_manage_access boolean default false,can_bypass_approval boolean default false,revoked_at timestamptz,granted_at timestamptz,granted_by uuid,metadata jsonb);
 create table public.tasks(id bigint primary key,title text,description text,owner_id uuid,status text,priority text,start_date date,due_date date,created_by uuid,archived boolean default false);
 create table public.change_requests(id bigint primary key,proposed_data jsonb,request_status text);
 create table public.audit_trail(actor_id uuid,action text,target_type text,target_id text,new_data jsonb,metadata jsonb);
 create function private.is_system_manager(p_actor uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=p_actor and active and role='manager')$$;
 create function private.organization_strict_descendant_user_ids(uuid) returns table(user_id uuid) language sql stable as $$select null::uuid where false$$;
 create function private.organization_actor_can_direct_manage_user(uuid,uuid) returns boolean language sql stable as $$select false$$;
 create function private.project_delete_approval_active(bigint) returns boolean language sql stable as $$select false$$;
 grant usage on schema public,private,auth to authenticated,anon;
 
;
create table if not exists public.projects(
  id bigint generated by default as identity primary key,
  project_code text not null unique,
  title text not null,
  description text,
  owner_id uuid not null references public.profiles(id),
  manager_id uuid references public.profiles(id),
  unit_id bigint references public.organization_units(id) on delete set null,
  parent_project_id bigint references public.projects(id) on delete set null,
  planned_start date,planned_end date,actual_start date,actual_end date,
  status text not null default 'draft', priority text not null default 'medium',
  progress numeric(5,2) not null default 0 check(progress between 0 and 100),
  progress_override numeric(5,2) check(progress_override between 0 and 100),
  tags text[] not null default '{}', metadata jsonb not null default '{}'::jsonb,
  created_by uuid not null references public.profiles(id), updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  check(planned_end is null or planned_start is null or planned_end>=planned_start)
);
create table if not exists public.project_members(project_id bigint references public.projects(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,member_role text,created_at timestamptz not null default now(),primary key(project_id,user_id));
create table if not exists public.project_items(
  id bigint generated by default as identity primary key,project_id bigint not null references public.projects(id) on delete cascade,parent_item_id bigint references public.project_items(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete set null,item_type text not null check(item_type in ('phase','activity','task','subtask','milestone')),
  title text not null,description text,owner_id uuid references public.profiles(id) on delete set null,status text not null default 'planned',priority text not null default 'medium',
  planned_start date,planned_end date,actual_start date,actual_end date,progress numeric(5,2) not null default 0 check(progress between 0 and 100),weight numeric(10,2) not null default 1 check(weight>=0),created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(planned_end is null or planned_start is null or planned_end>=planned_start)
);
create table if not exists public.project_dependencies(
  id bigint generated by default as identity primary key,predecessor_item_id bigint not null references public.project_items(id) on delete cascade,successor_item_id bigint not null references public.project_items(id) on delete cascade,dependency_type text not null default 'FS' check(dependency_type in ('FS','SS','FF','SF')),lag_days integer not null default 0,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),unique(predecessor_item_id,successor_item_id),check(predecessor_item_id<>successor_item_id)
);

;
alter table public.project_items add column approval_request_id bigint,add column approval_state text default 'approved';
;
create or replace function private.feature_grant_allows(
  p_grant public.feature_access_grants,
  p_action text
)
returns boolean
language sql
immutable
security definer
set search_path=''
as $$
  select case lower(coalesce(p_action,'view'))
    when 'view' then p_grant.can_view
    when 'create' then p_grant.can_create
    when 'edit' then p_grant.can_edit
    when 'delete' then p_grant.can_delete
    when 'export' then p_grant.can_export
    when 'manage' then p_grant.can_manage_access
    when 'manage_access' then p_grant.can_manage_access
    when 'bypass_approval' then p_grant.can_bypass_approval
    else false
  end;
$$;
;
create or replace function public.can_access_feature(text,text default 'view') returns boolean language sql as $$select false$$;
;
-- Source-equivalent protected functions; no live identities or records. Supporting external
-- organization/approval semantics are explicitly stubbed by the isolated runner.
-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create or replace function public.delete_project_activity(p_item_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid:=auth.uid();
  v_item public.project_items%rowtype;
  v_direct boolean;
  v_request_id bigint;
  v_request_status text;
begin
  if v_actor is null then
    raise exception 'نشست فعال لازم است.' using errcode='42501';
  end if;
  select item.* into v_item
  from public.project_items item
  where item.id=p_item_id
    and item.item_type='activity'
    and public.platform_can_access_project(item.project_id)
  for update;
  if not found then
    raise exception 'فعالیت پروژه پیدا نشد.' using errcode='P0002';
  end if;
  if not private.feature_can_access_for(v_actor,'projects','delete') then
    raise exception 'مجوز حذف فعالیت پروژه را ندارید.' using errcode='42501';
  end if;
  if not private.feature_can_access_for(v_actor,'kanban','delete') then
    raise exception 'مجوز حذف وظیفهٔ مرتبط را ندارید.' using errcode='42501';
  end if;
  if v_item.approval_state in ('pending','in_review','needs_revision')
     and exists(
       select 1 from public.change_requests request
       where request.id=v_item.approval_request_id
         and request.request_status in ('pending','in_review','needs_revision')
     ) then
    raise exception 'این فعالیت یک درخواست باز دارد و تا تعیین تکلیف قابل حذف نیست.'
      using errcode='55000';
  end if;

  v_direct:=private.organization_actor_can_direct_manage_user(v_actor,v_item.owner_id);
  if v_direct then
    delete from public.project_items where id=v_item.id;
    return jsonb_build_object(
      'project_item_id',v_item.id,'request_id',null,
      'applied_directly',true,'request_context','project_activity'
    );
  end if;
  if v_item.owner_id is distinct from v_actor then
    raise exception 'حذف این فعالیت در اختیار متولی یا بالادست او نیست.' using errcode='42501';
  end if;
  if v_item.task_id is null then
    raise exception 'درخواست تعریف فعالیت ابتدا باید تعیین تکلیف شود.' using errcode='55000';
  end if;

  v_request_id:=private.submit_project_activity_change_request(
    'delete',v_item.id,'{}'::jsonb,null
  );
  select request_status into v_request_status
  from public.change_requests where id=v_request_id;
  update public.project_items
  set approval_request_id=v_request_id,
      approval_state=coalesce(v_request_status,'pending'),
      updated_at=now()
  where id=v_item.id;

  return jsonb_build_object(
    'project_item_id',v_item.id,'request_id',v_request_id,
    'applied_directly',false,'request_context','project_activity'
  );
end;
$$;

-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create or replace function private.enforce_project_item_identity()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  v_project_owner uuid;
  v_verified_person_delete boolean:=false;
begin
  -- Serialize structural edits per project. This makes the cycle check valid
  -- even when two independently approved move requests race each other.
  perform 1 from public.projects project
  where project.id=new.project_id for update;
  if tg_op='UPDATE' then
    -- delete_person_account is service-role-only and runs as postgres. Its FK
    -- cleanup must be able to clear this nullable historical reference without
    -- opening a caller-controlled path to rewrite the WBS node.
    v_verified_person_delete:=coalesce(
      current_user='postgres'
      and auth.role()='service_role'
      and nullif(current_setting('bamco.deleting_person',true),'')=old.created_by::text
      and old.created_by is not null
      and new.created_by is null
      and (to_jsonb(new)-'created_by')
          is not distinct from (to_jsonb(old)-'created_by'),
      false
    );
  end if;
  if tg_op='UPDATE' and (
    new.project_id is distinct from old.project_id
    or new.item_type is distinct from old.item_type
    or (
      new.created_by is distinct from old.created_by
      and not coalesce(v_verified_person_delete,false)
    )
  ) then
    raise exception 'پروژه، نوع و ثبت‌کنندهٔ گره ساختار شکست قابل تغییر نیست.'
      using errcode='23514';
  end if;
  select project.owner_id into v_project_owner
  from public.projects project where project.id=new.project_id;
  if not found or new.owner_id is distinct from v_project_owner then
    raise exception 'متولی گره ساختار شکست باید با متولی پروژه یکسان باشد.'
      using errcode='23514';
  end if;
  if new.parent_item_id is not null then
    if not exists(
      select 1 from public.project_items parent
      where parent.id=new.parent_item_id
        and parent.project_id=new.project_id
        and parent.item_type in ('phase','activity')
    ) then
      raise exception 'گره بالادست باید متعلق به همین پروژه باشد.' using errcode='23514';
    end if;
    if tg_op='UPDATE' and exists(
      with recursive ancestors(id,parent_item_id) as (
        select parent.id,parent.parent_item_id
        from public.project_items parent where parent.id=new.parent_item_id
        union all
        select parent.id,parent.parent_item_id
        from public.project_items parent
        join ancestors child on child.parent_item_id=parent.id
      )
      select 1 from ancestors where id=old.id
    ) then
      raise exception 'ساختار شکست نمی‌تواند حلقوی باشد.' using errcode='23514';
    end if;
  end if;
  return new;
end;
$$;

-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create or replace function private.enforce_project_owner_consistency()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- Legacy rows may retain a nullable manager reference different from the
  -- non-null owner. During service-role account deletion, normalize that one
  -- FK cleanup to the owner so the project remains valid and manageable.
  if coalesce(
       current_user='postgres'
       and auth.role()='service_role'
       and nullif(current_setting('bamco.deleting_person',true),'')=old.manager_id::text
       and old.manager_id is not null
       and old.manager_id is distinct from old.owner_id
       and new.manager_id is null
       and (to_jsonb(new)-'manager_id')
           is not distinct from (to_jsonb(old)-'manager_id'),
       false
     ) then
    new.manager_id:=new.owner_id;
    return new;
  end if;

  if new.created_by is distinct from old.created_by then
    raise exception 'ایجادکنندهٔ پروژه قابل تغییر نیست.' using errcode='42501';
  end if;

  if new.owner_id is distinct from old.owner_id
     or new.manager_id is distinct from old.manager_id then
    if not private.organization_actor_can_direct_manage_user(auth.uid(),old.owner_id)
       or not private.organization_actor_can_direct_manage_user(auth.uid(),new.owner_id) then
      raise exception 'انتقال متولی پروژه فقط برای مدیر مستقیمِ متولی قبلی و جدید مجاز است.'
        using errcode='42501';
    end if;
    if exists(
      select 1 from public.project_items item where item.project_id=old.id
    ) then
      raise exception 'پس از تعریف فعالیت، تغییر متولی پروژه فقط از مسیر انتقال یکپارچه مجاز است.'
        using errcode='23514';
    end if;
    if exists(
      select 1 from public.change_requests request
      where request.proposed_data->>'request_context'='project_activity'
        and request.proposed_data->>'project_id'=old.id::text
        and request.request_status in ('pending','in_review','needs_revision')
    ) then
      raise exception 'تا تعیین تکلیف درخواست‌های باز، متولی پروژه قابل تغییر نیست.'
        using errcode='55000';
    end if;
    if new.owner_id is distinct from new.manager_id then
      raise exception 'متولی و مسئول پروژه باید یک شخص باشند.' using errcode='23514';
    end if;
  end if;
  return new;
end;
$$;

-- Source: supabase/migrations/20260923100000_feature_access_realtime_and_explicit_deny.sql
create or replace function private.feature_can_access_for(
  p_actor uuid,
  p_feature_key text,
  p_action text default 'view',
  p_resource_type text default null,
  p_resource_id text default null
)
returns boolean
language sql
stable
security definer
set search_path=''
as $$
  with active_feature as (
    select 1 from public.app_features feature
    where feature.feature_key=p_feature_key and feature.active
  ), matching_grants as (
    select grant_row.*
    from public.feature_access_grants grant_row
    where grant_row.feature_key=p_feature_key
      and grant_row.revoked_at is null
      and (
        grant_row.resource_type is null
        or (
          grant_row.resource_type is not distinct from p_resource_type
          and grant_row.resource_id is not distinct from p_resource_id
        )
      )
  ), direct_deny as (
    select 1
    from matching_grants grant_row
    where grant_row.subject_kind='user'
      and grant_row.user_id=p_actor
      and grant_row.effect='deny'
  ), direct_allow as (
    select 1
    from matching_grants grant_row
    where grant_row.subject_kind='user'
      and grant_row.user_id=p_actor
      and grant_row.effect='allow'
      and private.feature_grant_allows(grant_row,p_action)
  ), role_allow as (
    select 1
    from matching_grants grant_row
    join public.organization_position_assignments assignment
      on assignment.user_id=p_actor
     and assignment.is_primary
     and assignment.valid_from<=current_date
     and (assignment.valid_to is null or assignment.valid_to>current_date)
    join public.organization_positions position
      on position.id=assignment.position_id and position.active
    where grant_row.subject_kind='organization_role'
      and grant_row.role_id=position.role_id
      and grant_row.effect='allow'
      and private.feature_grant_allows(grant_row,p_action)
  )
  select coalesce(
    p_actor is not null
    and exists(select 1 from active_feature)
    and exists(select 1 from public.profiles profile where profile.id=p_actor and profile.active)
    and (
      private.is_system_manager(p_actor)
      or (
        not exists(select 1 from direct_deny)
        and (exists(select 1 from direct_allow) or exists(select 1 from role_allow))
      )
    ),false);
$$;

-- Source: supabase/migrations/20260926163822_project_delete_approval_20260926.sql
create or replace function private.guard_project_item_open_request_delete()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if private.project_delete_approval_active(old.project_id) then return old; end if;
  perform 1 from public.projects project where project.id=old.project_id for update;
  if exists(
    with recursive subtree(id,item_type) as (
      select old.id,old.item_type
      union all select child.id,child.item_type from public.project_items child
      join subtree parent on child.parent_item_id=parent.id
    ) select 1 from subtree where id<>old.id and item_type='activity'
  ) then
    raise exception 'ابتدا فعالیت‌های زیرمجموعه را جداگانه حذف کنید.' using errcode='55000';
  end if;
  if exists(
    with recursive subtree(id) as (
      select old.id union all select child.id from public.project_items child
      join subtree parent on child.parent_item_id=parent.id
    ) select 1 from subtree join public.change_requests request
      on request.proposed_data->>'parent_item_id'=subtree.id::text
    where request.proposed_data->>'request_context'='project_activity'
      and request.proposed_data->>'project_id'=old.project_id::text
      and request.request_status in ('pending','in_review','needs_revision')
  ) then
    raise exception 'این گره، بالادست یک درخواست فعالیت باز است.' using errcode='55000';
  end if;
  if exists(
    with recursive subtree(id) as (
      select old.id union all select child.id from public.project_items child
      join subtree parent on child.parent_item_id=parent.id
    ) select 1 from subtree join public.project_items item on item.id=subtree.id
      join public.change_requests request on request.id=item.approval_request_id
    where request.request_status in ('pending','in_review','needs_revision')
  ) then
    raise exception 'ابتدا درخواست باز فعالیت‌های زیرمجموعه را تعیین تکلیف کنید.' using errcode='55000';
  end if;
  return old;
end;
$$;

-- Source: supabase/migrations/20260926163822_project_delete_approval_20260926.sql
create or replace function private.guard_project_open_request_delete()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if not private.project_delete_approval_active(old.id) then
    raise exception 'حذف پروژه باید برای تأیید بالادست ارسال شود.' using errcode='42501';
  end if;
  return old;
end;
$$;

-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create or replace function public.platform_can_access_project(p_project_id bigint)
returns boolean
language sql
stable
security definer
set search_path=''
as $$
  select public.can_access_feature('projects','view') and exists(
    select 1
    from public.projects project
    where project.id=p_project_id
      and (
        project.created_by=auth.uid()
        or project.owner_id=auth.uid()
        or exists(
          select 1 from public.project_members member
          where member.project_id=project.id and member.user_id=auth.uid()
        )
        or private.is_system_manager(auth.uid())
        or project.owner_id in (
          select scoped.user_id
          from private.organization_strict_descendant_user_ids(auth.uid()) scoped
        )
      )
  );
$$;

-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create or replace function public.save_project_activity(
  p_item_id bigint,
  p_project_id bigint,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid:=auth.uid();
  v_project public.projects%rowtype;
  v_item public.project_items%rowtype;
  v_owner uuid;
  v_parent_id bigint;
  v_progress numeric;
  v_direct boolean;
  v_request_id bigint;
  v_request_status text;
  v_request_payload jsonb;
  v_title text;
begin
  if v_actor is null
     or not exists(select 1 from public.profiles profile where profile.id=v_actor and profile.active) then
    raise exception 'نشست فعال لازم است.' using errcode='42501';
  end if;
  if jsonb_typeof(p_payload) is distinct from 'object' then
    raise exception 'اطلاعات فعالیت نامعتبر است.' using errcode='22023';
  end if;

  select * into v_project
  from public.projects project
  where project.id=p_project_id
    and public.platform_can_access_project(project.id)
  for update;
  if not found then
    raise exception 'پروژه در محدودهٔ دسترسی شما نیست.' using errcode='42501';
  end if;

  v_owner:=coalesce(nullif(p_payload->>'owner_id','')::uuid,v_project.owner_id);
  if v_owner is distinct from v_project.owner_id then
    raise exception 'متولی فعالیت باید با متولی پروژه یکسان باشد.' using errcode='23514';
  end if;
  v_direct:=private.organization_actor_can_direct_manage_user(v_actor,v_owner);
  if v_owner is distinct from v_actor and not v_direct then
    raise exception 'متولی پروژه در محدودهٔ سازمانی شما نیست.' using errcode='42501';
  end if;

  v_title:=nullif(btrim(p_payload->>'title'),'');
  if v_title is null then
    raise exception 'عنوان فعالیت الزامی است.' using errcode='22023';
  end if;
  v_parent_id:=nullif(p_payload->>'parent_item_id','')::bigint;
  if v_parent_id is not null and not exists(
    select 1 from public.project_items parent
    where parent.id=v_parent_id
      and parent.project_id=v_project.id
      and parent.item_type in ('phase','activity')
  ) then
    raise exception 'فعالیت بالادست باید متعلق به همین پروژه باشد.' using errcode='23514';
  end if;
  v_progress:=coalesce(nullif(p_payload->>'progress','')::numeric,0);
  if v_progress<0 or v_progress>100 then
    raise exception 'درصد پیشرفت باید بین صفر تا صد باشد.' using errcode='22023';
  end if;

  if p_item_id is null then
    if not private.feature_can_access_for(v_actor,'projects','create')
       or not private.feature_can_access_for(v_actor,'kanban','create') then
      raise exception 'مجوز افزودن فعالیت پروژه را ندارید.' using errcode='42501';
    end if;

    if v_direct then
      insert into public.project_items(
        project_id,parent_item_id,item_type,title,description,owner_id,status,priority,
        planned_start,planned_end,progress,weight,created_by,approval_state
      ) values(
        v_project.id,v_parent_id,'activity',v_title,p_payload->>'description',v_owner,
        coalesce(nullif(p_payload->>'status',''),'ثبت شده'),
        coalesce(nullif(p_payload->>'priority',''),'medium'),
        nullif(p_payload->>'planned_start','')::date,
        nullif(p_payload->>'planned_end','')::date,
        v_progress,1,v_actor,'approved'
      ) returning * into v_item;
      return jsonb_build_object(
        'project_item_id',v_item.id,'request_id',null,
        'applied_directly',true,'request_context','project_activity'
      );
    end if;

    -- Normal self-service creation does not create a WBS row or Kanban task.
    -- The request-state trigger creates both only after final approval.
    v_request_payload:=jsonb_build_object(
      'request_context','project_activity',
      'request_label','تعریف فعالیت در پروژه',
      'project_id',v_project.id,
      'project_item_id',null,
      'item_type','activity',
      'parent_item_id',v_parent_id,
      'title',v_title,
      'description',coalesce(p_payload->>'description',''),
      'owner_id',v_owner,
      'status',private.project_item_task_status(
        coalesce(nullif(p_payload->>'status',''),'ثبت شده')
      ),
      'priority',private.project_item_task_priority(
        coalesce(nullif(p_payload->>'priority',''),'medium')
      ),
      'start_date',nullif(p_payload->>'planned_start','')::date,
      'due_date',nullif(p_payload->>'planned_end','')::date,
      'done_date',null,
      'progress',v_progress,
      'source','project'
    );
    v_request_id:=private.submit_project_activity_create_request(v_request_payload);

    return jsonb_build_object(
      'project_item_id',null,'request_id',v_request_id,
      'applied_directly',false,'request_context','project_activity'
    );
  end if;

  if not private.feature_can_access_for(v_actor,'projects','edit') then
    raise exception 'مجوز ویرایش فعالیت پروژه را ندارید.' using errcode='42501';
  end if;
  if not private.feature_can_access_for(v_actor,'kanban','edit') then
    raise exception 'مجوز ویرایش وظیفهٔ مرتبط را ندارید.' using errcode='42501';
  end if;

  select * into v_item
  from public.project_items item
  where item.id=p_item_id
    and item.project_id=v_project.id
    and item.item_type='activity'
  for update;
  if not found then
    raise exception 'فعالیت پروژه پیدا نشد.' using errcode='P0002';
  end if;
  if v_item.owner_id is distinct from v_project.owner_id then
    raise exception 'متولی فعالیت با متولی پروژه همگام نیست؛ انتقال یکپارچه لازم است.'
      using errcode='23514';
  end if;
  if v_parent_id is not null and exists(
    with recursive ancestors(id,parent_item_id) as (
      select parent.id,parent.parent_item_id
      from public.project_items parent where parent.id=v_parent_id
      union all
      select parent.id,parent.parent_item_id
      from public.project_items parent
      join ancestors child on child.parent_item_id=parent.id
    )
    select 1 from ancestors where id=v_item.id
  ) then
    raise exception 'ساختار شکست نمی‌تواند حلقوی باشد.' using errcode='23514';
  end if;
  if v_item.approval_state in ('pending','in_review','needs_revision')
     and exists(
       select 1 from public.change_requests request
       where request.id=v_item.approval_request_id
         and request.request_status in ('pending','in_review','needs_revision')
     ) then
    raise exception 'این فعالیت یک درخواست باز دارد؛ اصلاح یا بررسی را از کارتابل تأییدها انجام دهید.'
      using errcode='55000';
  end if;

  if v_direct then
    update public.project_items
    set parent_item_id=v_parent_id,
        title=v_title,
        description=p_payload->>'description',
        status=coalesce(nullif(p_payload->>'status',''),status),
        priority=coalesce(nullif(p_payload->>'priority',''),priority),
        planned_start=nullif(p_payload->>'planned_start','')::date,
        planned_end=nullif(p_payload->>'planned_end','')::date,
        progress=v_progress,
        approval_state='approved',
        updated_at=now()
    where id=v_item.id
    returning * into v_item;
    return jsonb_build_object(
      'project_item_id',v_item.id,'request_id',null,
      'applied_directly',true,'request_context','project_activity'
    );
  end if;

  if v_item.owner_id is distinct from v_actor then
    raise exception 'ویرایش این فعالیت در اختیار متولی یا بالادست او نیست.' using errcode='42501';
  end if;

  if v_item.task_id is null then
    raise exception 'فعالیت تأییدشده باید یک وظیفهٔ کانبان معتبر داشته باشد.' using errcode='23514';
  end if;

  v_item.parent_item_id:=v_parent_id;
  v_item.title:=v_title;
  v_item.description:=p_payload->>'description';
  v_item.status:=coalesce(nullif(p_payload->>'status',''),v_item.status);
  v_item.priority:=coalesce(nullif(p_payload->>'priority',''),v_item.priority);
  v_item.planned_start:=nullif(p_payload->>'planned_start','')::date;
  v_item.planned_end:=nullif(p_payload->>'planned_end','')::date;
  v_item.progress:=v_progress;
  v_request_payload:=private.project_activity_request_payload(
    v_item,'ویرایش فعالیت در پروژه'
  );
  v_request_id:=private.submit_project_activity_change_request(
    'update',v_item.id,v_request_payload,null
  );
  select request_status into v_request_status
  from public.change_requests where id=v_request_id;
  update public.project_items
  set approval_request_id=v_request_id,
      approval_state=coalesce(v_request_status,'pending'),
      updated_at=now()
  where id=v_item.id;

  return jsonb_build_object(
    'project_item_id',v_item.id,'request_id',v_request_id,
    'applied_directly',false,'request_context','project_activity'
  );
end;
$$;


;
create or replace function public.can_access_feature(text,text default 'view') returns boolean language sql stable security definer set search_path='' as $$select private.feature_can_access_for(auth.uid(),$1,$2)$$;
 -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create trigger project_item_identity_guard
before insert or update of project_id,item_type,created_by,owner_id,parent_item_id
on public.project_items
for each row execute function private.enforce_project_item_identity();
 -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create trigger projects_owner_consistency_guard
before update of owner_id, manager_id, created_by on public.projects
for each row execute function private.enforce_project_owner_consistency();
 -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create trigger project_item_open_request_delete_guard
before delete on public.project_items
for each row execute function private.guard_project_item_open_request_delete();
 -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create trigger project_open_request_delete_guard
before delete on public.projects
for each row execute function private.guard_project_open_request_delete();
 alter table public.projects enable row level security;alter table public.project_members enable row level security;alter table public.tasks enable row level security;
 -- Synthetic fixture bootstrapping only.
create policy projects_read on public.projects for select to authenticated using(public.platform_can_access_project(id));
 -- Synthetic fixture bootstrapping only.
create policy members_read on public.project_members for select to authenticated using(public.platform_can_access_project(project_id));
 -- Synthetic fixture bootstrapping only.
create policy members_insert on public.project_members for insert to authenticated with check(public.can_access_feature('projects','edit') and public.platform_can_access_project(project_id));
 -- Synthetic fixture bootstrapping only.
create policy members_update on public.project_members for update to authenticated using(public.can_access_feature('projects','edit') and public.platform_can_access_project(project_id)) with check(public.can_access_feature('projects','edit') and public.platform_can_access_project(project_id));
 create function public.bamco_is_system_manager() returns boolean language sql stable as $$select private.is_system_manager(auth.uid())$$;
 create function public.organization_scope_user_ids(uuid) returns table(user_id uuid) language sql stable as $$select $1$$;
 grant select,insert,update,delete on public.projects,public.project_members,public.tasks to authenticated;
 grant select on public.profiles to authenticated;
 revoke all on function public.save_project_activity(bigint,bigint,jsonb),public.delete_project_activity(bigint) from public,anon;
 grant execute on function public.save_project_activity(bigint,bigint,jsonb),public.delete_project_activity(bigint) to authenticated;
 insert into public.app_features(feature_key) values('projects'),('kanban'),('settings');
;
-- Schema-only exact task SELECT policy observed read-only during preparation.
-- Source: supabase/migrations/20260923095000_restore_task_scope_policy.sql
create policy tasks_scope_read
  on public.tasks for select to authenticated
  using (
    (
      (not archived and (
        (select public.can_access_feature('kanban','view'))
        or (select public.can_access_feature('taskTimeline','view'))
      ))
      or (archived and (select public.can_access_feature('archive','view')))
    )
    and (
      (owner_id is null and (select public.bamco_is_system_manager()))
      or (owner_id is not null and (select public.bamco_is_system_manager()))
      or owner_id in (
        select scoped.user_id
        from public.organization_scope_user_ids((select auth.uid())) scoped
      )
    )
  );

;
insert into profiles values('00000000-0000-0000-0000-000000000001',true,'owner');
;
insert into profiles values('00000000-0000-0000-0000-000000000002',true,'owner');
;
insert into profiles values('00000000-0000-0000-0000-000000000003',true,'owner');
;
insert into profiles values('00000000-0000-0000-0000-000000000004',false,'owner');
;
insert into profiles values('00000000-0000-0000-0000-000000000005',true,'manager');
;
insert into feature_access_grants(feature_key,subject_kind,user_id,can_view) values('projects','user','00000000-0000-0000-0000-000000000001',true);
;
insert into feature_access_grants(feature_key,subject_kind,user_id,can_view) values('projects','user','00000000-0000-0000-0000-000000000002',true);
;
insert into feature_access_grants(feature_key,subject_kind,user_id,can_view) values('projects','user','00000000-0000-0000-0000-000000000004',true);
;
insert into feature_access_grants(feature_key,subject_kind,user_id,can_view) values('kanban','user','00000000-0000-0000-0000-000000000001',true);
;
insert into projects(id,project_code,title,owner_id,manager_id,created_by) values(10,'SYN-A','Foreign project','00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000002'),(20,'SYN-B','Viewer project','00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000001');
;
insert into project_items(id,project_id,item_type,title,owner_id,created_by) values(100,10,'phase','Foreign phase','00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000002'),(200,20,'phase','Other phase','00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000001');
;
insert into tasks values(1,'Foreign task',null,'00000000-0000-0000-0000-000000000002','doing','medium',null,null,'00000000-0000-0000-0000-000000000002',false),(2,'Personal task',null,'00000000-0000-0000-0000-000000000001','doing','medium',null,null,'00000000-0000-0000-0000-000000000001',false);
;
alter table public.tasks add column done_date date, add column archived_at timestamptz, add column reminder_days int, add column manager_notes text, add column source text, add column created_at timestamptz default now();
 alter table public.audit_trail add column old_data jsonb;
 alter table public.project_items add constraint project_items_task_link_activity_only check(task_id is null or item_type='activity'),add constraint project_items_milestone_single_date check(item_type<>'milestone' or ((planned_start is null and planned_end is null) or planned_end=planned_start));
 create table public.task_statuses(key text primary key,label text,kind text,merged_into text,aliases text[] default '{}');
 insert into public.task_statuses values('registered','ثبت شده','active',null,'{}'),('doing','در حال انجام','active',null,'{}'),('done','انجام شده','completed',null,'{}');
 create function public.organization_has_permission(text,uuid default null) returns boolean language sql stable as $$select private.is_system_manager(auth.uid())$$;
 create function public.bamco_strict_descendant_user_ids() returns table(user_id uuid) language sql stable as $$select null::uuid where false$$;
 create function public.bamco_can_direct_manage_organization_user(uuid) returns boolean language sql stable as $$select $1=auth.uid()$$;
 create function public.organization_can_manage_task(bigint) returns boolean language sql stable as $$select false$$;
 create function public.bamco_can_access_request(bigint) returns boolean language sql stable as $$select false$$;
 create table public.review_task_writes(kind text,task_id bigint);
 create function private.review_task_write() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.review_task_writes values(tg_op,coalesce(new.id,old.id));return coalesce(new,old);end$$;
 -- Synthetic fixture bootstrapping only.
create trigger review_task_write after insert or update or delete on public.tasks for each row execute function private.review_task_write();
 
;
create or replace function private.option_normalize(v text) returns text language sql immutable set search_path='' as $$select btrim(regexp_replace(translate(coalesce(v,''),'يك‌','یک '),'\s+',' ','g'))$$;
;
create or replace function private.task_status_option(v text) returns public.task_statuses language sql stable set search_path='' as $$select resolved from public.task_statuses s join public.task_statuses resolved on resolved.key=coalesce(s.merged_into,s.key) where s.key=v or private.option_normalize(s.label)=private.option_normalize(v) or exists(select 1 from unnest(s.aliases) a where private.option_normalize(a)=private.option_normalize(v)) order by (s.label=v) desc limit 1$$;
;
insert into project_items(id,project_id,parent_item_id,item_type,title,owner_id,created_by,task_id,progress) values(150,10,100,'activity','Protected activity','00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000002',1,50);
;
-- Source: supabase/migrations/20260925003446_request_notes_and_project_status_sync.sql
create or replace function private.project_item_task_status(p_status text)
returns text
language sql
stable
set search_path = ''
as $$
  select coalesce(
    (private.task_status_option(p_status)).label,
    (private.task_status_option(case p_status
      when 'draft' then 'registered'
      when 'planned' then 'registered'
      when 'in_progress' then 'doing'
      when 'waiting' then 'waiting'
      when 'completed' then 'done'
      else p_status
    end)).label,
    p_status
  );
$$;
;
-- Source: supabase/migrations/20260924193000_project_activity_task_canonical_sync.sql
create or replace function private.project_item_task_priority(p_priority text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case p_priority when 'urgent' then 'فوری' when 'low' then 'کم' else 'متوسط' end;
$$;
;
-- Source: supabase/migrations/20260925003446_request_notes_and_project_status_sync.sql
create or replace function private.canonicalize_project_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.status := private.project_item_task_status(new.status);
  return new;
end;
$$;
;
-- Source: supabase/migrations/20260924184500_project_leaf_progress_calculation.sql
create or replace function public.project_calculated_progress(p_project_id bigint)
returns numeric
language sql
stable
set search_path = ''
as $$
  with project_rows as (
    select i.id, i.parent_item_id, i.progress
    from public.project_items i
    where i.project_id = p_project_id
      and i.item_type in ('phase', 'activity', 'milestone')
  ), leaf_rows as (
    select p.progress
    from project_rows p
    where not exists (
      select 1 from project_rows child where child.parent_item_id = p.id
    )
  )
  select coalesce(round(avg(progress), 2), 0) from leaf_rows;
$$;
;
-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create or replace function private.rollup_project_phase_progress()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  v_project_id bigint:=case when tg_op='DELETE' then old.project_id else new.project_id end;
begin
  if tg_op='DELETE'
     or (tg_op='UPDATE' and new.parent_item_id is distinct from old.parent_item_id) then
    update public.project_items former_parent
    set progress=0,updated_at=now()
    where former_parent.id=old.parent_item_id
      and former_parent.item_type in ('phase','activity')
      and former_parent.progress is distinct from 0
      and not exists(
        select 1 from public.project_items child
        where child.parent_item_id=former_parent.id
      );
  end if;

  with recursive descendants(ancestor_id,descendant_id,progress,weight) as (
    select parent.id,child.id,child.progress,coalesce(nullif(child.weight,0),1)
    from public.project_items parent
    join public.project_items child on child.parent_item_id=parent.id
    where parent.project_id=v_project_id
    union all
    select path.ancestor_id,child.id,child.progress,
           coalesce(nullif(child.weight,0),1)
    from descendants path
    join public.project_items child on child.parent_item_id=path.descendant_id
  ), leaf_values as (
    select path.ancestor_id,path.progress,path.weight
    from descendants path
    where not exists(
      select 1 from public.project_items child
      where child.parent_item_id=path.descendant_id
    )
  ), totals as (
    select leaf.ancestor_id,
           coalesce(round(sum(leaf.progress*leaf.weight)/nullif(sum(leaf.weight),0),2),0) progress
    from leaf_values leaf group by leaf.ancestor_id
  )
  update public.project_items container
  set progress=totals.progress,updated_at=now()
  from totals
  where container.id=totals.ancestor_id
    and container.project_id=v_project_id
    and container.item_type in ('phase','activity')
    and container.progress is distinct from totals.progress;

  update public.projects project
  set progress=public.project_calculated_progress(project.id),updated_at=now()
  where project.id=v_project_id and project.progress_override is null;
  return case when tg_op='DELETE' then old else new end;
end;
$$;
;
-- Source: supabase/migrations/20260920120000_organizational_platform.sql
create or replace function private.sync_project_progress() returns trigger language plpgsql security definer set search_path='' as $$
declare project_id_value bigint;
begin
  project_id_value:=coalesce(new.project_id,old.project_id);
  update public.projects set progress=public.project_calculated_progress(project_id_value),updated_at=now() where id=project_id_value and progress_override is null;
  return case when tg_op='DELETE' then old else new end;
end $$;
;
-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create or replace function private.sync_project_activity_task()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_task_id bigint;
  v_task_status text;
  v_status_kind text;
  v_completed boolean;
  v_request_id bigint;
  v_request_is_project_delete boolean:=false;
begin
  -- DELETE must run even under a project/phase/activity cascade. The previous
  -- depth-first guard skipped child activities and left orphan Kanban tasks.
  if tg_op='DELETE' then
    if old.item_type='activity' and old.task_id is not null then
      delete from public.tasks where id=old.task_id;
      perform set_config('bamco.project_activity_deleted_task','1',true);
    end if;
    return old;
  end if;

  -- Approval state, WBS parent/progress and audit metadata do not map to task
  -- columns. Avoid a no-op task UPDATE: it would create history/row-version
  -- churn and, once the item is pending, be rejected by the binding guard.
  -- Keep the one repair/materialization case for an approved taskless activity.
  if tg_op='UPDATE'
     and row(
       new.item_type,new.task_id,new.title,new.description,new.owner_id,
       new.status,new.priority,new.planned_start,new.planned_end
     ) is not distinct from row(
       old.item_type,old.task_id,old.title,old.description,old.owner_id,
       old.status,old.priority,old.planned_start,old.planned_end
     )
     and not (
       new.item_type='activity'
       and new.task_id is null
       and new.approval_state='approved'
     ) then
    return new;
  end if;

  -- The service-role account deletion loop clears nullable FK references one
  -- column at a time. A created_by-only WBS cleanup is not a business edit and
  -- must not issue a no-op task UPDATE (which would bump row_version/audit or
  -- be rejected while an approval is open).
  if tg_op='UPDATE'
     and coalesce(
       current_user='postgres'
       and auth.role()='service_role'
       and nullif(current_setting('bamco.deleting_person',true),'')=old.created_by::text
       and old.created_by is not null
       and new.created_by is null
       and (to_jsonb(new)-'created_by')
           is not distinct from (to_jsonb(old)-'created_by'),
       false
     ) then
    return new;
  end if;

  if pg_trigger_depth()>1 then
    return new;
  end if;

  if new.item_type<>'activity' then
    if new.task_id is not null then
      update public.tasks
      set archived=true,archived_at=coalesce(archived_at,now())
      where id=new.task_id;
    end if;
    return new;
  end if;

  -- While an approved project delete is removing the task, the FK sets
  -- task_id to NULL before the request-state trigger removes the item. Do not
  -- recreate the task in that short interval.
  v_request_id:=nullif(current_setting('bamco.request_id',true),'')::bigint;
  if v_request_id is not null then
    select exists(
      select 1 from public.change_requests request
      where request.id=v_request_id
        and request.request_type='delete'
        and request.proposed_data->>'request_context'='project_activity'
    ) into v_request_is_project_delete;
  end if;
  if v_request_is_project_delete then
    return new;
  end if;

  if new.task_id is null and new.approval_state<>'approved' then
    return new;
  end if;

  v_task_status:=private.project_item_task_status(new.status);
  select status_option.kind into v_status_kind
  from private.task_status_option(v_task_status) status_option;
  v_completed:=coalesce(v_status_kind='completed',false);

  if new.task_id is null then
    insert into public.tasks(
      title,description,owner_id,status,priority,start_date,due_date,
      done_date,archived,archived_at,created_by,source
    ) values(
      new.title,new.description,new.owner_id,v_task_status,
      private.project_item_task_priority(new.priority),new.planned_start,new.planned_end,
      case when v_completed then current_date else null end,
      v_completed,case when v_completed then now() else null end,
      new.created_by,'project'
    ) returning id into v_task_id;
    update public.project_items set task_id=v_task_id where id=new.id;
  else
    update public.tasks
    set title=new.title,
        description=new.description,
        owner_id=new.owner_id,
        status=v_task_status,
        priority=private.project_item_task_priority(new.priority),
        start_date=new.planned_start,
        due_date=new.planned_end,
        done_date=case when v_completed then coalesce(done_date,current_date) else null end,
        archived=v_completed,
        archived_at=case when v_completed then coalesce(archived_at,now()) else null end,
        source='project'
    where id=new.task_id;
  end if;
  return new;
end;
$$;
;
-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create or replace function private.resequence_after_project_item_delete()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if coalesce(current_setting('bamco.project_activity_deleted_task',true),'')='1' then
    perform private.resequence_task_display_ids();
    perform set_config('bamco.project_activity_deleted_task','',true);
  end if;
  return null;
end;
$$;
;
-- Source: supabase/migrations/20260920120000_organizational_platform.sql
create or replace function private.enforce_project_progress_override() returns trigger language plpgsql set search_path='' as $$
begin
  if new.progress_override is distinct from old.progress_override and not public.organization_has_permission('project.progress_override',new.owner_id) then
    raise exception 'ثبت Override پیشرفت مجوز لازم دارد';
  end if;
  return new;
end $$;
;
-- Source: supabase/migrations/20260924173000_project_workspace_modal_and_milestone_rules.sql
create or replace function private.prevent_project_item_cycle()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.parent_item_id is null then
    return new;
  end if;

  if new.parent_item_id = new.id then
    raise exception 'یک آیتم نمی‌تواند بالادست خودش باشد';
  end if;

  if not exists (
    select 1 from public.project_items p
    where p.id = new.parent_item_id and p.project_id = new.project_id
  ) then
    raise exception 'آیتم بالادست باید متعلق به همین پروژه باشد';
  end if;

  if exists (
    with recursive ancestors(id, parent_item_id) as (
      select p.id, p.parent_item_id
      from public.project_items p
      where p.id = new.parent_item_id
      union all
      select p.id, p.parent_item_id
      from public.project_items p
      join ancestors a on a.parent_item_id = p.id
    )
    select 1 from ancestors where id = new.id
  ) then
    raise exception 'ساختار شکست نمی‌تواند حلقوی باشد';
  end if;

  return new;
end;
$$;
;
-- Source: supabase/migrations/20260920120000_organizational_platform.sql
create or replace function private.platform_audit_trigger()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into public.audit_trail(actor_id,action,target_type,target_id,old_data,new_data,metadata)
  values(auth.uid(),lower(tg_op),tg_table_name,coalesce(to_jsonb(old)->>'id',to_jsonb(new)->>'id',''),
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end,'{}'::jsonb);
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;
;
select event_object_table,trigger_name from information_schema.triggers where trigger_schema='public';
;
drop trigger if exists project_open_request_delete_guard on public.projects
;
drop trigger if exists projects_owner_consistency_guard on public.projects
;
drop trigger if exists project_item_open_request_delete_guard on public.project_items
;
drop trigger if exists project_item_identity_guard on public.project_items
;
drop trigger if exists project_item_identity_guard on public.project_items
;
-- Source: dynamic audit-trigger loop in supabase/migrations/20260920120000_organizational_platform.sql
CREATE TRIGGER project_dependencies_audit AFTER INSERT OR DELETE OR UPDATE ON public.project_dependencies FOR EACH ROW EXECUTE FUNCTION private.platform_audit_trigger();
;
-- Source: supabase/migrations/20260927113000_single_superior_approval_root.sql
create trigger project_item_activity_task_sync
after insert or delete or update of task_id,title,description,owner_id,status,priority,planned_start,planned_end,progress
on public.project_items
for each row execute function private.sync_project_activity_task();
;
-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create trigger project_item_identity_guard
before insert or update of project_id,item_type,created_by,owner_id,parent_item_id
on public.project_items
for each row execute function private.enforce_project_item_identity();
;
-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create trigger project_item_open_request_delete_guard
before delete on public.project_items
for each row execute function private.guard_project_item_open_request_delete();
;
-- Source: supabase/migrations/20260924173000_project_workspace_modal_and_milestone_rules.sql
create trigger project_item_parent_cycle_guard
before insert or update of parent_item_id, project_id on public.project_items
for each row execute function private.prevent_project_item_cycle();
;
-- Source: dynamic audit-trigger loop in supabase/migrations/20260920120000_organizational_platform.sql
CREATE TRIGGER project_items_audit AFTER INSERT OR DELETE OR UPDATE ON public.project_items FOR EACH ROW EXECUTE FUNCTION private.platform_audit_trigger();
;
-- Source: supabase/migrations/20260925003446_request_notes_and_project_status_sync.sql
create trigger project_items_canonical_status
before insert or update of status on public.project_items
for each row execute function private.canonicalize_project_status();
;
-- Source: supabase/migrations/20260927113000_single_superior_approval_root.sql
create trigger project_items_progress
after insert or delete or update of progress,weight,project_id,item_type
on public.project_items
for each row execute function private.sync_project_progress();
;
-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create trigger project_items_task_resequence_after_delete
after delete on public.project_items
for each statement execute function private.resequence_after_project_item_delete();
;
-- Source: supabase/migrations/20260927113000_single_superior_approval_root.sql
create trigger project_phase_progress_rollup
after insert or delete or update of progress,weight,parent_item_id,project_id,item_type
on public.project_items
for each row execute function private.rollup_project_phase_progress();
;
-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create trigger project_open_request_delete_guard
before delete on public.projects
for each row execute function private.guard_project_open_request_delete();
;
-- Source: supabase/migrations/20260920120000_organizational_platform.sql
create trigger project_progress_override_guard before update on public.projects for each row execute function private.enforce_project_progress_override();
;
-- Source: dynamic audit-trigger loop in supabase/migrations/20260920120000_organizational_platform.sql
CREATE TRIGGER projects_audit AFTER INSERT OR DELETE OR UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION private.platform_audit_trigger();
;
-- Source: supabase/migrations/20260925003446_request_notes_and_project_status_sync.sql
create trigger projects_canonical_status
before insert or update of status on public.projects
for each row execute function private.canonicalize_project_status();
;
-- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create trigger projects_owner_consistency_guard
before update of owner_id, manager_id, created_by on public.projects
for each row execute function private.enforce_project_owner_consistency();
;
select * from pg_policies;
;
drop policy projects_read on public.projects
;
drop policy members_update on public.project_members
;
drop policy members_insert on public.project_members
;
drop policy members_read on public.project_members
;
drop policy tasks_scope_read on public.tasks
;
alter table public.change_requests enable row level security; -- Source: supabase/migrations/20260922102000_enterprise_relationship_authorization_policy_contract.sql
create policy change_requests_participant_read on public.change_requests
  for select to authenticated using(
    public.can_access_feature('approvals','view')
    and public.bamco_can_access_request(id)
  );
alter table public.project_dependencies enable row level security; -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create policy project_dependencies_scoped_delete on public.project_dependencies
  for delete to authenticated
  using (
    public.can_access_feature('projects','edit')
    and exists(
      select 1 from public.project_items item
      where item.id=project_dependencies.predecessor_item_id
        and public.platform_can_access_project(item.project_id)
    )
  );
alter table public.project_dependencies enable row level security; -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create policy project_dependencies_scoped_insert on public.project_dependencies
  for insert to authenticated
  with check (
    public.can_access_feature('projects','edit')
    and exists(
      select 1
      from public.project_items predecessor
      join public.project_items successor
        on successor.id=project_dependencies.successor_item_id
       and successor.project_id=predecessor.project_id
      where predecessor.id=project_dependencies.predecessor_item_id
        and public.platform_can_access_project(predecessor.project_id)
    )
  );
alter table public.project_dependencies enable row level security; -- Source: supabase/migrations/20260921093000_organizational_platform_security_hardening.sql
create policy project_dependencies_scoped_read on public.project_dependencies for select to authenticated using (exists(select 1 from public.project_items i where i.id=predecessor_item_id and public.platform_can_access_project(i.project_id)));
alter table public.project_dependencies enable row level security; -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create policy project_dependencies_scoped_update on public.project_dependencies
  for update to authenticated
  using (
    public.can_access_feature('projects','edit')
    and exists(
      select 1 from public.project_items item
      where item.id=project_dependencies.predecessor_item_id
        and public.platform_can_access_project(item.project_id)
    )
  )
  with check (
    public.can_access_feature('projects','edit')
    and exists(
      select 1
      from public.project_items predecessor
      join public.project_items successor
        on successor.id=project_dependencies.successor_item_id
       and successor.project_id=predecessor.project_id
      where predecessor.id=project_dependencies.predecessor_item_id
        and public.platform_can_access_project(predecessor.project_id)
    )
  );
alter table public.project_items enable row level security; -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create policy project_items_scoped_delete on public.project_items
  for delete to authenticated
  using (
    item_type in ('phase','milestone') and task_id is null
    and public.can_access_feature('projects','delete')
    and public.platform_can_access_project(project_id)
  );
alter table public.project_items enable row level security; -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create policy project_items_scoped_insert on public.project_items
  for insert to authenticated
  with check (
    item_type in ('phase','milestone') and task_id is null
    and public.can_access_feature('projects','create')
    and public.platform_can_access_project(project_id)
    and created_by=(select auth.uid())
  );
alter table public.project_items enable row level security; -- Source: supabase/migrations/20260921093000_organizational_platform_security_hardening.sql
create policy project_items_scoped_read on public.project_items for select to authenticated using (public.platform_can_access_project(project_id));
alter table public.project_items enable row level security; -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create policy project_items_scoped_update on public.project_items
  for update to authenticated
  using (
    item_type in ('phase','milestone') and task_id is null
    and public.can_access_feature('projects','edit')
    and public.platform_can_access_project(project_id)
  )
  with check (
    item_type in ('phase','milestone') and task_id is null
    and public.can_access_feature('projects','edit')
    and public.platform_can_access_project(project_id)
  );
alter table public.project_members enable row level security; -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create policy project_members_scoped_delete on public.project_members
  for delete to authenticated
  using (
    public.can_access_feature('projects','edit')
    and public.platform_can_access_project(project_id)
  );
alter table public.project_members enable row level security; -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create policy project_members_scoped_insert on public.project_members
  for insert to authenticated
  with check (
    public.can_access_feature('projects','edit')
    and public.platform_can_access_project(project_id)
  );
alter table public.project_members enable row level security; -- Source: supabase/migrations/20260921093000_organizational_platform_security_hardening.sql
create policy project_members_scoped_read on public.project_members for select to authenticated using (public.platform_can_access_project(project_id));
alter table public.project_members enable row level security; -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create policy project_members_scoped_update on public.project_members
  for update to authenticated
  using (
    public.can_access_feature('projects','edit')
    and public.platform_can_access_project(project_id)
  )
  with check (
    public.can_access_feature('projects','edit')
    and public.platform_can_access_project(project_id)
  );
alter table public.projects enable row level security; -- Source: supabase/migrations/20260922074613_enterprise_relationship_authorization_consolidation.sql
create policy projects_feature_delete on public.projects for delete to authenticated using(
  public.can_access_feature('projects','delete') and public.platform_can_access_project(id)
);
alter table public.projects enable row level security; -- Source: supabase/migrations/20260923172942_project_invoice_creation_scope_fix.sql
create policy projects_feature_insert on public.projects
  for insert to authenticated
  with check (
    public.can_access_feature('projects','create')
    and created_by = (select auth.uid())
    and owner_id = manager_id
    and (
      owner_id = (select auth.uid())
      or owner_id in (
        select descendant.user_id
        from public.bamco_strict_descendant_user_ids() as descendant(user_id)
      )
    )
  );
alter table public.projects enable row level security; -- Source: supabase/migrations/20260922074613_enterprise_relationship_authorization_consolidation.sql
create policy projects_feature_read on public.projects for select to authenticated using(public.platform_can_access_project(id));
alter table public.projects enable row level security; -- Source: supabase/migrations/20260925014953_project_activity_approval_workflow.sql
create policy projects_feature_update on public.projects
  for update to authenticated
  using (
    public.can_access_feature('projects','edit')
    and public.platform_can_access_project(id)
  )
  with check (
    public.can_access_feature('projects','edit')
    and owner_id=manager_id
    and (
      (select public.bamco_is_system_manager())
      or owner_id=(select auth.uid())
      or owner_id in (
        select descendant.user_id
        from public.bamco_strict_descendant_user_ids() descendant
      )
    )
  );
alter table public.tasks enable row level security; -- Source: supabase/migrations/20260925031009_project_activity_delete_approval_hotfix.sql
create policy tasks_direct_insert
on public.tasks for insert to authenticated
with check (
  public.can_access_feature('kanban','create')
  and created_by=(select auth.uid())
  and (
    (owner_id is null and public.bamco_is_system_manager())
    or (
      owner_id is not null
      and public.bamco_can_direct_manage_organization_user(owner_id)
    )
  )
);
alter table public.tasks enable row level security; -- Source: supabase/migrations/20260926113231_task_edit_and_chat_recipient_scope.sql
create policy tasks_direct_update on public.tasks for update to authenticated
using (
  public.can_access_feature('kanban','edit')
  and public.organization_can_manage_task(id)
)
with check (
  public.can_access_feature('kanban','edit')
  and (
    (owner_id is not null and public.bamco_can_direct_manage_organization_user(owner_id))
    or (owner_id is null and status='ثبت شده')
  )
);
alter table public.tasks enable row level security; -- Source: supabase/migrations/20260923095000_restore_task_scope_policy.sql
create policy tasks_scope_read
  on public.tasks for select to authenticated
  using (
    (
      (not archived and (
        (select public.can_access_feature('kanban','view'))
        or (select public.can_access_feature('taskTimeline','view'))
      ))
      or (archived and (select public.can_access_feature('archive','view')))
    )
    and (
      (owner_id is null and (select public.bamco_is_system_manager()))
      or (owner_id is not null and (select public.bamco_is_system_manager()))
      or owner_id in (
        select scoped.user_id
        from public.organization_scope_user_ids((select auth.uid())) scoped
      )
    )
  );
grant select,insert,update,delete on project_items,project_dependencies to authenticated; grant usage, select on all sequences in schema public to authenticated;
-- Additional synthetic report-only fields/tables. No live business data.
alter table profiles add column display_name text,add column full_name text;
update profiles set display_name=case id::text when '00000000-0000-0000-0000-000000000001' then 'Synthetic reader' else 'Synthetic colleague' end;
alter table tasks add column legacy_id bigint,add column former_owner_name text;
alter table change_requests add column request_type text,add column requested_by uuid,add column final_data jsonb,add column created_at timestamptz default now(),add column task_id bigint,add column applied_task_id bigint;
create table app_settings(key text,value jsonb);
insert into app_features(feature_key) values('taskTimeline'),('performanceReport'),('archive'),('approvals');

-- Active unscoped duplicates are impossible under the real source invariant.
-- Source: supabase/migrations/20260922074613_enterprise_relationship_authorization_consolidation.sql
create unique index if not exists feature_access_grants_active_subject_feature_idx
  on public.feature_access_grants(
    feature_key,
    subject_kind,
    coalesce(user_id,'00000000-0000-0000-0000-000000000000'::uuid),
    coalesce(role_id,0),
    coalesce(resource_type,''),
    coalesce(resource_id,'')
  ) where revoked_at is null;
