(()=>{
const BRIDGE='http://127.0.0.1:8765',nav=document.querySelector('#nav'),ws=document.querySelector('.workspace');if(!nav||!ws)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isMgr=()=>document.querySelector('#userRole')?.textContent==='مدیر سامانه';
const statusNames={state1:'وضعیت مطلوب',state2:'یادآوری',state3:'نیازمند توجه',state4:'پیگیری جدی',state5:'اقدام فوری'};
let people=[],templates=[],logs=[],pickedPerson=null,replies={};
nav.querySelector('[data-view="mailsettings"]')?.remove();
if(!nav.querySelector('[data-view="fileconfig"]'))nav.insertAdjacentHTML('afterbegin','<button data-view="fileconfig" class="manager-only"><b>⚙</b><span>تنظیمات فایل</span></button>');
if(!document.querySelector('#fileconfigView'))ws.insertAdjacentHTML('beforeend',`<section id="fileconfigView" class="view hidden manager-only desktop-form-view"><div class="desktop-section-title">فایل مدیریت وظایف</div><div class="file-settings-form"><button id="chooseWorkbookBtn" class="primary desktop-action">انتخاب فایل</button><input id="workbookPicker" type="file" accept=".xlsx,.xlsm,.xls" hidden><input id="workbookName" class="english desktop-entry wide-file" dir="ltr" readonly><label>رمز فایل</label><input id="workbookPassword" class="english desktop-entry" dir="ltr" type="password" value="2276"><label>نام شیت</label><input id="workbookSheet" class="english desktop-entry" dir="ltr" value="TM"></div><div class="center-actions"><button id="analyzeWorkbookBtn" class="primary desktop-action wide-action">خواندن و بررسی فایل</button></div><div id="fileStatusBox" class="desktop-status-box">نسخه وب به پایگاه داده متصل است.</div></section>`);
function replaceViews(){
 const p=document.querySelector('#peopleView');if(p)p.innerHTML=`<div class="desktop-toolbar"><button id="addPersonX" class="primary desktop-action">افزودن فرد</button><button id="editPersonX" class="primary desktop-action">ویرایش</button><button id="disablePersonX" class="primary desktop-action">حذف</button></div><div class="table-wrap desktop-tree"><table><thead><tr><th>فعال ▾</th><th>رونوشت ▾</th><th>عنوان ایمیل ▾</th><th>ایمیل ▾</th><th>جنسیت ▾</th><th>نام در اکسل ▾</th></tr></thead><tbody id="peopleBodyX"></tbody></table></div>`;
 const s=document.querySelector('#sendView');if(s)s.innerHTML=`<fieldset class="desktop-fieldset"><legend>نحوه ارسال</legend><div class="send-mode-row"><label><input type="radio" name="sendModeX" value="preview" checked> پیش‌نمایش در اوت‌لوک</label><label><input type="radio" name="sendModeX" value="send"> ارسال مستقیم</label><span class="spacer"></span><button id="runSelectedX" class="primary desktop-action">اجرای عملیات برای افراد انتخاب‌شده</button></div></fieldset><div class="desktop-toolbar"><button id="selectAllX" class="primary desktop-action">انتخاب همه</button><button id="clearAllX" class="primary desktop-action">لغو همه</button><button id="overdueOnlyX" class="primary desktop-action">فقط دیرکرد</button><button id="warningOnlyX" class="primary desktop-action">فقط هشدار</button><span id="bridgeSendX" class="bridge-state">بررسی اتصال Outlook…</span></div><div class="table-wrap desktop-tree"><table><thead><tr><th>انتخاب ▾</th><th>استیکر ▾</th><th>دیرکرد ▾</th><th>هشدار ▾</th><th>وضعیت ▾</th><th>ایمیل ▾</th><th>نام ▾</th></tr></thead><tbody id="sendBodyX"></tbody></table></div>`;
 const t=document.querySelector('#templatesView');if(t)t.innerHTML=`<fieldset class="desktop-fieldset template-selector"><legend>ویرایش متن ایمیل</legend><label>الگو</label><select id="templateStateX" class="desktop-entry"><option value="state1">وضعیت مطلوب</option><option value="state2">یادآوری</option><option value="state3">نیازمند توجه</option><option value="state4">پیگیری جدی</option><option value="state5">اقدام فوری</option><option value="followup">یادآوری مجدد</option></select><button id="editTemplateX" class="primary desktop-action">ویرایش متن</button></fieldset><div id="templateSummaryX" class="desktop-status-box"></div>`;
 const st=document.querySelector('#stickersView');if(st)st.innerHTML=`<fieldset class="desktop-fieldset"><legend>پیش‌نمایش و انتخاب نسخه</legend><div class="sticker-controls"><label>وضعیت</label><select id="stickerStateX" class="desktop-entry"><option value="state1">وضعیت مطلوب</option><option value="state2">یادآوری</option><option value="state3">نیازمند توجه</option><option value="state4">پیگیری جدی</option><option value="state5">اقدام فوری</option></select><label>نسخه</label><select class="desktop-entry"><option>نسخه اصلی</option></select><label><input type="radio" name="stickerGenderX" value="female" checked> خانم</label><label><input type="radio" name="stickerGenderX" value="male"> آقا</label></div></fieldset><fieldset class="desktop-fieldset"><legend>مدیریت نسخه‌ها</legend><div class="sticker-pack-actions"><button id="activateStickerX" class="primary desktop-action">فعال‌سازی نسخه</button><button id="addStickerX" class="primary desktop-action">افزودن نسخه جدید</button><button id="restoreStickerX" class="primary desktop-action">بازگردانی نسخه اصلی</button></div></fieldset><div class="sticker-preview-box"><img id="stickerPreviewX"><div id="stickerLabelX"></div></div><input id="stickerUploadX" type="file" accept="image/*" hidden>`;
 const f=document.querySelector('#followupView');if(f)f.innerHTML=`<div class="desktop-toolbar split-toolbar"><div><button id="checkRepliesX" class="primary desktop-action">بررسی ایمیل‌ها و پاسخ‌ها</button><button id="selectUnansweredX" class="primary desktop-action">انتخاب افراد بدون پاسخ</button><button id="clearFollowX" class="primary desktop-action">لغو انتخاب</button></div><div><button id="previewFollowX" class="primary desktop-action">پیش‌نمایش یادآوری</button><button id="sendFollowX" class="primary desktop-action">ارسال یادآوری</button></div></div><fieldset class="desktop-fieldset follow-date-field"><legend>بازه زمانی ارسال ایمیل</legend><label>از تاریخ</label><input id="followFromX" class="desktop-entry" placeholder="۱۴۰۵/۰۱/۰۱"><button class="ghost desktop-action">تقویم شمسی</button><label>تا تاریخ</label><input id="followToX" class="desktop-entry" placeholder="۱۴۰۵/۱۲/۲۹"><button class="ghost desktop-action">تقویم شمسی</button><span class="spacer"></span><button id="clearDatesX" class="ghost desktop-action">پاک‌کردن بازه</button></fieldset><span id="bridgeFollowX" class="bridge-state inline-state">بررسی اتصال Outlook…</span><div class="table-wrap desktop-tree"><table><thead><tr><th>انتخاب ▾</th><th>پاسخ ▾</th><th>زمان ارسال ▾</th><th>موضوع ایمیل ▾</th><th>ایمیل ▾</th><th>نام ▾</th></tr></thead><tbody id="followBodyX"></tbody></table></div>`;
 if(!document.querySelector('#personDialogX'))document.body.insertAdjacentHTML('beforeend',`<dialog id="personDialogX" class="modal desktop-dialog"><form id="personFormX"><div class="modal-head"><h3 id="personTitleX">افزودن فرد</h3><button type="button" id="closePersonX">×</button></div><input name="id" type="hidden"><div class="person-grid"><label>نام دقیق در اکسل</label><input name="full_name" required><label>عنوان و نام در ایمیل</label><input name="salutation"><label>جنسیت</label><select name="gender"><option>خانم</option><option>آقا</option></select><label>ایمیل</label><input name="email" class="english" dir="ltr" type="email" required><label>رونوشت‌ها (با ; جدا شود)</label><input name="cc_emails" class="english" dir="ltr"><label></label><label class="check-label"><input name="active" type="checkbox" checked> دریافت ایمیل فعال باشد</label></div><div class="modal-actions"><button class="primary" type="submit">ذخیره</button><button id="cancelPersonX" type="button" class="ghost">انصراف</button></div></form></dialog><dialog id="templateDialogX" class="modal desktop-dialog template-dialog"><div class="modal-head"><h3>ویرایش متن ایمیل</h3><button id="closeTemplateX" type="button">×</button></div><textarea id="templateBodyX" class="template-editor"></textarea><div class="modal-actions"><button id="saveTemplateX" class="primary">ذخیره</button><button id="cancelTemplateX" type="button" class="ghost">انصراف</button></div></dialog>`)
}
replaceViews();
const count=(p,b)=>state.tasks.filter(x=>!x.archived&&x.owner_id===p.id&&norm(x.due_state)===b).length;
const sticker=p=>{const o=count(p,'دیرکرد'),w=count(p,'دوره هشدار');return o>=5?'state5':o>=3?'state4':o>=1?'state3':w>0?'state2':'state1'};
const cc=p=>Array.isArray(p.cc_emails)?p.cc_emails:String(p.cc_emails||'').split(';').map(x=>x.trim()).filter(Boolean);
async function safeSelect(t,q='select=*'){try{return await select(t,q)}catch{return[]}}
async function bridge(path,body){const r=await fetch(BRIDGE+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Outlook Bridge در دسترس نیست.');return d}
async function health(){for(const id of ['bridgeSendX','bridgeFollowX']){const e=document.querySelector('#'+id);if(!e)continue;try{const r=await fetch(BRIDGE+'/health'),d=await r.json();e.textContent=d.ok&&!d.offline?'Outlook باز و آماده است':'Outlook آماده نیست';e.className='bridge-state '+(d.ok&&!d.offline?'ok':'bad')}catch{e.textContent='Outlook Bridge اجرا نشده است';e.className='bridge-state bad'}}}
async function loadPeople(){people=await safeSelect('profiles','select=*&order=full_name');if(!people.length)people=state.profiles||[];renderPeople();renderSend()}
function renderPeople(){const b=document.querySelector('#peopleBodyX');if(!b)return;b.innerHTML=people.map(p=>`<tr data-id="${p.id}" class="${pickedPerson===p.id?'selected-row':''}"><td>${p.active!==false?'✓':'—'}</td><td class="english">${esc(cc(p).join('; '))}</td><td>${esc(p.salutation||'—')}</td><td class="english">${esc(p.email)}</td><td>${esc(p.gender||'—')}</td><td>${esc(p.full_name||'—')}</td></tr>`).join('')}
function renderSend(){const b=document.querySelector('#sendBodyX');if(!b)return;b.innerHTML=people.filter(p=>p.active!==false).map(p=>{const o=count(p,'دیرکرد'),w=count(p,'دوره هشدار'),k=sticker(p);return`<tr><td><input class="sendPickX" type="checkbox" data-id="${p.id}"></td><td>${statusNames[k]}</td><td>${fa(o)}</td><td>${fa(w)}</td><td>${statusNames[k]}</td><td class="english">${esc(p.email)}</td><td>${esc(p.full_name)}</td></tr>`}).join('')}
async function loadTemplates(){templates=await safeSelect('email_templates','select=*');templateSummary()}
const tpl=k=>templates.find(x=>x.template_key===k)||{template_key:k,body_html:''};
function templateSummary(){const k=document.querySelector('#templateStateX')?.value||'state1',t=tpl(k);const e=document.querySelector('#templateSummaryX');if(e)e.innerHTML=t.body_html||'متنی ثبت نشده است.'}
function taskRows(p,b){return state.tasks.filter(x=>!x.archived&&x.owner_id===p.id&&norm(x.due_state)===b)}
function table(title,rows){if(!rows.length)return'';return`<h4>${title}</h4><table><thead><tr><th>شناسه</th><th>عنوان کار</th><th>وضعیت</th><th>تاریخ پایان</th></tr></thead><tbody>${rows.map(x=>`<tr><td>#${fa(displayId(x))}</td><td>${esc(x.title)}</td><td>${esc(x.status)}</td><td>${jalaliText(x.due_date)}</td></tr>`).join('')}</tbody></table>`}
function emailHtml(p){const w=taskRows(p,'دوره هشدار'),o=taskRows(p,'دیرکرد'),k=sticker(p);let h=tpl(k).body_html||'[عنوان مخاطب]<br><br>با درود و مهر<br>تعداد امور دیرکردی: [تعداد دیرکرد]<br>تعداد امور در دوره هشدار: [تعداد هشدار]<br><br>[جدول امور دیرکردی][جدول امور هشداری]';return h.replaceAll('[عنوان مخاطب]',esc(p.salutation||p.full_name)).replaceAll('[تعداد هشدار]',fa(w.length)).replaceAll('[تعداد دیرکرد]',fa(o.length)).replaceAll('[جدول امور هشداری]',table('امور در دوره هشدار',w)).replaceAll('[جدول امور دیرکردی]',table('امور دارای دیرکرد',o)).replaceAll('[تاریخ گزارش]',jalaliText(new Date())).replaceAll('[استیکر]','<img src="cid:bamco_sticker">')}
const subject=p=>`گزارش روزانه وضعیت امور | ${jalaliText(new Date())}`;
async function stickerData(p){const g=(p.gender||'').includes('خانم')?'female':'male',k=sticker(p);try{const r=await fetch(`${SB_URL}/storage/v1/object/public/stickers/${k}_${g}.png`);if(!r.ok)return null;const bl=await r.blob();return await new Promise(ok=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.readAsDataURL(bl)})}catch{return null}}
function bind(){
 document.querySelector('#chooseWorkbookBtn')?.addEventListener('click',()=>document.querySelector('#workbookPicker').click());document.querySelector('#workbookPicker')?.addEventListener('change',e=>document.querySelector('#workbookName').value=e.target.files?.[0]?.name||'');document.querySelector('#analyzeWorkbookBtn')?.addEventListener('click',()=>document.querySelector('#fileStatusBox').textContent='نسخه وب فعلاً اطلاعات عملیاتی را از پایگاه داده می‌خواند.');
 document.querySelector('#peopleBodyX')?.addEventListener('click',e=>{const tr=e.target.closest('[data-id]');if(tr){pickedPerson=tr.dataset.id;renderPeople()}});
 const openPerson=p=>{const f=document.querySelector('#personFormX');f.reset();f.elements.active.checked=true;if(p){f.elements.id.value=p.id;f.elements.full_name.value=p.full_name||'';f.elements.salutation.value=p.salutation||'';f.elements.gender.value=p.gender||'خانم';f.elements.email.value=p.email||'';f.elements.cc_emails.value=cc(p).join('; ');f.elements.active.checked=p.active!==false;document.querySelector('#personTitleX').textContent='ویرایش فرد'}else document.querySelector('#personTitleX').textContent='افزودن فرد';document.querySelector('#personDialogX').showModal()};
 document.querySelector('#addPersonX')?.addEventListener('click',()=>openPerson(null));document.querySelector('#editPersonX')?.addEventListener('click',()=>{const p=people.find(x=>x.id===pickedPerson);p?openPerson(p):toast('ابتدا یک فرد را انتخاب کنید.',true)});document.querySelector('#disablePersonX')?.addEventListener('click',async()=>{const p=people.find(x=>x.id===pickedPerson);if(!p)return toast('ابتدا یک فرد را انتخاب کنید.',true);await update('profiles',`id=eq.${p.id}`,{active:false});loadPeople()});['closePersonX','cancelPersonX'].forEach(id=>document.querySelector('#'+id)?.addEventListener('click',()=>document.querySelector('#personDialogX').close()));
 document.querySelector('#personFormX')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),id=d.id;delete d.id;d.active=f.elements.active.checked;d.cc_emails=String(d.cc_emails||'').split(';').map(x=>x.trim()).filter(Boolean);if(!id)return toast('حساب جدید ابتدا باید در سامانه ساخته شود.',true);await update('profiles',`id=eq.${id}`,d);document.querySelector('#personDialogX').close();loadPeople();toast('ذخیره شد.')});
 const selectMode=m=>document.querySelectorAll('.sendPickX').forEach(x=>{const p=people.find(y=>y.id===x.dataset.id),o=count(p,'دیرکرد'),w=count(p,'دوره هشدار');x.checked=m==='all'||(m==='overdue'&&o>0)||(m==='warning'&&w>0&&o===0)});document.querySelector('#selectAllX')?.addEventListener('click',()=>selectMode('all'));document.querySelector('#clearAllX')?.addEventListener('click',()=>selectMode('none'));document.querySelector('#overdueOnlyX')?.addEventListener('click',()=>selectMode('overdue'));document.querySelector('#warningOnlyX')?.addEventListener('click',()=>selectMode('warning'));
 document.querySelector('#runSelectedX')?.addEventListener('click',async()=>{const ids=[...document.querySelectorAll('.sendPickX:checked')].map(x=>x.dataset.id);if(!ids.length)return toast('حداقل یک نفر را انتخاب کنید.',true);const send=document.querySelector('input[name="sendModeX"]:checked').value==='send';for(const id of ids){const p=people.find(x=>x.id===id);try{await bridge(send?'/mail/send':'/mail/preview',{to:p.email,cc:cc(p),subject:subject(p),html:emailHtml(p),inline_image:await stickerData(p)});if(send)try{await insert('email_logs',{recipient_id:p.id,recipient_email:p.email,subject:subject(p),mail_type:'daily',status:'sent'})}catch{}}catch(e){return toast(`${p.full_name}: ${e.message}`,true)}}toast(send?'ایمیل‌ها ارسال شد.':'پیش‌نمایش‌ها در Outlook باز شد.')});
 document.querySelector('#templateStateX')?.addEventListener('change',templateSummary);document.querySelector('#editTemplateX')?.addEventListener('click',()=>{document.querySelector('#templateBodyX').value=tpl(document.querySelector('#templateStateX').value).body_html||'';document.querySelector('#templateDialogX').showModal()});['closeTemplateX','cancelTemplateX'].forEach(id=>document.querySelector('#'+id)?.addEventListener('click',()=>document.querySelector('#templateDialogX').close()));document.querySelector('#saveTemplateX')?.addEventListener('click',async()=>{const k=document.querySelector('#templateStateX').value,t=tpl(k),body_html=document.querySelector('#templateBodyX').value;t.id?await update('email_templates',`id=eq.${t.id}`,{body_html}):await insert('email_templates',{template_key:k,body_html});document.querySelector('#templateDialogX').close();loadTemplates();toast('متن ذخیره شد.')});
 const refreshSticker=()=>{const s=document.querySelector('#stickerStateX').value,g=document.querySelector('input[name="stickerGenderX"]:checked').value;document.querySelector('#stickerPreviewX').src=`${SB_URL}/storage/v1/object/public/stickers/${s}_${g}.png?v=${Date.now()}`;document.querySelector('#stickerLabelX').textContent=`${statusNames[s]} ـ ${g==='female'?'خانم':'آقا'}`};document.querySelector('#stickerStateX')?.addEventListener('change',refreshSticker);document.querySelectorAll('input[name="stickerGenderX"]').forEach(x=>x.addEventListener('change',refreshSticker));document.querySelector('#addStickerX')?.addEventListener('click',()=>document.querySelector('#stickerUploadX').click());document.querySelector('#stickerUploadX')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const s=document.querySelector('#stickerStateX').value,g=document.querySelector('input[name="stickerGenderX"]:checked').value,r=await fetch(`${SB_URL}/storage/v1/object/stickers/${s}_${g}.png`,{method:'POST',headers:{apikey:SB_KEY,Authorization:`Bearer ${state.token}`,'x-upsert':'true','Content-Type':f.type||'image/png'},body:f});if(!r.ok)return toast(await r.text(),true);refreshSticker();toast('استیکر ذخیره شد.')});document.querySelector('#activateStickerX')?.addEventListener('click',()=>toast('نسخه نمایش‌داده‌شده فعال است.'));document.querySelector('#restoreStickerX')?.addEventListener('click',()=>toast('نسخه اصلی حفظ شده است.'));refreshSticker();
 document.querySelector('#clearDatesX')?.addEventListener('click',()=>{document.querySelector('#followFromX').value='';document.querySelector('#followToX').value=''});document.querySelector('#checkRepliesX')?.addEventListener('click',async()=>{const emails=[...new Set(logs.map(x=>x.recipient_email).filter(Boolean))];try{const d=await bridge('/replies/scan',{emails,days:90});replies=d.replies||{};renderLogs();toast('پاسخ‌ها بررسی شد.')}catch(e){toast(e.message,true)}});document.querySelector('#selectUnansweredX')?.addEventListener('click',()=>document.querySelectorAll('#followBodyX tr').forEach(tr=>{const c=tr.querySelector('.followPickX');if(c)c.checked=tr.children[1]?.textContent.includes('بدون پاسخ')}));document.querySelector('#clearFollowX')?.addEventListener('click',()=>document.querySelectorAll('.followPickX').forEach(x=>x.checked=false));
 const follow=async send=>{const ids=[...document.querySelectorAll('.followPickX:checked')].map(x=>x.dataset.id);if(!ids.length)return toast('حداقل یک نفر را انتخاب کنید.',true);for(const id of ids){const l=logs.find(x=>String(x.id)===id),p=people.find(x=>x.id===l.recipient_id),h=(tpl('followup').body_html||'[عنوان مخاطب]<br><br>با درود و مهر<br>این پیام یادآوری مجدد است.').replaceAll('[عنوان مخاطب]',esc(p?.salutation||p?.full_name||l.recipient_email));try{await bridge(send?'/followup/send':'/followup/preview',{recipient:l.recipient_email,subject_hint:'گزارش روزانه وضعیت امور',html:h,days:90})}catch(e){return toast(e.message,true)}}toast(send?'یادآوری‌ها ارسال شد.':'پیش‌نمایش یادآوری در Outlook باز شد.')};document.querySelector('#previewFollowX')?.addEventListener('click',()=>follow(false));document.querySelector('#sendFollowX')?.addEventListener('click',()=>follow(true));
}
function renderLogs(){const b=document.querySelector('#followBodyX');if(!b)return;b.innerHTML=logs.map(l=>{const p=people.find(x=>x.id===l.recipient_id),r=replies[String(l.recipient_email).toLowerCase()]||l.replied_at;return`<tr><td><input class="followPickX" type="checkbox" data-id="${l.id}"></td><td>${r?'پاسخ داده':'بدون پاسخ'}</td><td>${jalaliDateTime(l.sent_at)}</td><td>${esc(l.subject)}</td><td class="english">${esc(l.recipient_email)}</td><td>${esc(p?.full_name||'—')}</td></tr>`}).join('')}
async function loadLogs(){logs=await safeSelect('email_logs','select=*&order=sent_at.desc&limit=300');renderLogs()}
bind();
const exact={fileconfig:'تنظیمات فایل',people:'افراد و رونوشت‌ها',send:'انتخاب و ارسال',templates:'متن ایمیل‌ها',stickers:'مدیریت استیکرها',followup:'پیگیری پاسخ‌ها'};document.querySelectorAll('#nav button').forEach(btn=>{if(exact[btn.dataset.view])btn.addEventListener('click',e=>{if(!isMgr())return;e.stopImmediatePropagation();document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.querySelector('#'+btn.dataset.view+'View')?.classList.remove('hidden');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===btn));if(['people','send'].includes(btn.dataset.view))loadPeople();if(btn.dataset.view==='templates')loadTemplates();if(btn.dataset.view==='followup')loadPeople().then(loadLogs);if(['send','followup'].includes(btn.dataset.view))health()},{capture:true})});
const sync=()=>document.querySelectorAll('.manager-only').forEach(x=>x.classList.toggle('hidden',!isMgr()));setTimeout(sync,200);setTimeout(sync,1000);health();
})();
