(()=>{
'use strict';
const A=()=>window.BAMCO_DESKTOP_ASSETS||{};
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const stateLabels={state1:'وضعیت مطلوب',state2:'یادآوری',state3:'نیازمند توجه',state4:'پیگیری جدی',state5:'اقدام فوری',followup:'یادآوری مجدد'};
const DESKTOP_TEMPLATES={
state1:{subject:'گزارش روزانه وضعیت امور | [تاریخ کامل شمسی] | وضعیت مطلوب',body:`[عنوان و نام مخاطب]\n\nبا درود و مهر،\n\nبررسی آخرین اطلاعات ثبت‌شده در فایل «مدیریت وظایف» نشان می‌دهد که در حال حاضر هیچ‌یک از فعالیت‌های حوزه مسئولیت شما در وضعیت «هشدار» یا «دیرکرد» قرار ندارد.\n\nخلاصه وضعیت: ۰ مورد هشداری | ۰ مورد دیرکردی\n\n[استیکر]\n\nاز همراهی و اهتمام شما در پیگیری، انجام به‌موقع و به‌روزرسانی امور سپاسگزاریم.\n\nچنانچه تغییری در آخرین وضعیت فعالیت‌ها ایجاد شده است، لطفاً با پاسخ به همین ایمیل، مراتب را اعلام فرمایید تا اطلاعات فایل «مدیریت وظایف» به‌روزرسانی شود. همچنین در صورت نیاز می‌توانید از طریق شماره داخلی ۷۴۸۸ با مهندس قائمی در ارتباط باشید.\n\nتاریخ گزارش: [تاریخ کامل شمسی]\n\nبا تشکر و احترام\nسامانه خودکار پایش و پیگیری امور\nشرکت خودروسازان بم\nواحد مهندسی محصول`},
state2:{subject:'گزارش روزانه وضعیت امور | [تاریخ کامل شمسی] | یادآوری',body:`[عنوان و نام مخاطب]\n\nبا درود و مهر،\n\nبررسی آخرین اطلاعات ثبت‌شده در فایل «مدیریت وظایف» نشان می‌دهد که [تعداد امور هشداری] مورد از فعالیت‌های حوزه مسئولیت شما وارد دوره «هشدار» شده‌اند و موعد پایان آن‌ها نزدیک است.\n\nخلاصه وضعیت: [تعداد امور هشداری] مورد هشداری | ۰ مورد دیرکردی\n\n[استیکر]\n\n[جدول امور هشداری]\n\nلطفاً ضمن بررسی موارد فوق، برنامه‌ریزی و پیگیری لازم را به‌منظور انجام آن‌ها پیش از فرارسیدن موعد مقرر در دستور کار قرار دهید.\n\nچنانچه هر یک از فعالیت‌ها انجام شده، پیشرفت داشته یا وضعیت آن تغییر کرده است، لطفاً با پاسخ به همین ایمیل، مراتب را اعلام فرمایید تا اطلاعات فایل «مدیریت وظایف» به‌روزرسانی شود. همچنین در صورت نیاز می‌توانید از طریق شماره داخلی ۷۴۸۸ با مهندس قائمی در ارتباط باشید.\n\nتاریخ گزارش: [تاریخ کامل شمسی]\n\nبا تشکر و احترام\nسامانه خودکار پایش و پیگیری امور\nشرکت خودروسازان بم\nواحد مهندسی محصول`},
state3:{subject:'گزارش روزانه وضعیت امور | [تاریخ کامل شمسی] | نیازمند توجه',body:`[عنوان و نام مخاطب]\n\nبا درود و مهر،\n\nبررسی آخرین اطلاعات ثبت‌شده در فایل «مدیریت وظایف» نشان می‌دهد که [تعداد امور دیرکردی] مورد از فعالیت‌های حوزه مسئولیت شما از موعد تعیین‌شده عبور کرده و در وضعیت «دیرکرد» قرار گرفته‌اند.\n\nخلاصه وضعیت: [تعداد امور هشداری] مورد هشداری | [تعداد امور دیرکردی] مورد دیرکردی\n\n[استیکر]\n\n[جدول امور دیرکردی]\n\n[جدول امور هشداری]\n\nلطفاً موارد فوق را بررسی کرده و اقدامات لازم برای تکمیل آن‌ها و به‌روزرسانی آخرین وضعیت هر فعالیت را در اسرع وقت انجام دهید.\n\nچنانچه هر یک از فعالیت‌ها انجام شده، پیشرفت داشته یا وضعیت آن تغییر کرده است، لطفاً با پاسخ به همین ایمیل، مراتب را اعلام فرمایید تا اطلاعات فایل «مدیریت وظایف» به‌روزرسانی شود. همچنین در صورت نیاز می‌توانید از طریق شماره داخلی ۷۴۸۸ با مهندس قائمی در ارتباط باشید.\n\nتاریخ گزارش: [تاریخ کامل شمسی]\n\nبا تشکر و احترام\nسامانه خودکار پایش و پیگیری امور\nشرکت خودروسازان بم\nواحد مهندسی محصول`},
state4:{subject:'گزارش روزانه وضعیت امور | [تاریخ کامل شمسی] | پیگیری جدی',body:`[عنوان و نام مخاطب]\n\nبا درود و مهر،\n\nبررسی آخرین اطلاعات ثبت‌شده در فایل «مدیریت وظایف» نشان می‌دهد که [تعداد امور دیرکردی] مورد از فعالیت‌های حوزه مسئولیت شما در وضعیت «دیرکرد» قرار دارند و نیازمند پیگیری جدی‌تر هستند.\n\nخلاصه وضعیت: [تعداد امور هشداری] مورد هشداری | [تعداد امور دیرکردی] مورد دیرکردی\n\n[استیکر]\n\n[جدول امور دیرکردی]\n\n[جدول امور هشداری]\n\nخواهشمند است موارد فوق با جدیت بررسی شده و اقدامات لازم برای تعیین تکلیف، تکمیل و به‌روزرسانی وضعیت آن‌ها در اولویت قرار گیرد.\n\nچنانچه هر یک از فعالیت‌ها انجام شده، پیشرفت داشته یا وضعیت آن تغییر کرده است، لطفاً با پاسخ به همین ایمیل، مراتب را اعلام فرمایید تا اطلاعات فایل «مدیریت وظایف» به‌روزرسانی شود. همچنین در صورت نیاز می‌توانید از طریق شماره داخلی ۷۴۸۸ با مهندس قائمی در ارتباط باشید.\n\nتاریخ گزارش: [تاریخ کامل شمسی]\n\nبا تشکر و احترام\nسامانه خودکار پایش و پیگیری امور\nشرکت خودروسازان بم\nواحد مهندسی محصول`},
state5:{subject:'گزارش روزانه وضعیت امور | [تاریخ کامل شمسی] | اقدام فوری',body:`[عنوان و نام مخاطب]\n\nبا درود و مهر،\n\nبررسی آخرین اطلاعات ثبت‌شده در فایل «مدیریت وظایف» نشان می‌دهد که [تعداد امور دیرکردی] مورد از فعالیت‌های حوزه مسئولیت شما در وضعیت «دیرکرد» قرار گرفته‌اند و نیازمند رسیدگی و اقدام فوری هستند.\n\nخلاصه وضعیت: [تعداد امور هشداری] مورد هشداری | [تعداد امور دیرکردی] مورد دیرکردی\n\n[استیکر]\n\n[جدول امور دیرکردی]\n\n[جدول امور هشداری]\n\nخواهشمند است موارد فوق در اولویت پیگیری قرار گرفته و اقدامات مقتضی برای تعیین تکلیف و تکمیل آن‌ها در سریع‌ترین زمان ممکن انجام شود.\n\nچنانچه هر یک از فعالیت‌ها انجام شده، پیشرفت داشته یا وضعیت آن تغییر کرده است، لطفاً با پاسخ به همین ایمیل، مراتب را اعلام فرمایید تا اطلاعات فایل «مدیریت وظایف» به‌روزرسانی شود. همچنین در صورت نیاز می‌توانید از طریق شماره داخلی ۷۴۸۸ با مهندس قائمی در ارتباط باشید.\n\nتاریخ گزارش: [تاریخ کامل شمسی]\n\nبا تشکر و احترام\nسامانه خودکار پایش و پیگیری امور\nشرکت خودروسازان بم\nواحد مهندسی محصول`},
followup:{subject:'یادآوری مجدد وضعیت امور | [تاریخ کامل شمسی]',body:`[عنوان و نام مخاطب]\n\nبا درود و مهر،\n\nپیرو آخرین گزارش ارسال‌شده درباره وضعیت امور در تاریخ [تاریخ آخرین ارسال]، تاکنون پاسخی از سوی شما دریافت نشده است.\n\nخواهشمند است در صورت انجام فعالیت‌ها، ایجاد پیشرفت یا تغییر در آخرین وضعیت امور، مراتب را از طریق پاسخ به همین ایمیل اعلام فرمایید تا اطلاعات فایل «مدیریت وظایف» به‌روزرسانی شود.\n\nهمچنین در صورت نیاز می‌توانید از طریق شماره داخلی ۷۴۸۸ با مهندس قائمی در ارتباط باشید.\n\nبا تشکر و احترام\nسامانه خودکار پایش و پیگیری امور\nشرکت خودروسازان بم\nواحد مهندسی محصول`}
};
let people=[],templates=structuredClone(DESKTOP_TEMPLATES),followRows=[],customStickers={};
const exactIsManager=()=>state?.profile?.role==='manager';
const getOwner=t=>state.profiles.find(p=>p.id===t.owner_id)?.full_name||t.legacy_owner_name||'—';
const dayDiff=(a,b)=>{if(!a||!b)return 0;const aa=new Date(a+'T12:00:00'),bb=new Date(b+'T12:00:00');return Math.round((aa-bb)/86400000)};
function calcDelay(t){const n=dayDiff(t.done_date,t.due_date);return{delay:n>0?n:0,advance:n<0?-n:0}}
function desktopLogo(){document.querySelectorAll('.desktop-topbar img,.side-brand img').forEach(img=>{if(A().header_logo)img.src=A().header_logo})}
function menu(){
 const sidebar=document.querySelector('#sidebar'),nav=document.querySelector('#nav'); if(!sidebar||!nav)return;
 sidebar.querySelector('.desktop-menu-title')?.remove();
 const title=document.createElement('div'); title.className='desktop-menu-title'; title.innerHTML='<span>منوی اصلی</span><button class="desktop-menu-toggle" title="باز/بسته کردن منو"><span class="close-icon">◀◀</span><span class="open-icon">▶▶</span></button>'; sidebar.insertBefore(title,nav);
 title.querySelector('button').onclick=()=>sidebar.classList.toggle('collapsed');
 const labels={file:'تنظیمات فایل',dashboard:'داشبورد',people:'افراد و رونوشت‌ها',send:'انتخاب و ارسال',templates:'متن ایمیل‌ها',stickers:'مدیریت استیکرها',followup:'پیگیری پاسخ‌ها',kanban:'کانبان',archive:'آرشیو',approvals:'تأیید درخواست‌ها'};
 const icons={file:'⚙',dashboard:'▦',people:'♙',send:'✉',templates:'≡',stickers:'◇',followup:'↻',kanban:'▤',archive:'▣',approvals:'✓'};
 [...nav.querySelectorAll('button.manager-only')].forEach(x=>x.remove());
 if(!nav.querySelector('[data-view=file]'))nav.insertAdjacentHTML('afterbegin','<button data-view="file"><b>⚙</b><span>تنظیمات فایل</span></button>');
 ['people','send','templates','stickers','followup'].forEach(v=>{if(!nav.querySelector(`[data-view=${v}]`))nav.insertAdjacentHTML('beforeend',`<button data-view="${v}" class="desktop-manager-nav"><b>${icons[v]}</b><span>${labels[v]}</span></button>`)});
 const order=['file','dashboard','people','send','templates','stickers','followup','kanban','archive','approvals']; order.forEach(v=>{const b=nav.querySelector(`[data-view=${v}]`);if(b){b.querySelector('span').textContent=labels[v];b.querySelector('b').textContent=icons[v];nav.appendChild(b)}});
 if(!exactIsManager())['people','send','templates','stickers','followup','approvals'].forEach(v=>nav.querySelector(`[data-view=${v}]`)?.classList.add('hidden'));
 nav.querySelectorAll('button').forEach(b=>{if(b.dataset.exactBound)return;b.dataset.exactBound='1';b.addEventListener('click',()=>openExactView(b.dataset.view))});
}
function removeOldManagerViews(){['peopleView','sendView','templatesView','stickersView','followupView','mailsettingsView','fileViewExact'].forEach(id=>document.getElementById(id)?.remove())}
function addViews(){
 removeOldManagerViews(); const w=document.querySelector('.workspace');
 w.insertAdjacentHTML('beforeend',`
 <section id="fileViewExact" class="view hidden"><div class="desktop-screen"><div class="desktop-screen-title">فایل مدیریت وظایف</div><div class="file-grid"><label>انتخاب فایل</label><button id="importPickBtn" class="desktop-action small">انتخاب فایل</button><input id="importPath" class="desktop-entry english path-entry" readonly placeholder="فایل Excel یا CSV برای ورود تسک‌ها"><input id="importFile" class="hidden-file" type="file" accept=".xlsx,.xls,.csv"><label>رمز فایل</label><input id="importPassword" class="desktop-entry" type="password"><label>نام شیت</label><input id="importSheet" class="desktop-entry english" value="KANBAN"><span></span><button id="importRunBtn" class="desktop-action small" style="min-width:190px">خواندن و بررسی فایل</button></div><div id="importStatus" class="desktop-status" style="margin-top:18px">برای ورود گروهی تسک، فایل Excel یا CSV را انتخاب کنید.</div></div></section>
 <section id="peopleView" class="view hidden"><div class="desktop-screen"><div class="desktop-toolbar"><button id="personAdd" class="desktop-action">افزودن فرد</button><button id="personEdit" class="desktop-action">ویرایش</button><button id="personDelete" class="desktop-action">حذف</button></div><div class="desktop-table-wrap"><table class="desktop-table"><thead><tr><th>نام در اکسل</th><th>جنسیت</th><th>ایمیل</th><th>عنوان ایمیل</th><th>رونوشت</th><th>فعال</th></tr></thead><tbody id="exactPeopleBody"></tbody></table></div></div></section>
 <section id="sendView" class="view hidden"><div class="desktop-screen"><fieldset class="desktop-fieldset"><legend>نحوه ارسال</legend><div class="desktop-toolbar between"><button id="runSelected" class="desktop-action desktop-big-run">اجرای عملیات برای افراد انتخاب‌شده</button><div class="email-mode"><label><input type="radio" name="sendMode" value="preview">پیش‌نمایش در اوت‌لوک</label><label><input type="radio" name="sendMode" value="direct" checked>ارسال مستقیم</label><span id="bridgeStateSend" class="desktop-status" style="min-height:0;padding:7px 10px">در حال بررسی Outlook…</span></div></div></fieldset><div class="desktop-toolbar"><button id="pickAll" class="desktop-action small">انتخاب همه</button><button id="clearAll" class="desktop-action small">لغو همه</button><button id="pickOverdue" class="desktop-action small">فقط دیرکرد</button><button id="pickWarning" class="desktop-action small">فقط هشدار</button></div><div class="desktop-table-wrap"><table class="desktop-table"><thead><tr><th>نام</th><th>ایمیل</th><th>وضعیت</th><th>هشدار</th><th>دیرکرد</th><th>استیکر</th><th>انتخاب</th></tr></thead><tbody id="exactSendBody"></tbody></table></div></div></section>
 <section id="templatesView" class="view hidden"><div class="desktop-screen"><fieldset class="desktop-fieldset"><legend>ویرایش متن ایمیل</legend><div class="template-selector-row"><select id="templateKey" class="desktop-entry">${Object.keys(stateLabels).map(k=>`<option value="${k}">${stateLabels[k]}</option>`).join('')}</select><button id="openTemplateEditor" class="desktop-action small">ویرایش متن</button><button id="restoreTemplate" class="desktop-action small light">بازگردانی متن اصلی</button></div></fieldset><div class="desktop-note">متن‌ها عین نسخه دسکتاپ BAMCO بارگذاری شده‌اند و قابل ویرایش هستند.</div></div></section>
 <section id="stickersView" class="view hidden"><div class="desktop-screen"><fieldset class="desktop-fieldset"><legend>پیش‌نمایش و انتخاب نسخه</legend><div class="sticker-top"><label>وضعیت</label><select id="stickerState" class="desktop-entry">${Object.keys(stateLabels).filter(k=>k!=='followup').map(k=>`<option value="${k}">${stateLabels[k]}</option>`).join('')}</select><label><input type="radio" name="stickerGender" value="female" checked> خانم</label><label><input type="radio" name="stickerGender" value="male"> آقا</label></div></fieldset><fieldset class="desktop-fieldset"><legend>مدیریت نسخه‌ها</legend><div class="sticker-packs"><select id="stickerPack" class="desktop-entry"><option>نسخه اصلی</option></select><button id="activateSticker" class="desktop-action small">فعال‌سازی نسخه</button><button id="uploadSticker" class="desktop-action small">افزودن نسخه جدید</button><button id="restoreStickers" class="desktop-action small">بازگردانی نسخه اصلی</button><input id="stickerFile" class="hidden-file" type="file" accept="image/*"></div></fieldset><div class="sticker-preview-area"><img id="stickerPreview" alt="پیش‌نمایش استیکر"></div></div></section>
 <section id="followupView" class="view hidden"><div class="desktop-screen"><div class="desktop-toolbar between"><div class="group"><button id="checkReplies" class="desktop-action small">بررسی ایمیل‌ها و پاسخ‌ها</button><button id="selectUnanswered" class="desktop-action small">انتخاب افراد بدون پاسخ</button><button id="clearFollow" class="desktop-action small">لغو انتخاب</button></div><div class="group"><button id="followSend" class="desktop-action small">ارسال یادآوری</button><button id="followPreview" class="desktop-action small">پیش‌نمایش یادآوری</button></div></div><fieldset class="desktop-fieldset"><legend>بازه زمانی ارسال ایمیل</legend><div class="date-range"><label>از تاریخ <input id="followFromExact" class="desktop-entry" placeholder="۱۴۰۵/۰۱/۰۱"></label><label>تقویم شمسی</label><label>تا تاریخ <input id="followToExact" class="desktop-entry" placeholder="۱۴۰۵/۱۲/۲۹"></label><label>تقویم شمسی</label><button id="clearDates" class="desktop-action small light">پاک کردن بازه</button></div></fieldset><div id="bridgeStateFollow" class="desktop-status">در حال بررسی Outlook…</div><div class="desktop-table-wrap"><table class="desktop-table"><thead><tr><th>نام</th><th>ایمیل</th><th>موضوع ایمیل</th><th>زمان ارسال</th><th>پاسخ</th><th>انتخاب</th></tr></thead><tbody id="exactFollowBody"></tbody></table></div></div></section>
 <dialog id="templateDialogExact" class="modal desktop-dialog" style="width:min(1000px,calc(100% - 40px))"><div class="modal-head"><div><h3 id="templateDialogTitle">ویرایش متن ایمیل</h3><p>متن و موضوع دقیقاً قابل ویرایش است.</p></div><button onclick="this.closest('dialog').close()">×</button></div><label>موضوع ایمیل<input id="templateSubjectExact" class="subject-editor"></label><label>متن ایمیل<textarea id="templateBodyExact" class="desktop-editor"></textarea></label><div class="modal-actions"><button id="saveTemplateExact" class="desktop-action small">ذخیره</button><button onclick="this.closest('dialog').close()" class="desktop-action small light">انصراف</button></div></dialog>
 <dialog id="personDialogExact" class="modal desktop-dialog" style="width:min(760px,calc(100% - 40px))"><div class="modal-head"><h3 id="personTitleExact">افزودن فرد</h3><button onclick="this.closest('dialog').close()">×</button></div><div class="person-form-grid"><label>نام در اکسل</label><input id="pName"><label>جنسیت</label><select id="pGender"><option>خانم</option><option>آقا</option></select><label>ایمیل</label><input id="pEmail" class="english"><label>عنوان ایمیل</label><input id="pSalutation"><label>رونوشت</label><input id="pCc" class="english"><label>فعال</label><label><input id="pActive" type="checkbox" checked> بله</label></div><div class="modal-actions"><button id="savePersonExact" class="desktop-action small">ذخیره</button><button onclick="this.closest('dialog').close()" class="desktop-action small light">انصراف</button></div></dialog>`);
 bindExact();
}
function openExactView(view){
 if(['file','people','send','templates','stickers','followup'].includes(view)){
   document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden')); const id=view==='file'?'fileViewExact':view+'View';document.getElementById(id)?.classList.remove('hidden');
   document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
   if(view==='people')loadPeople(); if(view==='send'){loadPeople().then(renderSend);checkBridge()} if(view==='templates')loadTemplates(); if(view==='stickers')renderSticker(); if(view==='followup'){loadPeople();renderFollow();checkBridge()}
 }
}
async function loadPeople(){try{people=await select('profiles','select=*&order=full_name');}catch{people=state.profiles||[]}renderPeople();return people}
let selectedPersonId=null;
function renderPeople(){const body=document.getElementById('exactPeopleBody');if(!body)return;body.innerHTML=people.map(p=>`<tr data-id="${p.id}" class="${p.id===selectedPersonId?'selected':''}"><td>${esc(p.full_name||'')}</td><td>${esc(p.gender||'')}</td><td class="english">${esc(p.email||'')}</td><td>${esc(p.salutation||'')}</td><td class="english">${esc(Array.isArray(p.cc_emails)?p.cc_emails.join('; '):p.cc_emails||'')}</td><td>${p.active===false?'خیر':'بله'}</td></tr>`).join('')}
const overdueCount=p=>state.tasks.filter(t=>!t.archived&&t.owner_id===p.id&&norm(t.due_state)==='دیرکرد').length;
const warningCount=p=>state.tasks.filter(t=>!t.archived&&t.owner_id===p.id&&norm(t.due_state)==='دوره هشدار').length;
function stickerKey(p){const o=overdueCount(p),w=warningCount(p);return o>=5?'state5':o>=3?'state4':o>=1?'state3':w>0?'state2':'state1'}
function renderSend(){const body=document.getElementById('exactSendBody');if(!body)return;body.innerHTML=people.filter(p=>p.active!==false).map(p=>{const k=stickerKey(p);return`<tr><td>${esc(p.full_name||'')}</td><td class="english">${esc(p.email||'')}</td><td>${stateLabels[k]}</td><td>${fa(warningCount(p))}</td><td>${fa(overdueCount(p))}</td><td>${fa(['state1','state2','state3','state4','state5'].indexOf(k)+1)}</td><td><input class="sendPickExact" data-id="${p.id}" type="checkbox" checked></td></tr>`}).join('')}
async function loadTemplates(){templates=structuredClone(DESKTOP_TEMPLATES);try{const rows=await select('email_templates','select=*');for(const r of rows){if(templates[r.template_key]&&r.body_html)templates[r.template_key].body=r.body_html.replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,'')}}catch{}try{const x=JSON.parse(localStorage.getItem('bamco_exact_templates')||'null');if(x)templates=x}catch{}}
function openTemplate(){const k=document.getElementById('templateKey').value,t=templates[k]||DESKTOP_TEMPLATES[k];document.getElementById('templateDialogTitle').textContent=`ویرایش متن «${stateLabels[k]}»`;document.getElementById('templateSubjectExact').value=t.subject;document.getElementById('templateBodyExact').value=t.body;document.getElementById('templateDialogExact').showModal()}
async function saveTemplate(){const k=document.getElementById('templateKey').value;templates[k]={subject:document.getElementById('templateSubjectExact').value.trim(),body:document.getElementById('templateBodyExact').value};try{const existing=await select('email_templates',`template_key=eq.${k}&select=id`);const body_html=templates[k].body.replace(/\n/g,'<br>');if(existing.length)await update('email_templates',`template_key=eq.${k}`,{body_html,updated_by:state.profile.id,updated_at:new Date().toISOString()});else await insert('email_templates',{template_key:k,body_html,updated_by:state.profile.id});}catch{}localStorage.setItem('bamco_exact_templates',JSON.stringify(templates));document.getElementById('templateDialogExact').close();toast('متن ایمیل ذخیره شد.')}
function stickerAsset(k,g){const prefix={state1:'01_happy',state2:'02_reminder',state3:'03_concerned',state4:'04_serious',state5:'05_urgent'}[k];const custom=customStickers[`${k}_${g}`];return custom||A()[`${prefix}_${g}`]||`${SB_URL}/storage/v1/object/public/stickers/${k}_${g}.png`}
function renderSticker(){const k=document.getElementById('stickerState')?.value||'state1',g=document.querySelector('input[name=stickerGender]:checked')?.value||'female';const img=document.getElementById('stickerPreview');if(img)img.src=stickerAsset(k,g)}
async function bridge(path,payload={}){const r=await fetch(`http://127.0.0.1:8765${path}`,{method:path==='/health'?'GET':'POST',headers:{'Content-Type':'application/json'},body:path==='/health'?undefined:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok||data.ok===false)throw new Error(data.error||'Outlook Bridge در دسترس نیست.');return data}
async function checkBridge(){for(const id of ['bridgeStateSend','bridgeStateFollow']){const el=document.getElementById(id);if(!el)continue;try{await bridge('/health');el.textContent='Outlook باز و آماده است';el.classList.add('ok');el.classList.remove('bad')}catch{el.textContent='Outlook/Bridge در دسترس نیست';el.classList.add('bad');el.classList.remove('ok')}}}
function taskRows(p,bucket){return state.tasks.filter(t=>!t.archived&&t.owner_id===p.id&&norm(t.due_state)===bucket)}
function tableHtml(title,rows){if(!rows.length)return'';return`<div style="font-family:'B Nazanin';direction:rtl;text-align:right"><b>${title}</b><table dir="rtl" style="border-collapse:collapse;width:100%;margin:8px 0"><tr>${['شناسه','عنوان فعالیت','وضعیت','تاریخ پایان'].map(h=>`<th style="border:1px solid #aaa;background:#dfece6;padding:7px">${h}</th>`).join('')}</tr>${rows.map(t=>`<tr><td style="border:1px solid #bbb;padding:7px">${fa(displayId(t))}</td><td style="border:1px solid #bbb;padding:7px">${esc(t.title)}</td><td style="border:1px solid #bbb;padding:7px">${esc(t.status)}</td><td style="border:1px solid #bbb;padding:7px">${jalaliText(t.due_date)}</td></tr>`).join('')}</table></div>`}
function renderMail(p){const k=stickerKey(p),t=templates[k]||DESKTOP_TEMPLATES[k],w=taskRows(p,'دوره هشدار'),o=taskRows(p,'دیرکرد'),date=jalaliText(new Date());let body=t.body.replaceAll('[عنوان و نام مخاطب]',p.salutation||p.full_name||'').replaceAll('[تعداد امور هشداری]',fa(w.length)).replaceAll('[تعداد امور دیرکردی]',fa(o.length)).replaceAll('[تاریخ کامل شمسی]',date).replaceAll('[جدول امور هشداری]',tableHtml('امور در دوره هشدار',w)).replaceAll('[جدول امور دیرکردی]',tableHtml('امور دارای دیرکرد',o)).replaceAll('[استیکر]','<img src="cid:bamco_sticker" style="max-width:260px">');let html=body.replace(/\n/g,'<br>');let subject=t.subject.replaceAll('[تاریخ کامل شمسی]',date);return{subject,html,k,sticker:stickerAsset(k,p.gender==='آقا'?'male':'female')}}
async function runSelected(){const mode=document.querySelector('input[name=sendMode]:checked')?.value||'direct',ids=[...document.querySelectorAll('.sendPickExact:checked')].map(x=>x.dataset.id);if(!ids.length)return toast('هیچ فردی انتخاب نشده است.',true);if(!confirm(`${mode==='direct'?'ارسال مستقیم':'پیش‌نمایش'} برای ${fa(ids.length)} نفر انجام شود؟`))return;for(const id of ids){const p=people.find(x=>x.id===id);if(!p)continue;const m=renderMail(p);await bridge(mode==='direct'?'/mail/send':'/mail/preview',{to:p.email,cc:Array.isArray(p.cc_emails)?p.cc_emails:[],subject:m.subject,html:m.html,inline_image:m.sticker})}toast(`${fa(ids.length)} مورد آماده شد.`)}
function renderFollow(){const body=document.getElementById('exactFollowBody');if(!body)return;body.innerHTML=followRows.length?followRows.map((r,i)=>`<tr><td>${esc(r.name)}</td><td class="english">${esc(r.email)}</td><td>${esc(r.subject||'')}</td><td>${esc(r.sent_display||r.sent_on||'')}</td><td>${r.responded?'پاسخ داده':'بدون پاسخ'}</td><td><input class="followPickExact" data-index="${i}" type="checkbox" ${!r.responded?'checked':''}></td></tr>`).join(''):'<tr><td colspan="6" style="text-align:center;height:100px">برای بررسی، دکمه «بررسی ایمیل‌ها و پاسخ‌ها» را بزنید.</td></tr>'}
async function checkRepliesExact(){const emails=people.filter(p=>p.active!==false).map(p=>p.email);const res=await bridge('/replies/scan',{emails,days:90});followRows=people.filter(p=>p.active!==false).map(p=>{const rr=res.replies?.[String(p.email).toLowerCase()];return{name:p.full_name,email:p.email,subject:rr?.subject||'',sent_on:rr?.received_at||'',responded:!!rr}});renderFollow();toast('بررسی پاسخ‌ها انجام شد.')}
async function sendFollow(preview){const rows=[...document.querySelectorAll('.followPickExact:checked')].map(x=>followRows[Number(x.dataset.index)]).filter(Boolean);if(!rows.length)return toast('هیچ موردی انتخاب نشده است.',true);for(const r of rows){const p=people.find(x=>x.email===r.email);let t=templates.followup||DESKTOP_TEMPLATES.followup;let body=t.body.replaceAll('[عنوان و نام مخاطب]',p?.salutation||p?.full_name||r.name).replaceAll('[تاریخ کامل شمسی]',jalaliText(new Date())).replaceAll('[تاریخ آخرین ارسال]',r.sent_on?jalaliDateTime(r.sent_on):'—').replace(/\n/g,'<br>');await bridge(preview?'/followup/preview':'/followup/send',{recipient:r.email,subject_hint:'گزارش روزانه وضعیت امور',html:body,days:90})}toast(`${fa(rows.length)} یادآوری ${preview?'برای پیش‌نمایش باز شد':'ارسال شد'}.`)}
function bindExact(){
 document.getElementById('importPickBtn').onclick=()=>document.getElementById('importFile').click();document.getElementById('importFile').onchange=e=>{document.getElementById('importPath').value=e.target.files?.[0]?.name||''};document.getElementById('importRunBtn').onclick=importTasks;
 document.getElementById('exactPeopleBody').onclick=e=>{const tr=e.target.closest('tr[data-id]');if(tr){selectedPersonId=tr.dataset.id;renderPeople()}};document.getElementById('personAdd').onclick=()=>openPerson();document.getElementById('personEdit').onclick=()=>{const p=people.find(x=>x.id===selectedPersonId);if(!p)return toast('یک فرد را انتخاب کنید.',true);openPerson(p)};document.getElementById('personDelete').onclick=()=>toast('حذف حساب کاربری از این بخش انجام نمی‌شود؛ می‌توانید فرد را غیرفعال کنید.',true);
 document.getElementById('runSelected').onclick=()=>runSelected().catch(e=>toast(e.message,true));document.getElementById('pickAll').onclick=()=>document.querySelectorAll('.sendPickExact').forEach(x=>x.checked=true);document.getElementById('clearAll').onclick=()=>document.querySelectorAll('.sendPickExact').forEach(x=>x.checked=false);document.getElementById('pickOverdue').onclick=()=>document.querySelectorAll('.sendPickExact').forEach(x=>{const p=people.find(p=>p.id===x.dataset.id);x.checked=overdueCount(p)>0});document.getElementById('pickWarning').onclick=()=>document.querySelectorAll('.sendPickExact').forEach(x=>{const p=people.find(p=>p.id===x.dataset.id);x.checked=warningCount(p)>0&&overdueCount(p)===0});
 document.getElementById('openTemplateEditor').onclick=openTemplate;document.getElementById('saveTemplateExact').onclick=saveTemplate;document.getElementById('restoreTemplate').onclick=()=>{const k=document.getElementById('templateKey').value;templates[k]=structuredClone(DESKTOP_TEMPLATES[k]);openTemplate()};
 document.getElementById('stickerState').onchange=renderSticker;document.querySelectorAll('input[name=stickerGender]').forEach(x=>x.onchange=renderSticker);document.getElementById('uploadSticker').onclick=()=>document.getElementById('stickerFile').click();document.getElementById('stickerFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{const k=document.getElementById('stickerState').value,g=document.querySelector('input[name=stickerGender]:checked').value;customStickers[`${k}_${g}`]=rd.result;localStorage.setItem('bamco_custom_stickers',JSON.stringify(customStickers));renderSticker()};rd.readAsDataURL(f)};document.getElementById('restoreStickers').onclick=()=>{customStickers={};localStorage.removeItem('bamco_custom_stickers');renderSticker();toast('نسخه اصلی استیکرها فعال شد.')};
 document.getElementById('checkReplies').onclick=()=>checkRepliesExact().catch(e=>toast(e.message,true));document.getElementById('selectUnanswered').onclick=()=>document.querySelectorAll('.followPickExact').forEach(x=>{const r=followRows[Number(x.dataset.index)];x.checked=!r.responded});document.getElementById('clearFollow').onclick=()=>document.querySelectorAll('.followPickExact').forEach(x=>x.checked=false);document.getElementById('followPreview').onclick=()=>sendFollow(true).catch(e=>toast(e.message,true));document.getElementById('followSend').onclick=()=>sendFollow(false).catch(e=>toast(e.message,true));document.getElementById('clearDates').onclick=()=>{document.getElementById('followFromExact').value='';document.getElementById('followToExact').value=''};
 document.getElementById('savePersonExact').onclick=savePerson;
}
let editingPerson=null;function openPerson(p=null){editingPerson=p;document.getElementById('personTitleExact').textContent=p?'ویرایش فرد':'افزودن فرد';document.getElementById('pName').value=p?.full_name||'';document.getElementById('pGender').value=p?.gender||'خانم';document.getElementById('pEmail').value=p?.email||'';document.getElementById('pSalutation').value=p?.salutation||'';document.getElementById('pCc').value=Array.isArray(p?.cc_emails)?p.cc_emails.join('; '):'';document.getElementById('pActive').checked=p?.active!==false;document.getElementById('personDialogExact').showModal()}
async function savePerson(){if(!editingPerson)return toast('برای افزودن حساب جدید ابتدا کاربر باید در Authentication ساخته شود.',true);const payload={full_name:document.getElementById('pName').value.trim(),gender:document.getElementById('pGender').value,email:document.getElementById('pEmail').value.trim(),salutation:document.getElementById('pSalutation').value.trim(),cc_emails:document.getElementById('pCc').value.split(';').map(x=>x.trim()).filter(Boolean),active:document.getElementById('pActive').checked};await update('profiles',`id=eq.${editingPerson.id}`,payload);document.getElementById('personDialogExact').close();toast('مشخصات ذخیره شد.');await loadPeople()}
function faKey(o,...keys){for(const k of keys)if(o[k]!==undefined&&o[k]!==null&&String(o[k]).trim()!=='')return o[k];return null}
function isoDate(v){if(!v)return null;if(v instanceof Date&&!isNaN(v))return v.toISOString().slice(0,10);if(typeof v==='number'&&window.XLSX?.SSF){const d=XLSX.SSF.parse_date_code(v);if(d)return`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}const s=String(v).trim();if(/^\d{4}-\d{1,2}-\d{1,2}$/.test(s)){const [y,m,d]=s.split('-');return`${y}-${m.padStart(2,'0')}-${d.padStart(2,'0')}`}return null}
async function importTasks(){if(!exactIsManager())return toast('فقط مدیر اجازه ورود گروهی تسک دارد.',true);const file=document.getElementById('importFile').files?.[0];if(!file)return toast('ابتدا فایل را انتخاب کنید.',true);const status=document.getElementById('importStatus');try{status.textContent='در حال خواندن فایل…';let rows=[];if(file.name.toLowerCase().endsWith('.csv')){const txt=await file.text();const wb=XLSX.read(txt,{type:'string'});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}else{const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:true});const sn=document.getElementById('importSheet').value.trim();const sheet=wb.Sheets[sn]||wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sheet,{defval:''})}if(!people.length)await loadPeople();let ok=0,skip=0;const errors=[];for(const r of rows){const title=faKey(r,'عنوان فعالیت','عنوان کار','عنوان','title');if(!title){skip++;continue}const ownerText=String(faKey(r,'متولی','نام در اکسل','owner','ایمیل')||'').trim();const owner=people.find(p=>norm(p.full_name)===norm(ownerText)||String(p.email).toLowerCase()===ownerText.toLowerCase());if(!owner){errors.push(`متولی پیدا نشد: ${ownerText||'خالی'} | ${title}`);skip++;continue}const payload={title:String(title),description:String(faKey(r,'توضیحات','description')||''),owner_id:owner.id,status:String(faKey(r,'وضعیت','status')||'ثبت شده'),priority:String(faKey(r,'اولویت','priority')||'متوسط'),start_date:isoDate(faKey(r,'تاریخ شروع','start_date')),done_date:isoDate(faKey(r,'تاریخ انجام','done_date')),due_date:isoDate(faKey(r,'تاریخ پایان','due_date')),reminder_days:Number(faKey(r,'یادآور','reminder_days')||0),manager_notes:String(faKey(r,'توضیحات مدیر','manager_notes')||''),created_by:state.profile.id};await insert('tasks',payload);ok++}status.className='desktop-status '+(errors.length?'bad':'ok');status.textContent=`${fa(ok)} تسک وارد شد. ${fa(skip)} ردیف رد شد.${errors.length?'\n'+errors.slice(0,8).join('\n'):''}`;await refresh();}catch(e){status.className='desktop-status bad';status.textContent='خطا در ورود فایل: '+e.message}}
function exactTaskRender(archived){const body=archived?document.getElementById('archiveBody'):document.getElementById('kanbanBody');if(!body)return;const input=archived?document.getElementById('archiveSearch'):document.getElementById('kanbanSearch'),q=(input?.value||'').trim().toLowerCase();const rows=state.tasks.filter(t=>!!t.archived===archived).filter(t=>!q||Object.values(t).some(v=>String(v??'').toLowerCase().includes(q))||getOwner(t).toLowerCase().includes(q));if(archived){body.innerHTML=rows.map(t=>{const d=calcDelay(t);return`<tr><td>${fa(displayId(t))}</td><td>${esc(t.title)}</td><td>${esc(t.description||'')}</td><td>${esc(getOwner(t))}</td><td>${esc(t.status||'')}</td><td>${esc(t.priority||'')}</td><td>${jalaliText(t.start_date)}</td><td>${jalaliText(t.done_date)}</td><td>${jalaliText(t.due_date)}</td><td>${fa(t.reminder_days||0)}</td><td>${jalaliDateTime(t.last_updated_at||t.updated_at)}</td><td>${esc(t.due_state||'')}</td><td>${esc(t.manager_notes||'')}</td><td class="delay-bad">${d.delay?fa(d.delay):'—'}</td><td class="delay-good">${d.advance?fa(d.advance):'—'}</td></tr>`}).join('')||'<tr><td colspan="15">موردی وجود ندارد.</td></tr>'}else{body.innerHTML=rows.map(t=>`<tr><td>${fa(displayId(t))}</td><td>${esc(t.title)}</td><td>${esc(t.description||'')}</td><td>${esc(getOwner(t))}</td><td>${esc(t.status||'')}</td><td>${esc(t.priority||'')}</td><td>${jalaliText(t.start_date)}</td><td>${jalaliText(t.done_date)}</td><td>${jalaliText(t.due_date)}</td><td>${fa(t.reminder_days||0)}</td><td>${jalaliDateTime(t.last_updated_at||t.updated_at)}</td><td>${esc(t.due_state||'')}</td><td>${esc(t.manager_notes||'')}</td><td><button class="icon-btn" onclick="openEdit('${t.id}')">${exactIsManager()?'ویرایش':'درخواست تغییر'}</button></td></tr>`).join('')||'<tr><td colspan="14">موردی وجود ندارد.</td></tr>'}}
function patchTaskTables(){const kv=document.querySelector('#kanbanView table'),av=document.querySelector('#archiveView table');if(kv){kv.classList.add('desktop-table','kanban-wide');kv.querySelector('thead').innerHTML='<tr><th>شناسه</th><th>عنوان فعالیت</th><th>توضیحات</th><th>متولی</th><th>وضعیت</th><th>اولویت</th><th>تاریخ شروع</th><th>تاریخ انجام</th><th>تاریخ پایان</th><th>یادآور</th><th>آخرین به روز رسانی</th><th>وضعیت دیرکرد</th><th>توضیحات مدیر</th><th></th></tr>';kv.closest('.table-wrap')?.classList.add('desktop-table-wrap')}if(av){av.classList.add('desktop-table','archive-wide');av.querySelector('thead').innerHTML='<tr><th>شناسه</th><th>عنوان فعالیت</th><th>توضیحات</th><th>متولی</th><th>وضعیت</th><th>اولویت</th><th>تاریخ شروع</th><th>تاریخ انجام</th><th>تاریخ پایان</th><th>یادآور</th><th>آخرین به روز رسانی</th><th>وضعیت دیرکرد</th><th>توضیحات مدیر</th><th>تاخیر</th><th>تعجیل</th></tr>';av.closest('.table-wrap')?.classList.add('desktop-table-wrap')}
 renderTasks=function(archived){exactTaskRender(archived)};document.getElementById('kanbanSearch')?.addEventListener('input',()=>exactTaskRender(false));document.getElementById('archiveSearch')?.addEventListener('input',()=>exactTaskRender(true));
}
function init(){try{customStickers=JSON.parse(localStorage.getItem('bamco_custom_stickers')||'{}')}catch{}setTimeout(()=>{desktopLogo();menu();addViews();patchTaskTables();renderSticker();checkBridge();},250);setTimeout(desktopLogo,1200)}
document.addEventListener('DOMContentLoaded',init);
})();
