(()=>{
  const nav=document.querySelector('#nav');
  const workspace=document.querySelector('.workspace');
  if(!nav||!workspace)return;

  const navHtml=`
    <div class="nav-divider manager-only"></div>
    <button data-view="people" class="manager-only"><b>♙</b><span>افراد و رونوشت‌ها</span></button>
    <button data-view="send" class="manager-only"><b>✉</b><span>انتخاب و ارسال</span></button>
    <button data-view="templates" class="manager-only"><b>≡</b><span>متن ایمیل‌ها</span></button>
    <button data-view="stickers" class="manager-only"><b>◇</b><span>مدیریت استیکرها</span></button>
    <button data-view="followup" class="manager-only"><b>↻</b><span>پیگیری پاسخ‌ها</span></button>
    <button data-view="settings"><b>⚙</b><span>تنظیمات</span></button>`;
  nav.insertAdjacentHTML('beforeend',navHtml);

  const views=`
  <section id="peopleView" class="view hidden manager-only"><div class="panel table-panel"><div class="panel-head"><div><h3>افراد و رونوشت‌ها</h3><small>مدیریت گیرندگان ایمیل و رونوشت‌ها</small></div><div class="manager-toolbar"><input id="peopleSearch" class="search" placeholder="جست‌وجو…"><button id="addPersonBtn" class="primary">＋ افزودن فرد</button></div></div><div class="table-wrap"><table class="manager-table"><thead><tr><th>فعال</th><th>نام</th><th>جنسیت</th><th>ایمیل</th><th>عنوان ایمیل</th><th>رونوشت</th><th></th></tr></thead><tbody id="peopleBody"></tbody></table></div></div></section>

  <section id="sendView" class="view hidden manager-only"><div class="panel"><div class="panel-head"><div><h3>انتخاب و ارسال</h3><small>ارسال گزارش روزانه با Outlook نصب‌شده روی ویندوز</small></div><div class="manager-toolbar"><button id="selectAllSend" class="ghost">انتخاب همه</button><button id="previewSelected" class="ghost">پیش‌نمایش</button><button id="sendSelected" class="primary">ارسال مستقیم</button></div></div><div class="send-summary"><article><small>افراد</small><strong id="sendPeopleCount">۰</strong></article><article><small>هشدار</small><strong id="sendWarningCount">۰</strong></article><article><small>دیرکرد</small><strong id="sendOverdueCount">۰</strong></article><article><small>انتخاب‌شده</small><strong id="sendPickedCount">۰</strong></article></div><div class="manager-warning" id="mailConnectionNotice">در حال بررسی رابط Outlook…</div><div class="table-wrap"><table class="manager-table"><thead><tr><th>انتخاب</th><th>نام</th><th>ایمیل</th><th>وضعیت</th><th>هشدار</th><th>دیرکرد</th><th>استیکر</th></tr></thead><tbody id="sendBody"></tbody></table></div></div></section>

  <section id="templatesView" class="view hidden manager-only"><div class="panel"><div class="panel-head"><div><h3>متن ایمیل‌ها</h3><small>متن گزارش بر اساس وضعیت گیرنده</small></div><div class="manager-toolbar"><select id="templateState"><option value="state1">وضعیت مطلوب</option><option value="state2">یادآوری</option><option value="state3">نیازمند توجه</option><option value="state4">پیگیری جدی</option><option value="state5">اقدام فوری</option><option value="followup">یادآوری مجدد</option></select><button id="saveTemplateBtn" class="primary">ذخیره متن</button></div></div><div class="manager-note">متغیرهای قابل استفاده: [عنوان مخاطب]، [تعداد هشدار]، [تعداد دیرکرد]، [جدول امور هشداری]، [جدول امور دیرکردی]، [استیکر]، [تاریخ گزارش]</div><textarea id="templateBody" class="template-editor"></textarea></div></section>

  <section id="stickersView" class="view hidden manager-only"><div class="panel"><div class="panel-head"><div><h3>مدیریت استیکرها</h3><small>نسخه‌های زن و مرد برای پنج وضعیت</small></div><button id="refreshStickers" class="ghost">به‌روزرسانی</button></div><div id="stickerGrid" class="sticker-grid"></div></div></section>

  <section id="followupView" class="view hidden manager-only"><div class="panel"><div class="panel-head"><div><h3>پیگیری پاسخ‌ها</h3><small>بررسی مستقیم پوشه‌های ارسال و دریافت Outlook</small></div><div class="manager-toolbar"><button id="checkRepliesBtn" class="ghost">بررسی ایمیل‌ها و پاسخ‌ها</button><button id="sendFollowupBtn" class="primary">ارسال یادآوری</button></div></div><div class="follow-date-row"><label>از تاریخ شمسی<input id="followFrom" class="compact-input" placeholder="۱۴۰۵/۰۱/۰۱"></label><label>تا تاریخ شمسی<input id="followTo" class="compact-input" placeholder="۱۴۰۵/۱۲/۲۹"></label></div><div class="manager-warning">برای بررسی پاسخ‌ها، Outlook و رابط ویندوز باید روی رایانه ارسال‌کننده در حال اجرا باشند.</div><div class="table-wrap"><table class="manager-table"><thead><tr><th>انتخاب</th><th>نام</th><th>ایمیل</th><th>موضوع</th><th>زمان ارسال</th><th>پاسخ</th></tr></thead><tbody id="followBody"></tbody></table></div></div></section>

  <section id="settingsView" class="view hidden"><div class="panel"><div class="panel-head"><div><h3>تنظیمات حساب کاربری</h3><small>نام نمایشی، تصویر پروفایل و امنیت حساب</small></div></div><div class="manager-form"><label>نام نمایشی<input id="profileDisplayName"></label><label>ایمیل / نام کاربری<input id="profileEmail" class="english" dir="ltr" readonly></label><label class="wide-field">تصویر پروفایل<input id="profileAvatar" type="file" accept="image/png,image/jpeg,image/webp"></label></div><div class="modal-actions"><button id="changePasswordBtn" class="ghost">تغییر رمز عبور</button><button id="saveProfileBtn" class="primary">ذخیره پروفایل</button></div></div><div class="panel manager-only"><div class="panel-head"><div><h3>رابط Outlook ویندوز</h3><small>ارسال امن از حساب واردشده در Outlook Desktop؛ بدون Azure و بدون ذخیره رمز</small></div><span id="mailState" class="connection-state bad">در حال بررسی…</span></div><div class="manager-form"><label>تأخیر بین ارسال‌ها (ثانیه)<input id="sendDelay" type="number" min="0" value="2"></label><label>موضوع گزارش<input id="subjectPrefix" value="گزارش روزانه وضعیت امور"></label></div><div class="modal-actions"><button id="saveMailSettings" class="ghost">ذخیره تنظیمات</button><button id="connectMicrosoft" class="primary">بررسی اتصال Outlook</button></div></div></section>

  <dialog id="personDialog" class="modal manager-modal"><form id="personForm" method="dialog"><div class="modal-head"><div><h3 id="personDialogTitle">افزودن فرد</h3><p>اطلاعات حساب، گیرنده و رونوشت</p></div><button type="button" onclick="this.closest('dialog').close()">×</button></div><input name="id" type="hidden"><div class="manager-form"><label>نام کامل<input name="full_name" required></label><label>جنسیت<select name="gender"><option>آقا</option><option>خانم</option></select></label><label>ایمیل<input name="email" class="english" dir="ltr" type="email" required></label><label>رمز اولیه<input name="initial_password" class="english" dir="ltr" type="password" minlength="8"></label><label>عنوان ایمیل<input name="salutation"></label><label class="wide-field">رونوشت‌ها (با ; جدا کنید)<input name="cc_emails" class="english" dir="ltr"></label><label>فعال<select name="active"><option value="true">بله</option><option value="false">خیر</option></select></label></div><div class="modal-actions"><button type="button" class="ghost" onclick="this.closest('dialog').close()">انصراف</button><button type="submit" class="primary">ذخیره</button></div></form></dialog>

  <dialog id="emailPreviewDialog" class="modal manager-modal"><div class="modal-head"><div><h3>پیش‌نمایش ایمیل</h3><p id="previewRecipient"></p></div><button type="button" onclick="this.closest('dialog').close()">×</button></div><div id="emailPreviewBody" class="preview-email"></div></dialog>`;
  workspace.insertAdjacentHTML('beforeend',views);

  const managerTitles={people:'افراد و رونوشت‌ها',send:'انتخاب و ارسال',templates:'متن ایمیل‌ها',stickers:'مدیریت استیکرها',followup:'پیگیری پاسخ‌ها',settings:'تنظیمات'};
  const stateMeta={state1:'وضعیت مطلوب',state2:'یادآوری',state3:'نیازمند توجه',state4:'پیگیری جدی',state5:'اقدام فوری'};
  const BRIDGE_URL='http://127.0.0.1:8765';
  let followRows=[];
  let people=[],templates=[],settings={},editingPerson=null;
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const countByOwner=(ownerId,bucket)=>state.tasks.filter(t=>!t.archived&&t.owner_id===ownerId&&norm(t.due_state)===bucket).length;
  const stickerState=p=>{const o=countByOwner(p.id,'دیرکرد'),w=countByOwner(p.id,'دوره هشدار');if(o>=5)return'state5';if(o>=3)return'state4';if(o>=1)return'state3';if(w>0)return'state2';return'state1'};
  const ensureManager=()=>document.querySelector('#userRole')?.textContent==='مدیر سامانه';
  async function safeSelect(table,q='select=*'){try{return await select(table,q)}catch(e){console.warn(e);return[]}}

  async function loadPeople(){
    people=await safeSelect('profiles','select=*&order=full_name');
    if(!people.length)people=state.profiles||[];
    renderPeople();renderSend();
  }
  function renderPeople(){const q=(document.querySelector('#peopleSearch')?.value||'').trim().toLowerCase();const rows=people.filter(p=>!q||[p.full_name,p.email,p.salutation,(p.cc_emails||[]).join?.(';')].some(x=>String(x||'').toLowerCase().includes(q)));document.querySelector('#peopleBody').innerHTML=rows.map(p=>`<tr><td>${p.active!==false?'✓':'—'}</td><td>${esc(p.full_name)}</td><td>${esc(p.gender||'—')}</td><td class="english">${esc(p.email)}</td><td>${esc(p.salutation||'—')}</td><td class="english">${esc(Array.isArray(p.cc_emails)?p.cc_emails.join('; '):(p.cc_emails||'—'))}</td><td><button class="icon-btn" data-edit-person="${p.id}">ویرایش</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">اطلاعات افراد هنوز بارگذاری نشده است.</td></tr>';}
  function renderSend(){if(!document.querySelector('#sendBody'))return;const owners=people.filter(p=>p.active!==false&&p.role!=='manager'||p.active!==false);document.querySelector('#sendBody').innerHTML=owners.map(p=>{const w=countByOwner(p.id,'دوره هشدار'),o=countByOwner(p.id,'دیرکرد'),s=stickerState(p);return`<tr><td><input type="checkbox" class="send-pick" data-id="${p.id}"></td><td>${esc(p.full_name)}</td><td class="english">${esc(p.email)}</td><td>${stateMeta[s]}</td><td>${fa(w)}</td><td>${fa(o)}</td><td>${stateMeta[s]}</td></tr>`}).join('');document.querySelector('#sendPeopleCount').textContent=fa(owners.length);document.querySelector('#sendWarningCount').textContent=fa(owners.reduce((a,p)=>a+countByOwner(p.id,'دوره هشدار'),0));document.querySelector('#sendOverdueCount').textContent=fa(owners.reduce((a,p)=>a+countByOwner(p.id,'دیرکرد'),0));updatePicked()}
  function updatePicked(){const n=[...document.querySelectorAll('.send-pick:checked')].length;const e=document.querySelector('#sendPickedCount');if(e)e.textContent=fa(n)}

  async function loadTemplates(){templates=await safeSelect('email_templates','select=*&order=template_key');showTemplate()}
  function showTemplate(){const key=document.querySelector('#templateState')?.value;const row=templates.find(t=>t.template_key===key);if(document.querySelector('#templateBody'))document.querySelector('#templateBody').value=row?.body_html||''}
  async function saveTemplate(){const key=document.querySelector('#templateState').value,body_html=document.querySelector('#templateBody').value;const existing=templates.find(t=>t.template_key===key);try{if(existing)await update('email_templates',`id=eq.${existing.id}`,{body_html});else await insert('email_templates',{template_key:key,body_html});toast('متن ایمیل ذخیره شد.');await loadTemplates()}catch(e){toast('ابتدا فایل supabase_phase4.sql را در Supabase اجرا کنید.',true)}}

  function rowsFor(p,bucket){return state.tasks.filter(t=>!t.archived&&t.owner_id===p.id&&norm(t.due_state)===bucket)}
  function tableHtml(title,rows){if(!rows.length)return'';return`<h4>${title}</h4><table><thead><tr><th>شناسه</th><th>عنوان کار</th><th>وضعیت</th><th>تاریخ پایان</th></tr></thead><tbody>${rows.map(t=>`<tr><td>#${fa(displayId(t))}</td><td>${esc(t.title)}</td><td>${esc(t.status)}</td><td>${jalaliText(t.due_date)}</td></tr>`).join('')}</tbody></table>`}
  function emailHtml(p){const w=rowsFor(p,'دوره هشدار'),o=rowsFor(p,'دیرکرد'),key=stickerState(p),tpl=templates.find(t=>t.template_key===key)?.body_html||`[عنوان مخاطب]<br><br>با درود و مهر<br>تعداد امور دیرکردی: [تعداد دیرکرد]<br>تعداد امور در دوره هشدار: [تعداد هشدار]<br><br>[جدول امور دیرکردی][جدول امور هشداری]`;return tpl.replaceAll('[عنوان مخاطب]',esc(p.salutation||p.full_name)).replaceAll('[تعداد هشدار]',fa(w.length)).replaceAll('[تعداد دیرکرد]',fa(o.length)).replaceAll('[جدول امور هشداری]',tableHtml('امور در دوره هشدار',w)).replaceAll('[جدول امور دیرکردی]',tableHtml('امور دارای دیرکرد',o)).replaceAll('[تاریخ گزارش]',jalaliText(new Date())).replaceAll('[استیکر]','')}
  function previewSelected(){const id=document.querySelector('.send-pick:checked')?.dataset.id;if(!id)return toast('حداقل یک نفر را انتخاب کنید.',true);const p=people.find(x=>x.id===id);document.querySelector('#previewRecipient').textContent=`${p.full_name} | ${p.email}`;document.querySelector('#emailPreviewBody').innerHTML=emailHtml(p);document.querySelector('#emailPreviewDialog').showModal()}

  async function bridge(path,payload){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),path==='/health'?5000:180000);try{const get=path==='/health',r=await fetch(BRIDGE_URL+path,{method:get?'GET':'POST',headers:{'Content-Type':'application/json'},body:get?undefined:JSON.stringify(payload||{}),signal:controller.signal}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.error||'رابط Outlook پاسخ نداد.');return d}catch(e){if(e.name==='AbortError')throw new Error('زمان انتظار رابط Outlook تمام شد.');throw e}finally{clearTimeout(timer)}}
  async function loadSettings(){const rows=await safeSelect('app_settings','select=*');settings=Object.fromEntries(rows.map(x=>[x.key,x.value]));const val=k=>typeof settings[k]==='string'?settings[k]:(settings[k]?.value||'');document.querySelector('#sendDelay').value=val('send_delay_seconds')||2;document.querySelector('#subjectPrefix').value=val('subject_prefix')||'گزارش روزانه وضعیت امور';await updateMailState()}
  async function updateMailState(){let connected=false;try{await bridge('/health');connected=true}catch{}const e=document.querySelector('#mailState');if(e){e.textContent=connected?'Outlook آماده است':'رابط Outlook در دسترس نیست';e.className='connection-state '+(connected?'ok':'bad')}const n=document.querySelector('#mailConnectionNotice');if(n)n.textContent=connected?'Outlook آماده ارسال است.':'ابتدا Outlook و فایل Start_Outlook_Bridge.bat را روی رایانه اجرا کنید.';return connected}
  async function saveSettings(){const pairs={send_delay_seconds:document.querySelector('#sendDelay').value,subject_prefix:document.querySelector('#subjectPrefix').value.trim()};try{for(const [key,value] of Object.entries(pairs)){const exists=await safeSelect('app_settings',`key=eq.${encodeURIComponent(key)}&select=key`);if(exists.length)await update('app_settings',`key=eq.${encodeURIComponent(key)}`,{value:{value}});else await insert('app_settings',{key,value:{value}})}toast('تنظیمات ایمیل ذخیره شد.');await loadSettings()}catch(e){toast(e.message,true)}}
  async function edge(name,body={}){const r=await fetch(`${SB_URL}/functions/v1/${name}`,{method:'POST',headers:{apikey:SB_KEY,Authorization:`Bearer ${state.token}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'عملیات سمت سرور انجام نشد.');return d}
  async function connectMicrosoft(){const ok=await updateMailState();toast(ok?'اتصال Outlook برقرار است.':'Outlook یا رابط ویندوز اجرا نشده است.',!ok)}
  function captureMicrosoftToken(){if(new URLSearchParams(location.search).get('graph')==='connected'){history.replaceState(null,'',location.pathname);toast('اتصال Microsoft 365 برقرار شد.')}}
  async function sendSelected(){const ids=[...document.querySelectorAll('.send-pick:checked')].map(x=>x.dataset.id);if(!ids.length)return toast('حداقل یک نفر را انتخاب کنید.',true);if(!await updateMailState())throw new Error('ابتدا Outlook و رابط ویندوز را اجرا کنید.');const dispatch=(await insert('email_dispatches',{kind:'daily',provider:'bridge',status:'processing',idempotency_key:crypto.randomUUID(),created_by:state.profile.id}))[0];let sent=0;const failures=[];for(const id of ids){const p=people.find(x=>x.id===id);if(!p||!p.email)continue;const key=stickerState(p),subject=`${document.querySelector('#subjectPrefix').value.trim()||'گزارش روزانه وضعیت امور'} | ${jalaliText(new Date())}`;try{await bridge('/mail/send',{to:p.email,cc:Array.isArray(p.cc_emails)?p.cc_emails:[],subject,html:emailHtml(p),state_key:key,gender:p.gender||'خانم'});await insert('email_logs',{dispatch_id:dispatch.id,recipient_id:p.id,recipient_email:p.email,cc_emails:Array.isArray(p.cc_emails)?p.cc_emails:[],subject,mail_type:'daily',status:'sent',created_by:state.profile.id});sent++}catch(e){failures.push(`${p.full_name}: ${e.message}`);await insert('email_logs',{dispatch_id:dispatch.id,recipient_id:p.id,recipient_email:p.email,cc_emails:Array.isArray(p.cc_emails)?p.cc_emails:[],subject,mail_type:'daily',status:'failed',created_by:state.profile.id,error_message:e.message}).catch(()=>{})}const delay=Math.max(0,Number(document.querySelector('#sendDelay').value)||0);if(delay&&sent<ids.length)await new Promise(r=>setTimeout(r,delay*1000))}await update('email_dispatches',`id=eq.${dispatch.id}`,{status:failures.length?'partial':'completed',completed_at:new Date().toISOString(),error_message:failures.join('\n')||null});if(failures.length)throw new Error(`${fa(sent)} ایمیل ارسال شد؛ ${fa(failures.length)} مورد خطا داشت.`);toast(`${fa(sent)} ایمیل با Outlook ارسال شد.`)}

  async function loadFollowup(){const logs=await safeSelect('email_logs','select=*&order=sent_at.desc&limit=200');const body=document.querySelector('#followBody');body.innerHTML=logs.length?logs.map(l=>{const p=people.find(x=>x.id===l.recipient_id);return`<tr><td><input type="checkbox" class="follow-pick" data-id="${l.id}"></td><td>${esc(p?.full_name||'—')}</td><td class="english">${esc(l.recipient_email)}</td><td>${esc(l.subject)}</td><td>${jalaliDateTime(l.sent_at)}</td><td>${l.replied_at?'پاسخ داده':'بدون پاسخ'}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty">سابقه‌ای ثبت نشده است.</td></tr>'}
  function renderBridgeFollowup(){const body=document.querySelector('#followBody');body.innerHTML=followRows.length?followRows.map((r,i)=>`<tr><td><input type="checkbox" class="follow-pick" data-index="${i}" ${r.found&&!r.responded?'checked':''}></td><td>${esc(r.person?.full_name||r.person?.name||'—')}</td><td class="english">${esc(r.person?.email||'—')}</td><td>${esc(r.subject||'—')}</td><td>${esc(r.sent_display||'—')}</td><td>${r.responded?'پاسخ داده':'بدون پاسخ'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">ایمیلی در این بازه پیدا نشد.</td></tr>'}
  async function checkReplies(){const from=document.querySelector('#followFrom').value.trim(),to=document.querySelector('#followTo').value.trim();if(!from||!to)throw new Error('ابتدا تاریخ شروع و پایان را وارد کنید.');toast('بررسی Outlook آغاز شد.');const d=await bridge('/followups/inspect',{people:people.filter(p=>p.active!==false),date_from:from,date_to:to});followRows=d.rows||[];renderBridgeFollowup();toast('بررسی پاسخ‌ها انجام شد.')}
  async function sendFollowups(){const rows=[...document.querySelectorAll('.follow-pick:checked')].map(x=>followRows[Number(x.dataset.index)]).filter(Boolean);if(!rows.length)throw new Error('حداقل یک مورد بدون پاسخ را انتخاب کنید.');const row=templates.find(t=>t.template_key==='followup');const template={subject:'یادآوری | [موضوع آخرین ایمیل]',body:(row?.body_html||'با درود و مهر\n\nخواهشمند است نتیجه بررسی را در پاسخ به همین ایمیل اعلام فرمایید.').replace(/<br\s*\/?>/gi,'\n')};const d=await bridge('/followups/run',{rows,template,automatic:true});if(d.failures?.length)throw new Error(`${fa(d.sent||0)} یادآوری ارسال شد؛ ${fa(d.failures.length)} مورد خطا داشت.`);toast(`${fa(d.sent||rows.length)} یادآوری ارسال شد.`)}

  async function loadStickers(){const grid=document.querySelector('#stickerGrid');const states=['state1','state2','state3','state4','state5'];grid.innerHTML=states.map(s=>`<div class="sticker-cell"><b>${stateMeta[s]}</b><small>خانم</small><img id="${s}_female_img" alt=""><input type="file" accept="image/*" data-sticker="${s}_female"><small>آقا</small><img id="${s}_male_img" alt=""><input type="file" accept="image/*" data-sticker="${s}_male"></div>`).join('');document.querySelectorAll('[data-sticker]').forEach(i=>i.addEventListener('change',uploadSticker));for(const s of states)for(const g of ['female','male']){const url=`${SB_URL}/storage/v1/object/public/stickers/${s}_${g}.png`;document.querySelector(`#${s}_${g}_img`).src=url+'?v='+Date.now()}}
  async function uploadSticker(e){const f=e.target.files?.[0];if(!f)return;const name=e.target.dataset.sticker+'.png';try{const r=await fetch(`${SB_URL}/storage/v1/object/stickers/${name}`,{method:'POST',headers:{apikey:SB_KEY,Authorization:`Bearer ${state.token}`,'x-upsert':'true','Content-Type':f.type||'image/png'},body:f});if(!r.ok)throw new Error(await r.text());toast('استیکر ذخیره شد.');await loadStickers()}catch(err){toast('آپلود استیکر انجام نشد؛ supabase_phase4.sql را اجرا کنید.',true)}}

  let avatarObjectUrl='';
  window.refreshProfileAvatar=async function(){const el=document.querySelector('#avatar');if(!el||!state.profile)return;if(avatarObjectUrl){URL.revokeObjectURL(avatarObjectUrl);avatarObjectUrl=''}el.classList.remove('has-image');el.style.backgroundImage='';el.textContent=(state.profile.display_name||state.profile.full_name||'ب').trim()[0];if(!state.profile.avatar_path)return;try{const path=state.profile.avatar_path.split('/').map(encodeURIComponent).join('/'),r=await fetch(`${SB_URL}/storage/v1/object/authenticated/avatars/${path}?v=${Date.now()}`,{headers:{apikey:SB_KEY,Authorization:`Bearer ${state.token}`}});if(!r.ok)throw new Error();avatarObjectUrl=URL.createObjectURL(await r.blob());el.style.backgroundImage=`url("${avatarObjectUrl}")`;el.classList.add('has-image')}catch{toast('تصویر پروفایل ذخیره شده اما نمایش آن ممکن نشد.',true)}};

  async function loadManagerView(view){document.querySelector('#viewTitle').textContent=managerTitles[view]||document.querySelector('#viewTitle').textContent;if(view==='settings'){document.querySelector('#profileDisplayName').value=state.profile.display_name||state.profile.full_name||'';document.querySelector('#profileEmail').value=state.profile.email||'';await window.refreshProfileAvatar();if(ensureManager())await loadSettings();return}if(!ensureManager())return;if(view==='people'||view==='send')await loadPeople();if(view==='templates')await loadTemplates();if(view==='stickers')await loadStickers();if(view==='followup'){if(!people.length)await loadPeople();await loadFollowup()}}

  document.addEventListener('DOMContentLoaded',()=>{
    captureMicrosoftToken();
    document.querySelectorAll('#nav button.manager-only,#nav button[data-view="settings"]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>loadManagerView(b.dataset.view),0)));
    document.querySelector('#peopleSearch')?.addEventListener('input',renderPeople);
    document.querySelector('#peopleBody')?.addEventListener('click',e=>{const b=e.target.closest('[data-edit-person]');if(!b)return;editingPerson=people.find(p=>p.id===b.dataset.editPerson);const f=document.querySelector('#personForm');for(const k of ['id','full_name','gender','email','salutation','active'])if(f.elements[k])f.elements[k].value=String(editingPerson?.[k]??'');f.elements.cc_emails.value=Array.isArray(editingPerson.cc_emails)?editingPerson.cc_emails.join('; '):(editingPerson.cc_emails||'');document.querySelector('#personDialogTitle').textContent='ویرایش فرد';document.querySelector('#personDialog').showModal()});
    document.querySelector('#addPersonBtn')?.addEventListener('click',()=>{editingPerson=null;const f=document.querySelector('#personForm');f.reset();f.elements.active.value='true';document.querySelector('#personDialogTitle').textContent='افزودن فرد';document.querySelector('#personDialog').showModal()});
    document.querySelector('#personForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.active=d.active==='true';d.cc_emails=d.cc_emails.split(';').map(x=>x.trim()).filter(Boolean);try{if(editingPerson){delete d.initial_password;const {id,...payload}=d;await update('profiles',`id=eq.${editingPerson.id}`,payload)}else{if(!d.initial_password)throw new Error('رمز اولیه الزامی است.');await edge('admin-users',d)}document.querySelector('#personDialog').close();toast('مشخصات فرد ذخیره شد.');await loadPeople()}catch(err){toast(err.message,true)}});
    document.querySelector('#sendBody')?.addEventListener('change',updatePicked);
    document.querySelector('#selectAllSend')?.addEventListener('click',()=>{const xs=[...document.querySelectorAll('.send-pick')],all=xs.every(x=>x.checked);xs.forEach(x=>x.checked=!all);updatePicked()});
    document.querySelector('#previewSelected')?.addEventListener('click',previewSelected);
    document.querySelector('#sendSelected')?.addEventListener('click',()=>sendSelected().catch(e=>toast(e.message,true)));
    document.querySelector('#templateState')?.addEventListener('change',showTemplate);document.querySelector('#saveTemplateBtn')?.addEventListener('click',saveTemplate);
    document.querySelector('#refreshStickers')?.addEventListener('click',loadStickers);
    document.querySelector('#saveMailSettings')?.addEventListener('click',saveSettings);document.querySelector('#connectMicrosoft')?.addEventListener('click',connectMicrosoft);
    document.querySelector('#checkRepliesBtn')?.addEventListener('click',()=>checkReplies().catch(e=>toast(e.message,true)));document.querySelector('#sendFollowupBtn')?.addEventListener('click',()=>sendFollowups().catch(e=>toast(e.message,true)));
    document.querySelector('#changePasswordBtn')?.addEventListener('click',()=>{document.querySelector('#cancelPasswordBtn').classList.remove('hidden');document.querySelector('#passwordError').textContent='';document.querySelector('#passwordForm').reset();document.querySelector('#passwordDialog').showModal()});
    document.querySelector('#saveProfileBtn')?.addEventListener('click',async()=>{try{const display_name=document.querySelector('#profileDisplayName').value.trim(),file=document.querySelector('#profileAvatar').files?.[0];let avatar_path=state.profile.avatar_path||null;if(file){if(file.size>2097152)throw new Error('حجم تصویر باید کمتر از ۲ مگابایت باشد.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('فرمت تصویر باید PNG، JPG یا WebP باشد.');avatar_path=`${state.profile.id}/avatar.${file.type==='image/jpeg'?'jpg':file.type.split('/')[1]}`;const path=avatar_path.split('/').map(encodeURIComponent).join('/'),r=await fetch(`${SB_URL}/storage/v1/object/avatars/${path}`,{method:'POST',headers:{apikey:SB_KEY,Authorization:`Bearer ${state.token}`,'x-upsert':'true','Content-Type':file.type,'cache-control':'3600'},body:file});if(!r.ok){const detail=await r.json().catch(()=>({}));throw new Error(detail.message||detail.error||'آپلود تصویر انجام نشد.')}}await update('profiles',`id=eq.${state.profile.id}`,{display_name,avatar_path,updated_at:new Date().toISOString()});state.profile.display_name=display_name;state.profile.avatar_path=avatar_path;document.querySelector('#userName').textContent=display_name||state.profile.full_name;document.querySelector('#profileAvatar').value='';await window.refreshProfileAvatar();toast('نام و تصویر پروفایل ذخیره شد.')}catch(e){toast(e.message,true)}});
    updateMailState();
  });
})();
