(()=>{
  const nav=document.querySelector('#nav');
  const workspace=document.querySelector('.workspace');
  if(!nav||!workspace)return;

  const navHtml=`
    <div class="nav-divider manager-only"></div>
    <button data-view="people" class="manager-only"><b>♙</b><span>افراد و رونوشت‌ها</span></button>
    <button data-view="send" class="manager-only"><b>✉</b><span>انتخاب و ارسال</span></button>
    <button data-view="templates" class="manager-only"><b>≡</b><span>متن ایمیل‌ها</span></button>
    <button data-view="stickers" class="manager-only"><b>◇</b><span>مدیریت استیکرها</span></button>
    <button data-view="followup" class="manager-only"><b>↻</b><span>پیگیری پاسخ‌ها</span></button>
    <button data-view="mailsettings" class="manager-only"><b>⚙</b><span>تنظیمات ایمیل</span></button>`;
  nav.insertAdjacentHTML('beforeend',navHtml);

  const views=`
  <section id="peopleView" class="view hidden manager-only"><div class="panel table-panel"><div class="panel-head"><div><h3>افراد و رونوشت‌ها</h3><small>مدیریت گیرندگان ایمیل و رونوشت‌ها</small></div><div class="manager-toolbar"><input id="peopleSearch" class="search" placeholder="جست‌وجو…"><button id="addPersonBtn" class="primary">＋ افزودن فرد</button></div></div><div class="table-wrap"><table class="manager-table"><thead><tr><th>فعال</th><th>نام</th><th>جنسیت</th><th>ایمیل</th><th>عنوان ایمیل</th><th>رونوشت</th><th></th></tr></thead><tbody id="peopleBody"></tbody></table></div></div></section>

  <section id="sendView" class="view hidden manager-only"><div class="panel"><div class="panel-head"><div><h3>انتخاب و ارسال</h3><small>ارسال گزارش روزانه و یادآوری برای افراد انتخاب‌شده</small></div><div class="manager-toolbar"><button id="selectAllSend" class="ghost">انتخاب همه</button><button id="previewSelected" class="ghost">پیش‌نمایش</button><button id="sendSelected" class="primary">ارسال مستقیم</button></div></div><div class="send-summary"><article><small>افراد</small><strong id="sendPeopleCount">۰</strong></article><article><small>هشدار</small><strong id="sendWarningCount">۰</strong></article><article><small>دیرکرد</small><strong id="sendOverdueCount">۰</strong></article><article><small>انتخاب‌شده</small><strong id="sendPickedCount">۰</strong></article></div><div class="manager-warning" id="mailConnectionNotice">برای ارسال مستقیم، اتصال Microsoft 365 باید در «تنظیمات ایمیل» فعال باشد. پیش‌نمایش بدون اتصال قابل استفاده است.</div><div class="table-wrap"><table class="manager-table"><thead><tr><th>انتخاب</th><th>نام</th><th>ایمیل</th><th>وضعیت</th><th>هشدار</th><th>دیرکرد</th><th>استیکر</th></tr></thead><tbody id="sendBody"></tbody></table></div></div></section>

  <section id="templatesView" class="view hidden manager-only"><div class="panel"><div class="panel-head"><div><h3>متن ایمیل‌ها</h3><small>متن گزارش بر اساس وضعیت گیرنده</small></div><div class="manager-toolbar"><select id="templateState"><option value="state1">وضعیت مطلوب</option><option value="state2">یادآوری</option><option value="state3">نیازمند توجه</option><option value="state4">پیگیری جدی</option><option value="state5">اقدام فوری</option><option value="followup">یادآوری مجدد</option></select><button id="saveTemplateBtn" class="primary">ذخیره متن</button></div></div><div class="manager-note">متغیرهای قابل استفاده: [عنوان مخاطب]، [تعداد هشدار]، [تعداد دیرکرد]، [جدول امور هشداری]، [جدول امور دیرکردی]، [استیکر]، [تاریخ گزارش]</div><textarea id="templateBody" class="template-editor"></textarea></div></section>

  <section id="stickersView" class="view hidden manager-only"><div class="panel"><div class="panel-head"><div><h3>مدیریت استیکرها</h3><small>نسخه‌های زن و مرد برای پنج وضعیت</small></div><button id="refreshStickers" class="ghost">به‌روزرسانی</button></div><div id="stickerGrid" class="sticker-grid"></div></div></section>

  <section id="followupView" class="view hidden manager-only"><div class="panel"><div class="panel-head"><div><h3>پیگیری پاسخ‌ها</h3><small>بررسی ایمیل‌های ارسال‌شده و پاسخ‌های دریافت‌شده</small></div><div class="manager-toolbar"><button id="checkRepliesBtn" class="ghost">بررسی ایمیل‌ها و پاسخ‌ها</button><button id="sendFollowupBtn" class="primary">ارسال یادآوری</button></div></div><div class="follow-date-row"><label>از تاریخ شمسی<input id="followFrom" class="compact-input" placeholder="۱۴۰۵/۰۱/۰۱"></label><label>تا تاریخ شمسی<input id="followTo" class="compact-input" placeholder="۱۴۰۵/۱۲/۲۹"></label></div><div class="manager-warning">بررسی پاسخ و ارسال Reply از طریق Microsoft Graph انجام می‌شود؛ تا قبل از فعال‌سازی اتصال، این بخش فقط سابقه ثبت‌شده در سامانه را نشان می‌دهد.</div><div class="table-wrap"><table class="manager-table"><thead><tr><th>انتخاب</th><th>نام</th><th>ایمیل</th><th>موضوع</th><th>زمان ارسال</th><th>پاسخ</th></tr></thead><tbody id="followBody"></tbody></table></div></div></section>

  <section id="mailsettingsView" class="view hidden manager-only"><div class="panel"><div class="panel-head"><div><h3>تنظیمات ایمیل</h3><small>اتصال امن وب‌اپ به Microsoft 365 / Outlook</small></div><span id="mailState" class="connection-state bad">اتصال فعال نیست</span></div><div class="manager-form"><label>Tenant ID<input id="tenantId" class="english" dir="ltr"></label><label>Client ID<input id="clientId" class="english" dir="ltr"></label><label class="wide-field">Redirect URI<input id="redirectUri" class="english" dir="ltr"></label><label>تأخیر بین ارسال‌ها (ثانیه)<input id="sendDelay" type="number" min="0" value="2"></label><label>پسوند موضوع<input id="subjectPrefix" value="گزارش روزانه وضعیت امور"></label></div><div class="modal-actions"><button id="saveMailSettings" class="ghost">ذخیره تنظیمات</button><button id="connectMicrosoft" class="primary">اتصال به Microsoft 365</button></div></div></section>

  <dialog id="personDialog" class="modal manager-modal"><form id="personForm" method="dialog"><div class="modal-head"><div><h3 id="personDialogTitle">افزودن فرد</h3><p>اطلاعات گیرنده و رونوشت</p></div><button type="button" onclick="this.closest('dialog').close()">×</button></div><input name="id" type="hidden"><div class="manager-form"><label>نام کامل<input name="full_name" required></label><label>جنسیت<select name="gender"><option>آقا</option><option>خانم</option></select></label><label>ایمیل<input name="email" class="english" dir="ltr" type="email" required></label><label>عنوان ایمیل<input name="salutation"></label><label class="wide-field">رونوشت‌ها (با ; جدا کنید)<input name="cc_emails" class="english" dir="ltr"></label><label>فعال<select name="active"><option value="true">بله</option><option value="false">خیر</option></select></label></div><div class="modal-actions"><button type="button" class="ghost" onclick="this.closest('dialog').close()">انصراف</button><button type="submit" class="primary">ذخیره</button></div></form></dialog>

  <dialog id="emailPreviewDialog" class="modal manager-modal"><div class="modal-head"><div><h3>پیش‌نمایش ایمیل</h3><p id="previewRecipient"></p></div><button type="button" onclick="this.closest('dialog').close()">×</button></div><div id="emailPreviewBody" class="preview-email"></div></dialog>`;
  workspace.insertAdjacentHTML('beforeend',views);

  const managerTitles={people:'افراد و رونوشت‌ها',send:'انتخاب و ارسال',templates:'متن ایمیل‌ها',stickers:'مدیریت استیکرها',followup:'پیگیری پاسخ‌ها',mailsettings:'تنظیمات ایمیل'};
  const stateMeta={state1:'وضعیت مطلوب',state2:'یادآوری',state3:'نیازمند توجه',state4:'پیگیری جدی',state5:'اقدام فوری'};
  let people=[],templates=[],settings={},editingPerson=null;
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const countByOwner=(ownerId,bucket)=>state.tasks.filter(t=>!t.archived&&t.owner_id===ownerId&&norm(t.due_state)===bucket).length;
  const stickerState=p=>{const o=countByOwner(p.id,'دیرکرد'),w=countByOwner(p.id,'دوره هشدار');if(o>=5)return'state5';if(o>=3)return'state4';if(o>=1)return'state3';if(w>0)return'state2';return'state1'};
  const ensureManager=()=>document.querySelector('#userRole')?.textContent==='مدیر سامانه';
  async function safeSelect(table,q='select=*'){try{return await select(table,q)}catch(e){console.warn(e);return[]}}

  async function loadPeople(){
    people=await safeSelect('profiles','select=*&order=full_name');
    if(!people.length)people=state.profiles||[];
    renderPeople();renderSend();
  }
  function renderPeople(){const q=(document.querySelector('#peopleSearch')?.value||'').trim().toLowerCase();const rows=people.filter(p=>!q||[p.full_name,p.email,p.salutation,(p.cc_emails||[]).join?.(';')].some(x=>String(x||'').toLowerCase().includes(q)));document.querySelector('#peopleBody').innerHTML=rows.map(p=>`<tr><td>${p.active!==false?'✓':'—'}</td><td>${esc(p.full_name)}</td><td>${esc(p.gender||'—')}</td><td class="english">${esc(p.email)}</td><td>${esc(p.salutation||'—')}</td><td class="english">${esc(Array.isArray(p.cc_emails)?p.cc_emails.join('; '):(p.cc_emails||'—'))}</td><td><button class="icon-btn" data-edit-person="${p.id}">ویرایش</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">اطلاعات افراد هنوز بارگذاری نشده است.</td></tr>';}
  function renderSend(){if(!document.querySelector('#sendBody'))return;const owners=people.filter(p=>p.active!==false&&p.role!=='manager'||p.active!==false);document.querySelector('#sendBody').innerHTML=owners.map(p=>{const w=countByOwner(p.id,'دوره هشدار'),o=countByOwner(p.id,'دیرکرد'),s=stickerState(p);return`<tr><td><input type="checkbox" class="send-pick" data-id="${p.id}"></td><td>${esc(p.full_name)}</td><td class="english">${esc(p.email)}</td><td>${stateMeta[s]}</td><td>${fa(w)}</td><td>${fa(o)}</td><td>${stateMeta[s]}</td></tr>`}).join('');document.querySelector('#sendPeopleCount').textContent=fa(owners.length);document.querySelector('#sendWarningCount').textContent=fa(owners.reduce((a,p)=>a+countByOwner(p.id,'دوره هشدار'),0));document.querySelector('#sendOverdueCount').textContent=fa(owners.reduce((a,p)=>a+countByOwner(p.id,'دیرکرد'),0));updatePicked()}
  function updatePicked(){const n=[...document.querySelectorAll('.send-pick:checked')].length;const e=document.querySelector('#sendPickedCount');if(e)e.textContent=fa(n)}

  async function loadTemplates(){templates=await safeSelect('email_templates','select=*&order=template_key');showTemplate()}
  function showTemplate(){const key=document.querySelector('#templateState')?.value;const row=templates.find(t=>t.template_key===key);if(document.querySelector('#templateBody'))document.querySelector('#templateBody').value=row?.body_html||''}
  async function saveTemplate(){const key=document.querySelector('#templateState').value,body_html=document.querySelector('#templateBody').value;const existing=templates.find(t=>t.template_key===key);try{if(existing)await update('email_templates',`id=eq.${existing.id}`,{body_html});else await insert('email_templates',{template_key:key,body_html});toast('متن ایمیل ذخیره شد.');await loadTemplates()}catch(e){toast('ابتدا فایل supabase_phase4.sql را در Supabase اجرا کنید.',true)}}

  function rowsFor(p,bucket){return state.tasks.filter(t=>!t.archived&&t.owner_id===p.id&&norm(t.due_state)===bucket)}
  function tableHtml(title,rows){if(!rows.length)return'';return`<h4>${title}</h4><table><thead><tr><th>شناسه</th><th>عنوان کار</th><th>وضعیت</th><th>تاریخ پایان</th></tr></thead><tbody>${rows.map(t=>`<tr><td>#${fa(displayId(t))}</td><td>${esc(t.title)}</td><td>${esc(t.status)}</td><td>${jalaliText(t.due_date)}</td></tr>`).join('')}</tbody></table>`}
  function emailHtml(p){const w=rowsFor(p,'دوره هشدار'),o=rowsFor(p,'دیرکرد'),key=stickerState(p),tpl=templates.find(t=>t.template_key===key)?.body_html||`[عنوان مخاطب]<br><br>با درود و مهر<br>تعداد امور دیرکردی: [تعداد دیرکرد]<br>تعداد امور در دوره هشدار: [تعداد هشدار]<br><br>[جدول امور دیرکردی][جدول امور هشداری]`;return tpl.replaceAll('[عنوان مخاطب]',esc(p.salutation||p.full_name)).replaceAll('[تعداد هشدار]',fa(w.length)).replaceAll('[تعداد دیرکرد]',fa(o.length)).replaceAll('[جدول امور هشداری]',tableHtml('امور در دوره هشدار',w)).replaceAll('[جدول امور دیرکردی]',tableHtml('امور دارای دیرکرد',o)).replaceAll('[تاریخ گزارش]',jalaliText(new Date())).replaceAll('[استیکر]','')}
  function previewSelected(){const id=document.querySelector('.send-pick:checked')?.dataset.id;if(!id)return toast('حداقل یک نفر را انتخاب کنید.',true);const p=people.find(x=>x.id===id);document.querySelector('#previewRecipient').textContent=`${p.full_name} | ${p.email}`;document.querySelector('#emailPreviewBody').innerHTML=emailHtml(p);document.querySelector('#emailPreviewDialog').showModal()}

  async function loadSettings(){const rows=await safeSelect('app_settings','select=*');settings=Object.fromEntries(rows.map(x=>[x.key,x.value]));const val=k=>typeof settings[k]==='string'?settings[k]:(settings[k]?.value||'');document.querySelector('#tenantId').value=val('ms_tenant_id');document.querySelector('#clientId').value=val('ms_client_id');document.querySelector('#redirectUri').value=val('ms_redirect_uri')||location.origin+location.pathname;document.querySelector('#sendDelay').value=val('send_delay_seconds')||2;document.querySelector('#subjectPrefix').value=val('subject_prefix')||'گزارش روزانه وضعیت امور';updateMailState()}
  function updateMailState(){const token=sessionStorage.getItem('bamco_ms_token');const e=document.querySelector('#mailState');if(!e)return;e.textContent=token?'Microsoft 365 متصل است':'اتصال فعال نیست';e.className='connection-state '+(token?'ok':'bad');const n=document.querySelector('#mailConnectionNotice');if(n)n.textContent=token?'اتصال Microsoft 365 فعال است؛ ارسال مستقیم قابل استفاده است.':'برای ارسال مستقیم، اتصال Microsoft 365 باید در «تنظیمات ایمیل» فعال باشد. پیش‌نمایش بدون اتصال قابل استفاده است.'}
  async function saveSettings(){const pairs={ms_tenant_id:document.querySelector('#tenantId').value.trim(),ms_client_id:document.querySelector('#clientId').value.trim(),ms_redirect_uri:document.querySelector('#redirectUri').value.trim(),send_delay_seconds:document.querySelector('#sendDelay').value,subject_prefix:document.querySelector('#subjectPrefix').value.trim()};try{for(const [key,value] of Object.entries(pairs)){const exists=await safeSelect('app_settings',`key=eq.${encodeURIComponent(key)}&select=key`);if(exists.length)await update('app_settings',`key=eq.${encodeURIComponent(key)}`,{value:{value}});else await insert('app_settings',{key,value:{value}})}toast('تنظیمات ایمیل ذخیره شد.');await loadSettings()}catch(e){toast('ابتدا supabase_phase4.sql را اجرا کنید.',true)}}
  function connectMicrosoft(){const tenant=document.querySelector('#tenantId').value.trim(),client=document.querySelector('#clientId').value.trim(),redirect=document.querySelector('#redirectUri').value.trim();if(!tenant||!client)return toast('Tenant ID و Client ID را وارد کنید.',true);const stateKey=crypto.randomUUID();sessionStorage.setItem('bamco_ms_state',stateKey);const scope=encodeURIComponent('openid profile offline_access Mail.Read Mail.ReadWrite Mail.Send');location.href=`https://login.microsoftonline.com/${encodeURIComponent(tenant)}/oauth2/v2.0/authorize?client_id=${encodeURIComponent(client)}&response_type=token&redirect_uri=${encodeURIComponent(redirect)}&response_mode=fragment&scope=${scope}&state=${encodeURIComponent(stateKey)}`}
  function captureMicrosoftToken(){const h=new URLSearchParams(location.hash.slice(1)),token=h.get('access_token');if(token&&h.get('state')===sessionStorage.getItem('bamco_ms_state')){sessionStorage.setItem('bamco_ms_token',token);history.replaceState(null,'',location.pathname+location.search);updateMailState();toast('اتصال Microsoft 365 برقرار شد.')}}
  async function graph(path,opt={}){const token=sessionStorage.getItem('bamco_ms_token');if(!token)throw new Error('Microsoft 365 متصل نیست.');const r=await fetch('https://graph.microsoft.com/v1.0'+path,{...opt,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok)throw new Error((await r.json().catch(()=>({})))?.error?.message||'خطا در Microsoft Graph');return r.status===204?null:r.json()}
  async function sendSelected(){const ids=[...document.querySelectorAll('.send-pick:checked')].map(x=>x.dataset.id);if(!ids.length)return toast('حداقل یک نفر را انتخاب کنید.',true);if(!sessionStorage.getItem('bamco_ms_token'))return toast('ابتدا اتصال Microsoft 365 را از تنظیمات ایمیل فعال کنید.',true);const prefix=document.querySelector('#subjectPrefix')?.value||'گزارش روزانه وضعیت امور';for(const id of ids){const p=people.find(x=>x.id===id),cc=(Array.isArray(p.cc_emails)?p.cc_emails:String(p.cc_emails||'').split(';')).filter(Boolean);const message={subject:`${prefix} | ${jalaliText(new Date())}`,body:{contentType:'HTML',content:emailHtml(p)},toRecipients:[{emailAddress:{address:p.email}}],ccRecipients:cc.map(address=>({emailAddress:{address:address.trim()}}))};await graph('/me/sendMail',{method:'POST',body:JSON.stringify({message,saveToSentItems:true})});try{await insert('email_logs',{recipient_id:p.id,recipient_email:p.email,subject:message.subject,mail_type:'daily',sent_at:new Date().toISOString(),status:'sent'})}catch{} }toast(`${fa(ids.length)} ایمیل ارسال شد.`)}

  async function loadFollowup(){const logs=await safeSelect('email_logs','select=*&order=sent_at.desc&limit=200');const body=document.querySelector('#followBody');body.innerHTML=logs.length?logs.map(l=>{const p=people.find(x=>x.id===l.recipient_id);return`<tr><td><input type="checkbox" class="follow-pick" data-id="${l.id}"></td><td>${esc(p?.full_name||'—')}</td><td class="english">${esc(l.recipient_email)}</td><td>${esc(l.subject)}</td><td>${jalaliDateTime(l.sent_at)}</td><td>${l.replied_at?'پاسخ داده':'بدون پاسخ'}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty">سابقه‌ای ثبت نشده است.</td></tr>'}
  async function checkReplies(){if(!sessionStorage.getItem('bamco_ms_token'))return toast('ابتدا Microsoft 365 را متصل کنید.',true);toast('بررسی پاسخ‌ها آغاز شد.');try{const data=await graph('/me/mailFolders/inbox/messages?$top=100&$select=id,subject,receivedDateTime,from,inReplyTo');console.log(data);toast('صندوق ورودی بررسی شد. برای تطبیق کامل Replyها، ثبت Message-ID در ارسال مرحله بعد فعال می‌شود.')}catch(e){toast(e.message,true)}}

  async function loadStickers(){const grid=document.querySelector('#stickerGrid');const states=['state1','state2','state3','state4','state5'];grid.innerHTML=states.map(s=>`<div class="sticker-cell"><b>${stateMeta[s]}</b><small>خانم</small><img id="${s}_female_img" alt=""><input type="file" accept="image/*" data-sticker="${s}_female"><small>آقا</small><img id="${s}_male_img" alt=""><input type="file" accept="image/*" data-sticker="${s}_male"></div>`).join('');document.querySelectorAll('[data-sticker]').forEach(i=>i.addEventListener('change',uploadSticker));for(const s of states)for(const g of ['female','male']){const url=`${SB_URL}/storage/v1/object/public/stickers/${s}_${g}.png`;document.querySelector(`#${s}_${g}_img`).src=url+'?v='+Date.now()}}
  async function uploadSticker(e){const f=e.target.files?.[0];if(!f)return;const name=e.target.dataset.sticker+'.png';try{const r=await fetch(`${SB_URL}/storage/v1/object/stickers/${name}`,{method:'POST',headers:{apikey:SB_KEY,Authorization:`Bearer ${state.token}`,'x-upsert':'true','Content-Type':f.type||'image/png'},body:f});if(!r.ok)throw new Error(await r.text());toast('استیکر ذخیره شد.');await loadStickers()}catch(err){toast('آپلود استیکر انجام نشد؛ supabase_phase4.sql را اجرا کنید.',true)}}

  async function loadManagerView(view){if(!ensureManager())return;document.querySelector('#viewTitle').textContent=managerTitles[view]||document.querySelector('#viewTitle').textContent;if(view==='people'||view==='send')await loadPeople();if(view==='templates')await loadTemplates();if(view==='stickers')await loadStickers();if(view==='followup'){if(!people.length)await loadPeople();await loadFollowup()}if(view==='mailsettings')await loadSettings()}

  document.addEventListener('DOMContentLoaded',()=>{
    captureMicrosoftToken();
    document.querySelectorAll('#nav button.manager-only').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>loadManagerView(b.dataset.view),0)));
    document.querySelector('#peopleSearch')?.addEventListener('input',renderPeople);
    document.querySelector('#peopleBody')?.addEventListener('click',e=>{const b=e.target.closest('[data-edit-person]');if(!b)return;editingPerson=people.find(p=>p.id===b.dataset.editPerson);const f=document.querySelector('#personForm');for(const k of ['id','full_name','gender','email','salutation','active'])if(f.elements[k])f.elements[k].value=String(editingPerson?.[k]??'');f.elements.cc_emails.value=Array.isArray(editingPerson.cc_emails)?editingPerson.cc_emails.join('; '):(editingPerson.cc_emails||'');document.querySelector('#personDialogTitle').textContent='ویرایش فرد';document.querySelector('#personDialog').showModal()});
    document.querySelector('#addPersonBtn')?.addEventListener('click',()=>{editingPerson=null;const f=document.querySelector('#personForm');f.reset();f.elements.active.value='true';document.querySelector('#personDialogTitle').textContent='افزودن فرد';document.querySelector('#personDialog').showModal()});
    document.querySelector('#personForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.active=d.active==='true';d.cc_emails=d.cc_emails.split(';').map(x=>x.trim()).filter(Boolean);try{if(editingPerson){const {id,...payload}=d;await update('profiles',`id=eq.${editingPerson.id}`,payload)}else{toast('ایجاد حساب جدید باید از بخش Authentication در Supabase انجام شود؛ پس از ایجاد حساب، مشخصات اینجا قابل ویرایش است.',true);return}document.querySelector('#personDialog').close();toast('مشخصات فرد ذخیره شد.');await loadPeople()}catch(err){toast('برای ویرایش مشخصات، supabase_phase4.sql را اجرا کنید.',true)}});
    document.querySelector('#sendBody')?.addEventListener('change',updatePicked);
    document.querySelector('#selectAllSend')?.addEventListener('click',()=>{const xs=[...document.querySelectorAll('.send-pick')],all=xs.every(x=>x.checked);xs.forEach(x=>x.checked=!all);updatePicked()});
    document.querySelector('#previewSelected')?.addEventListener('click',previewSelected);
    document.querySelector('#sendSelected')?.addEventListener('click',()=>sendSelected().catch(e=>toast(e.message,true)));
    document.querySelector('#templateState')?.addEventListener('change',showTemplate);document.querySelector('#saveTemplateBtn')?.addEventListener('click',saveTemplate);
    document.querySelector('#refreshStickers')?.addEventListener('click',loadStickers);
    document.querySelector('#saveMailSettings')?.addEventListener('click',saveSettings);document.querySelector('#connectMicrosoft')?.addEventListener('click',connectMicrosoft);
    document.querySelector('#checkRepliesBtn')?.addEventListener('click',checkReplies);document.querySelector('#sendFollowupBtn')?.addEventListener('click',()=>toast('پس از تکمیل تطبیق Replyها با Message-ID، یادآوری به همان زنجیره ایمیل ارسال می‌شود.',true));
    updateMailState();
  });
})();