const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
function edge(name,db,extra={}){let handler;const source=stripTypeScriptTypes(fs.readFileSync(`supabase/functions/${name}/index.ts`,'utf8').replace(/^import .*;\n/gm,''));vm.runInNewContext(source,{Deno:{env:{get:()=> 'test'},serve:f=>handler=f},createClient:()=>db,Request,Response,FormData,File,URL,crypto,Uint8Array,TextDecoder,...extra});return handler}
function lettersDB({user=true,active=true,version=2,conflict=false}={}){const calls=[];const db={auth:{getUser:async()=>({data:{user:user?{id:'owner'}:null},error:!user})},storage:{from:()=>({upload:async(path)=>{calls.push(['upload',path]);return{}},remove:async(paths)=>{calls.push(['remove',paths]);return{}},createSignedUrl:async()=>({data:{signedUrl:'https://example.test/file'}})})},from:table=>{let write=false,patch;const b={select:()=>b,eq:()=>b,update:p=>{write=true;patch=p;return b},insert:p=>{write=true;patch=p;return b},single:async()=>table==='profiles'?{data:{active,role:'owner'}}:write?(conflict?{error:{code:'PGRST116'}}:{data:patch}):{data:{id:'letter',version,storage_path:'old.pdf',file_name:'old.pdf'}}};return b}};return{db,calls}}
function saveRequest(version=2,file=null){const f=new FormData();Object.entries({action:'save',id:'letter',version:String(version),letter_number:'1405/10/30/1',letter_date:'1405/01/01',recipient:'گیرنده',subject:'موضوع'}).forEach(([k,v])=>f.set(k,v));if(file)f.set('file',file);return new Request('https://test',{method:'POST',body:f,headers:{authorization:'Bearer test'}})}
test('letter edge rejects missing authentication and inactive accounts',async()=>{for(const [options,status] of [[{user:false},401],[{active:false},403]]){const {db}=lettersDB(options);const r=await edge('letters-library',db)(saveRequest());assert.equal(r.status,status)}});
test('letter edge lets owner edit metadata and rejects stale versions before upload',async()=>{const {db,calls}=lettersDB();const handler=edge('letters-library',db);const good=await handler(saveRequest());assert.equal(good.status,200);assert.equal((await good.json()).letter.version,3);assert.equal((await handler(saveRequest(1))).status,409);assert.equal(calls.length,0)});
test('failed concurrent letter update removes only newly uploaded object',async()=>{const {db,calls}=lettersDB({conflict:true});const r=await edge('letters-library',db)(saveRequest(2,new File(['%PDF-1.7\n'], 'letter.pdf',{type:'application/pdf'})));assert.equal(r.status,409);assert.equal(calls[0][0],'upload');assert.equal(calls[1][1][0],calls[0][1]);assert.notEqual(calls[1][1][0],'old.pdf')});
test('fake PDF payload is rejected before Storage upload',async()=>{const {db,calls}=lettersDB();const r=await edge('letters-library',db)(saveRequest(2,new File(['<html>'], 'letter.pdf',{type:'application/pdf'})));assert.equal(r.status,400);assert.equal(calls.length,0)});
function pushDB(){const calls=[];const db={auth:{getUser:async()=>({data:{user:{id:'owner'}}})},from:()=>({select(){return this},eq(){return this},single:async()=>({data:{active:true}})}),rpc:async(_,args)=>{calls.push(args);return{data:args.p_action==='config'?{public_key:'public',private_key:'private',worker_key:'worker'}:args.p_action==='claim'?[{id:1,notification_id:2,subscription_id:'sub',subscription:{endpoint:'https://fcm.googleapis.com/test'},title:'اعلان'}]:{}}}};return{db,calls}}
test('push rejects unauthorized worker and SSRF subscription destinations',async()=>{const {db}=pushDB();const h=edge('web-push',db,{webpush:{}});const req=body=>new Request('https://test',{method:'POST',body:JSON.stringify(body)});assert.equal((await h(req({action:'deliver'}))).status,401);assert.equal((await h(req({action:'subscribe',subscription:{endpoint:'https://127.0.0.1/private',keys:{}}}))).status,400)});
test('expired push endpoint is retired and never marked accepted',async()=>{const {db,calls}=pushDB();const h=edge('web-push',db,{webpush:{setVapidDetails(){},sendNotification:async()=>{throw{statusCode:410}}}});const r=await h(new Request('https://test',{method:'POST',headers:{'x-push-worker-key':'worker'},body:JSON.stringify({action:'deliver'})}));assert.deepEqual(await r.json(),{accepted:0,failed:1});const finish=calls.find(x=>x.p_action==='finish').p_data;assert.equal(finish.ok,false);assert.equal(finish.expired,true)});
