-- BAMCO platform foundation: organization source-of-truth, dynamic approvals,
-- projects, parts, staged financial obligations, scope and audit.
-- The legacy approval_chain tables remain read-only historical storage. New
-- requests and migrated active requests use organization_workflows exclusively.

create extension if not exists pgcrypto;

create table if not exists public.organization_roles(
  id bigint generated by default as identity primary key,
  role_key text not null unique,
  title text not null,
  level_no integer not null default 0 check(level_no>=0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.organization_roles(role_key,title,level_no) values
 ('expert','کارشناس',10),('supervisor','سرپرست',20),('head','رئیس',30),
 ('manager','مدیر',40),('deputy','معاون',50),('office_manager','مسئول دفتر',60)
on conflict(role_key) do update set title=excluded.title,level_no=excluded.level_no;

create table if not exists public.permission_catalog(
  permission_key text primary key,
  title text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.permission_catalog(permission_key,title) values
 ('project.create','ایجاد پروژه'),('project.view','مشاهده پروژه'),('project.progress_override','ثبت Override پیشرفت پروژه'),
 ('project.edit','ویرایش پروژه'),('project.delete','حذف پروژه'),
 ('project.assign','تخصیص پروژه'),('project.view_subordinates','مشاهده پروژه‌های زیرمجموعه'),
 ('part.create','ایجاد قطعه'),('part.view','مشاهده قطعه'),('part.edit','ویرایش قطعه'),
 ('invoice.create','ایجاد صورتحساب'),('invoice.view','مشاهده صورتحساب'),
 ('invoice.approve','تأیید صورتحساب'),('invoice.record_payment','ثبت پرداخت'),
 ('organization.manage','مدیریت ساختار سازمانی'),('request.approve','تأیید درخواست')
on conflict(permission_key) do update set title=excluded.title;

create table if not exists public.organization_role_permissions(
  role_id bigint not null references public.organization_roles(id) on delete cascade,
  permission_key text not null references public.permission_catalog(permission_key) on delete cascade,
  allowed boolean not null default true,
  primary key(role_id,permission_key)
);

insert into public.organization_role_permissions(role_id,permission_key)
select r.id,p.permission_key
from public.organization_roles r cross join public.permission_catalog p
where r.role_key in ('manager','deputy') and p.active
on conflict do nothing;
insert into public.organization_role_permissions(role_id,permission_key)
select r.id,p.permission_key
from public.organization_roles r cross join public.permission_catalog p
where r.role_key in ('expert','supervisor','head','office_manager')
  and p.permission_key in ('project.create','project.view','part.view','invoice.view')
on conflict do nothing;

create table if not exists public.organization_units(
  id bigint generated by default as identity primary key,
  parent_unit_id bigint references public.organization_units(id) on delete restrict,
  code text not null unique,
  title text not null,
  description text,
  active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_positions(
  id bigint generated by default as identity primary key,
  unit_id bigint references public.organization_units(id) on delete set null,
  parent_position_id bigint references public.organization_positions(id) on delete restrict,
  role_id bigint not null references public.organization_roles(id),
  code text not null unique,
  title text not null,
  description text,
  active boolean not null default true,
  valid_from date,
  valid_to date,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(valid_to is null or valid_from is null or valid_to>=valid_from)
);

create table if not exists public.organization_position_assignments(
  id bigint generated by default as identity primary key,
  position_id bigint not null references public.organization_positions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  is_primary boolean not null default true,
  valid_from date not null default current_date,
  valid_to date,
  assigned_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  check(valid_to is null or valid_to>=valid_from)
);
create unique index if not exists organization_primary_position_idx
  on public.organization_position_assignments(position_id)
  where is_primary and valid_to is null;

create table if not exists public.organization_position_acting(
  id bigint generated by default as identity primary key,
  position_id bigint not null references public.organization_positions(id) on delete cascade,
  acting_user_id uuid not null references public.profiles(id) on delete cascade,
  valid_from date not null,
  valid_to date not null,
  granted_by uuid references public.profiles(id) on delete set null,
  reason text,
  check(valid_to>=valid_from)
);

alter table public.profiles add column if not exists primary_position_id bigint;
do $$ begin
  alter table public.profiles add constraint profiles_primary_position_fk
    foreign key(primary_position_id) references public.organization_positions(id) on delete set null;
exception when duplicate_object then null;
end $$;

create table if not exists public.organization_settings(
  singleton boolean primary key default true check(singleton),
  structure_version bigint not null default 1,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);
insert into public.organization_settings(singleton) values(true) on conflict do nothing;

create table if not exists public.audit_trail(
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  old_data jsonb,
  new_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_trail_target_idx on public.audit_trail(target_type,target_id,created_at desc);

create or replace function private.platform_can_manage_org(p_user uuid default auth.uid())
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.profiles p where p.id=p_user and p.active and p.role='manager')
    or exists(
      select 1 from public.organization_position_assignments a
      join public.organization_positions pos on pos.id=a.position_id and pos.active
      join public.organization_roles r on r.id=pos.role_id and r.active
      join public.organization_role_permissions rp on rp.role_id=r.id and rp.permission_key='organization.manage' and rp.allowed
      where a.user_id=p_user and a.is_primary and a.valid_to is null
    );
$$;

create or replace function public.organization_scope_user_ids(p_actor uuid default auth.uid())
returns table(user_id uuid)
language sql stable security definer set search_path='' as $$
  with recursive roots as(
    select a.position_id from public.organization_position_assignments a
    where a.user_id=p_actor and a.is_primary and a.valid_from<=current_date
      and (a.valid_to is null or a.valid_to>=current_date)
  ), tree as(
    select p.id from public.organization_positions p join roots r on r.position_id=p.id
    union all
    select child.id from public.organization_positions child join tree parent on child.parent_position_id=parent.id
    where child.active
  )
  select distinct a.user_id from public.organization_position_assignments a
  join tree t on t.id=a.position_id
  where a.valid_from<=current_date and (a.valid_to is null or a.valid_to>=current_date)
  union select p_actor where p_actor is not null;
$$;

create or replace function public.organization_has_permission(p_permission text,p_target_user uuid default null)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(
    select 1
    from public.organization_position_assignments a
    join public.organization_positions pos on pos.id=a.position_id and pos.active
    join public.organization_roles r on r.id=pos.role_id and r.active
    join public.organization_role_permissions rp on rp.role_id=r.id and rp.permission_key=p_permission and rp.allowed
    where a.user_id=auth.uid() and a.is_primary and a.valid_from<=current_date
      and (a.valid_to is null or a.valid_to>=current_date)
      and (p_target_user is null or p_target_user in (select user_id from public.organization_scope_user_ids(auth.uid())))
  ) or exists(select 1 from public.profiles p where p.id=auth.uid() and p.active and p.role='manager');
$$;

create or replace function private.platform_audit_trigger()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into public.audit_trail(actor_id,action,target_type,target_id,old_data,new_data,metadata)
  values(auth.uid(),lower(tg_op),tg_table_name,coalesce(to_jsonb(old)->>'id',to_jsonb(new)->>'id',''),
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end,'{}'::jsonb);
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

create or replace function private.bump_organization_version()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  update public.organization_settings set structure_version=structure_version+1,updated_at=now(),updated_by=auth.uid() where singleton;
  return case when tg_op='DELETE' then old else new end;
end $$;
drop trigger if exists organization_units_version on public.organization_units;
create trigger organization_units_version after insert or update or delete on public.organization_units for each row execute function private.bump_organization_version();
drop trigger if exists organization_positions_version on public.organization_positions;
create trigger organization_positions_version after insert or update or delete on public.organization_positions for each row execute function private.bump_organization_version();
drop trigger if exists organization_assignments_version on public.organization_position_assignments;
create trigger organization_assignments_version after insert or update or delete on public.organization_position_assignments for each row execute function private.bump_organization_version();

create table if not exists public.approval_policies(
  id bigint generated by default as identity primary key,
  policy_key text not null unique,
  title text not null,
  active boolean not null default true,
  max_levels integer not null default 3 check(max_levels>0),
  required_role_keys text[] not null default '{}',
  amount_threshold numeric,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.approval_policy_steps(
  id bigint generated by default as identity primary key,
  policy_id bigint not null references public.approval_policies(id) on delete cascade,
  step_no integer not null check(step_no>0),
  role_key text references public.organization_roles(role_key),
  required boolean not null default true,
  unique(policy_id,step_no)
);
insert into public.approval_policies(policy_key,title,max_levels) values
 ('create','تعریف وظیفه',3),('update','ویرایش وظیفه',3),('complete','اعلام انجام وظیفه',3),
 ('project','درخواست پروژه',3),('invoice','درخواست مالی',5)
on conflict(policy_key) do nothing;
insert into public.approval_policy_steps(policy_id,step_no,role_key)
select p.id,x.step_no,x.role_key
from public.approval_policies p
join (values
  ('create',1,'supervisor'),('create',2,'head'),('create',3,'manager'),
  ('update',1,'supervisor'),('update',2,'head'),('update',3,'manager'),
  ('complete',1,'supervisor'),('complete',2,'head'),
  ('project',1,'supervisor'),('project',2,'head'),('project',3,'manager'),
  ('invoice',1,'supervisor'),('invoice',2,'head'),('invoice',3,'manager'),('invoice',4,'deputy')
) as x(policy_key,step_no,role_key) on x.policy_key=p.policy_key
on conflict(policy_id,step_no) do update set role_key=excluded.role_key;

create table if not exists public.organization_workflows(
  id bigint generated by default as identity primary key,
  request_id bigint not null unique references public.change_requests(id) on delete cascade,
  policy_id bigint references public.approval_policies(id) on delete set null,
  requester_position_id bigint references public.organization_positions(id) on delete set null,
  structure_version bigint not null default 1,
  status text not null default 'in_review' check(status in ('in_review','needs_revision','approved','rejected','cancelled','blocked')),
  current_step integer not null default 1,
  structure_snapshot jsonb not null default '{}'::jsonb,
  blocked_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.organization_workflow_steps(
  id bigint generated by default as identity primary key,
  workflow_id bigint not null references public.organization_workflows(id) on delete cascade,
  step_no integer not null,
  position_id bigint references public.organization_positions(id) on delete set null,
  approver_id uuid references public.profiles(id) on delete set null,
  role_key text,
  position_title text,
  decision text not null default 'pending' check(decision in ('pending','approved','rejected','needs_revision')),
  note text,
  decided_at timestamptz,
  unique(workflow_id,step_no)
);
alter table public.change_requests add column if not exists organization_workflow_id bigint references public.organization_workflows(id) on delete set null;
alter table public.change_requests add column if not exists requester_position_id bigint references public.organization_positions(id) on delete set null;

create or replace function private.route_change_request(p_request_id bigint)
returns void language plpgsql security definer set search_path='' as $$
declare
  r public.change_requests%rowtype; policy public.approval_policies%rowtype; wf bigint;
  requester_position bigint; version_no bigint; depth_no integer; parent_id bigint;
  pos record; approver uuid; allowed boolean; snapshot jsonb:='[]'::jsonb; route_step_no integer:=0;
begin
  select * into r from public.change_requests where id=p_request_id for update;
  if not found then raise exception 'درخواست پیدا نشد'; end if;
  select * into policy from public.approval_policies where policy_key in (r.request_type,'task') and active
    order by (policy_key=r.request_type) desc,id limit 1;
  select a.position_id into requester_position from public.organization_position_assignments a
    where a.user_id=r.requested_by and a.is_primary and a.valid_from<=current_date and (a.valid_to is null or a.valid_to>=current_date)
    order by a.id desc limit 1;
  select structure_version into version_no from public.organization_settings where singleton;
  insert into public.organization_workflows(request_id,policy_id,requester_position_id,structure_version,status,current_step,structure_snapshot)
    values(r.id,policy.id,requester_position,coalesce(version_no,1),'in_review',1,'{}'::jsonb) returning id into wf;
  if requester_position is not null then
    for pos in
      with recursive ancestors as(
        select p.id,p.parent_position_id,p.title,ro.role_key,0 as depth_no
        from public.organization_positions p join public.organization_roles ro on ro.id=p.role_id
        where p.id=requester_position
        union all
        select parent.id,parent.parent_position_id,parent.title,ro.role_key,child.depth_no+1
        from public.organization_positions parent
        join ancestors child on child.parent_position_id=parent.id
        join public.organization_roles ro on ro.id=parent.role_id
      )
      select * from ancestors where depth_no>0 order by depth_no
    loop
      exit when route_step_no >= coalesce(policy.max_levels,3);
      select coalesce(a.acting_user_id,pa.user_id) into approver
      from public.organization_positions p
      left join public.organization_position_assignments pa on pa.position_id=p.id and pa.is_primary and pa.valid_to is null
      left join lateral(select acting_user_id from public.organization_position_acting ac where ac.position_id=p.id and ac.valid_from<=current_date and ac.valid_to>=current_date order by ac.id desc limit 1) a on true
      where p.id=pos.id and p.active and (a.acting_user_id is not null or pa.user_id is not null) limit 1;
      allowed := approver is not null and exists(select 1 from public.profiles pr where pr.id=approver and pr.active and pr.id<>r.requested_by)
        and (coalesce(array_length(policy.required_role_keys,1),0)=0 or pos.role_key=any(policy.required_role_keys))
        and (not exists(select 1 from public.approval_policy_steps ps where ps.policy_id=policy.id)
          or exists(select 1 from public.approval_policy_steps ps where ps.policy_id=policy.id and ps.step_no=route_step_no+1 and (ps.role_key is null or ps.role_key=pos.role_key)));
      if allowed then
        route_step_no:=route_step_no+1;
        insert into public.organization_workflow_steps(workflow_id,step_no,position_id,approver_id,role_key,position_title)
          values(wf,route_step_no,pos.id,approver,pos.role_key,pos.title);
        snapshot:=snapshot||jsonb_build_array(jsonb_build_object('step_no',route_step_no,'position_id',pos.id,'position_title',pos.title,'role_key',pos.role_key,'approver_id',approver));
      end if;
    end loop;
  end if;
  if route_step_no=0 then
    update public.organization_workflows set status='blocked',blocked_reason=case when requester_position is null then 'برای ثبت‌کننده سمت سازمانی فعال تعیین نشده است.' else 'بالادست فعال و قابل تأیید پیدا نشد.' end,structure_snapshot=snapshot,updated_at=now() where id=wf;
    update public.change_requests set organization_workflow_id=wf,requester_position_id=requester_position,request_status='pending',current_stage=1 where id=r.id;
  else
    update public.organization_workflows set structure_snapshot=snapshot,updated_at=now() where id=wf;
    update public.change_requests set organization_workflow_id=wf,requester_position_id=requester_position,request_status='in_review',current_stage=1,approval_chain_id=null where id=r.id;
    select approver_id into approver from public.organization_workflow_steps where workflow_id=wf and step_no=1;
    if approver is not null then
      begin perform private.create_portal_event(approver,'درخواست جدید برای تأیید','یک درخواست در کارتابل شما قرار گرفت.','approval_request','change_request',r.id::text); exception when others then null; end;
    end if;
  end if;
  insert into public.change_request_events(request_id,actor_id,event_type,note,snapshot)
    values(r.id,auth.uid(),'routed',case when route_step_no=0 then 'گردش سازمانی متوقف شد؛ ساختار سازمانی نیازمند تکمیل است.' else 'درخواست بر اساس ساختار سازمانی وارد گردش شد.' end,jsonb_build_object('workflow_id',wf,'structure_version',version_no,'steps',snapshot));
end $$;

create or replace function public.submit_change_request(p_request_type text,p_task_id bigint,p_proposed_data jsonb,p_note text default null)
returns bigint language plpgsql security definer set search_path='' as $$
declare rid bigint; owned boolean; before_snapshot jsonb;
begin
  if p_request_type not in ('create','update','status','priority','description','complete','delete','due_date') then raise exception 'نوع درخواست نامعتبر است'; end if;
  if p_request_type='create' then
    p_proposed_data=coalesce(p_proposed_data,'{}'::jsonb)||jsonb_build_object('owner_id',null,'status','ثبت شده','start_date',null,'due_date',null,'done_date',null);
  else
    select exists(select 1 from public.tasks where id=p_task_id and owner_id=auth.uid()) into owned;
    if not owned and not private.is_manager() and not public.organization_has_permission('project.edit',null) then raise exception 'این وظیفه در محدوده دسترسی شما نیست'; end if;
    select to_jsonb(t) into before_snapshot from public.tasks t where t.id=p_task_id;
  end if;
  insert into public.change_requests(task_id,request_type,before_data,proposed_data,requested_by,request_status,requester_note)
    values(p_task_id,p_request_type,before_snapshot,coalesce(p_proposed_data,'{}'::jsonb),auth.uid(),'pending',p_note) returning id into rid;
  perform private.route_change_request(rid);
  return rid;
end $$;

create or replace function public.review_request_stage(p_request_id bigint,p_decision text,p_note text default null,p_final_data jsonb default null)
returns text language plpgsql security definer set search_path='' as $$
declare r public.change_requests%rowtype; wf public.organization_workflows%rowtype; step public.organization_workflow_steps%rowtype; next_step integer; payload jsonb;
begin
  if p_decision not in ('approved','rejected','needs_revision') then raise exception 'تصمیم نامعتبر است'; end if;
  select * into r from public.change_requests where id=p_request_id and request_status in ('pending','in_review','needs_revision') for update;
  if not found then raise exception 'درخواست باز پیدا نشد'; end if;
  if r.organization_workflow_id is null then raise exception 'این درخواست در گردش سازمانی نیست؛ رکورد تاریخی فقط قابل مشاهده است.'; end if;
  select * into wf from public.organization_workflows where id=r.organization_workflow_id for update;
  select * into step from public.organization_workflow_steps where workflow_id=wf.id and step_no=wf.current_step and approver_id=auth.uid() and decision='pending' for update;
  if not found then raise exception 'این درخواست در کارتابل شما نیست'; end if;
  update public.organization_workflow_steps set decision=p_decision,note=p_note,decided_at=now() where id=step.id;
  insert into public.change_request_events(request_id,actor_id,event_type,note,snapshot) values(r.id,auth.uid(),p_decision,p_note,jsonb_build_object('workflow_id',wf.id,'step_no',wf.current_step));
  if p_decision='rejected' then update public.organization_workflows set status='rejected',updated_at=now() where id=wf.id; update public.change_requests set request_status='rejected',manager_note=p_note,reviewed_by=auth.uid(),reviewed_at=now(),completed_at=now() where id=r.id; return 'rejected'; end if;
  if p_decision='needs_revision' then update public.organization_workflows set status='needs_revision',updated_at=now() where id=wf.id; update public.change_requests set request_status='needs_revision',manager_note=p_note,reviewed_by=auth.uid(),reviewed_at=now() where id=r.id; begin perform private.create_portal_event(r.requested_by,'درخواست برای اصلاح برگشت داده شد',coalesce(p_note,'لطفاً درخواست را اصلاح کنید.'),'request_revision','change_request',r.id::text); exception when others then null; end; return 'needs_revision'; end if;
  select min(step_no) into next_step from public.organization_workflow_steps where workflow_id=wf.id and step_no>wf.current_step;
  if next_step is not null then update public.organization_workflows set current_step=next_step,updated_at=now() where id=wf.id; update public.change_requests set current_stage=next_step where id=r.id; select approver_id into step.approver_id from public.organization_workflow_steps where workflow_id=wf.id and step_no=next_step; begin perform private.create_portal_event(step.approver_id,'درخواست جدید برای تأیید','درخواست به مرحله بعدی گردش رسید.','approval_request','change_request',r.id::text); exception when others then null; end; return 'next_stage'; end if;
  payload:=coalesce(p_final_data,r.proposed_data); perform private.apply_change_request(r.id,auth.uid(),payload);
  update public.organization_workflows set status='approved',updated_at=now() where id=wf.id;
  return 'approved';
end $$;

create or replace function public.resubmit_change_request(p_request_id bigint,p_proposed_data jsonb)
returns void language plpgsql security definer set search_path='' as $$
begin
  update public.change_requests set proposed_data=coalesce(p_proposed_data,'{}'::jsonb),request_status='pending',revision_count=revision_count+1,resubmitted_at=now(),reviewed_by=null,reviewed_at=null,manager_note=null,current_stage=1,completed_at=null,final_data=null,applied_task_id=null,organization_workflow_id=null where id=p_request_id and requested_by=auth.uid() and request_status='needs_revision';
  if not found then raise exception 'درخواست قابل اصلاح پیدا نشد'; end if;
  insert into public.change_request_events(request_id,actor_id,event_type,note,snapshot) values(p_request_id,auth.uid(),'resubmitted','درخواست پس از اصلاح دوباره ارسال شد',p_proposed_data);
  perform private.route_change_request(p_request_id);
end $$;

create or replace function public.request_routing_status()
returns table(request_id bigint,stage_no smallint,stage_title text,approver_names text,actionable boolean)
language sql stable security definer set search_path='' as $$
  select r.id,w.current_step::smallint,coalesce(string_agg(distinct s.position_title,'، ' order by s.position_title),'بدون بالادست'),
    string_agg(distinct p.full_name,'، ' order by p.full_name),
    coalesce(bool_or(s.approver_id=auth.uid() and s.decision='pending'),false)
  from public.change_requests r join public.organization_workflows w on w.id=r.organization_workflow_id
  join public.organization_workflow_steps s on s.workflow_id=w.id and s.step_no=w.current_step
  left join public.profiles p on p.id=s.approver_id
  where r.request_status in ('pending','in_review','needs_revision')
    and (r.requested_by=auth.uid() or s.approver_id=auth.uid() or public.organization_has_permission('request.approve',r.requested_by))
  group by r.id,w.current_step;
$$;

create or replace function public.request_workflow_snapshot()
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare current_rows jsonb; history_rows jsonb; routes jsonb; me uuid:=auth.uid();
begin
  select coalesce(jsonb_agg(to_jsonb(r) order by r.created_at desc,r.id desc),'[]'::jsonb) into current_rows
  from public.change_requests r left join public.organization_workflows w on w.id=r.organization_workflow_id
  where r.request_status in ('pending','in_review','needs_revision') and (r.requested_by=me or exists(select 1 from public.organization_workflow_steps s where s.workflow_id=w.id and s.approver_id=me and s.step_no=w.current_step and s.decision='pending') or public.organization_has_permission('request.approve',r.requested_by));
  select coalesce(jsonb_agg(to_jsonb(r) order by coalesce(r.reviewed_at,r.completed_at,r.created_at) desc,r.id desc),'[]'::jsonb) into history_rows
  from public.change_requests r where r.request_status in ('approved','rejected','cancelled') and (r.requested_by=me or public.organization_has_permission('request.approve',r.requested_by));
  select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) into routes from public.request_routing_status() x;
  return jsonb_build_object('current_requests',current_rows,'history_requests',history_rows,'routes',routes);
end $$;

grant execute on function public.organization_scope_user_ids(uuid) to authenticated;
grant execute on function public.organization_has_permission(text,uuid) to authenticated;
grant execute on function public.submit_change_request(text,bigint,jsonb,text) to authenticated;
grant execute on function public.review_request_stage(bigint,text,text,jsonb) to authenticated;
grant execute on function public.resubmit_change_request(bigint,jsonb) to authenticated;
grant execute on function public.request_routing_status() to authenticated;
grant execute on function public.request_workflow_snapshot() to authenticated;
revoke all on function private.route_change_request(bigint) from public,anon,authenticated;

-- Migrate open requests once. Terminal requests keep their old chain and step
-- history untouched; an open request gets a new hierarchy snapshot or a
-- visible blocked state that an administrator can resolve by completing the tree.
do $$
declare r record;
begin
  for r in select id from public.change_requests
    where request_status in ('pending','in_review','needs_revision')
      and organization_workflow_id is null order by id
  loop
    begin
      perform private.route_change_request(r.id);
    exception when others then
      insert into public.audit_trail(actor_id,action,target_type,target_id,metadata)
        values(auth.uid(),'migration_blocked','change_request',r.id::text,jsonb_build_object('reason',sqlerrm));
    end;
  end loop;
end $$;

create table if not exists public.projects(
  id bigint generated by default as identity primary key,
  project_code text not null unique,
  title text not null,
  description text,
  owner_id uuid not null references public.profiles(id),
  manager_id uuid references public.profiles(id),
  unit_id bigint references public.organization_units(id) on delete set null,
  parent_project_id bigint references public.projects(id) on delete set null,
  planned_start date,planned_end date,actual_start date,actual_end date,
  status text not null default 'draft', priority text not null default 'medium',
  progress numeric(5,2) not null default 0 check(progress between 0 and 100),
  progress_override numeric(5,2) check(progress_override between 0 and 100),
  tags text[] not null default '{}', metadata jsonb not null default '{}'::jsonb,
  created_by uuid not null references public.profiles(id), updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  check(planned_end is null or planned_start is null or planned_end>=planned_start)
);
create table if not exists public.project_members(project_id bigint references public.projects(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,member_role text,created_at timestamptz not null default now(),primary key(project_id,user_id));
create table if not exists public.project_items(
  id bigint generated by default as identity primary key,project_id bigint not null references public.projects(id) on delete cascade,parent_item_id bigint references public.project_items(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete set null,item_type text not null check(item_type in ('phase','activity','task','subtask','milestone')),
  title text not null,description text,owner_id uuid references public.profiles(id) on delete set null,status text not null default 'planned',priority text not null default 'medium',
  planned_start date,planned_end date,actual_start date,actual_end date,progress numeric(5,2) not null default 0 check(progress between 0 and 100),weight numeric(10,2) not null default 1 check(weight>=0),created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(planned_end is null or planned_start is null or planned_end>=planned_start)
);
create table if not exists public.project_dependencies(
  id bigint generated by default as identity primary key,predecessor_item_id bigint not null references public.project_items(id) on delete cascade,successor_item_id bigint not null references public.project_items(id) on delete cascade,dependency_type text not null default 'FS' check(dependency_type in ('FS','SS','FF','SF')),lag_days integer not null default 0,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),unique(predecessor_item_id,successor_item_id),check(predecessor_item_id<>successor_item_id)
);
create or replace function private.prevent_project_dependency_cycle() returns trigger language plpgsql set search_path='' as $$ begin if exists(with recursive walk(node) as(select new.successor_item_id union all select d.successor_item_id from public.project_dependencies d join walk w on w.node=d.predecessor_item_id) select 1 from walk where node=new.predecessor_item_id) then raise exception 'وابستگی حلقوی مجاز نیست'; end if; return new; end $$;
drop trigger if exists project_dependency_cycle_guard on public.project_dependencies;
create trigger project_dependency_cycle_guard before insert or update on public.project_dependencies for each row execute function private.prevent_project_dependency_cycle();
create or replace function public.project_calculated_progress(p_project_id bigint) returns numeric language sql stable set search_path='' as $$ select coalesce(round(sum(i.progress*i.weight)/nullif(sum(i.weight),0),2),0) from public.project_items i where i.project_id=p_project_id and i.item_type in ('activity','task','subtask','milestone'); $$;
create or replace function private.sync_project_progress() returns trigger language plpgsql security definer set search_path='' as $$
declare project_id_value bigint;
begin
  project_id_value:=coalesce(new.project_id,old.project_id);
  update public.projects set progress=public.project_calculated_progress(project_id_value),updated_at=now() where id=project_id_value and progress_override is null;
  return case when tg_op='DELETE' then old else new end;
end $$;
drop trigger if exists project_items_progress on public.project_items;
create trigger project_items_progress after insert or update or delete on public.project_items for each row execute function private.sync_project_progress();
create or replace function private.enforce_project_progress_override() returns trigger language plpgsql set search_path='' as $$
begin
  if new.progress_override is distinct from old.progress_override and not public.organization_has_permission('project.progress_override',new.owner_id) then
    raise exception 'ثبت Override پیشرفت مجوز لازم دارد';
  end if;
  return new;
end $$;
drop trigger if exists project_progress_override_guard on public.projects;
create trigger project_progress_override_guard before update on public.projects for each row execute function private.enforce_project_progress_override();

create table if not exists public.parts(
  id bigint generated by default as identity primary key,part_number text not null unique,code text,fa_name text not null,en_name text,group_name text,subgroup_name text,part_type text,manufacturer text,supplier text,brand text,country text,status text not null default 'active',description text,image_path text,drawing_number text,revision text,last_revision_date date,specifications jsonb not null default '{}'::jsonb,created_by uuid not null references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.part_bom(parent_part_id bigint references public.parts(id) on delete cascade,child_part_id bigint references public.parts(id) on delete cascade,quantity numeric(12,3) not null default 1,position_no text,primary key(parent_part_id,child_part_id),check(parent_part_id<>child_part_id));
create table if not exists public.part_vehicle_links(part_id bigint references public.parts(id) on delete cascade,vehicle_ref text not null,trim_name text not null default '',subsystem text,created_at timestamptz not null default now(),primary key(part_id,vehicle_ref,trim_name));
create table if not exists public.part_project_links(part_id bigint references public.parts(id) on delete cascade,project_id bigint references public.projects(id) on delete cascade,created_at timestamptz not null default now(),primary key(part_id,project_id));
create table if not exists public.part_test_links(id bigint generated by default as identity primary key,part_id bigint references public.parts(id) on delete cascade,test_ref text not null,test_title text,result text,test_date date,owner_id uuid references public.profiles(id),report_path text,approval_status text not null default 'pending',metadata jsonb not null default '{}'::jsonb);
create table if not exists public.part_history(id bigint generated by default as identity primary key,part_id bigint references public.parts(id) on delete cascade,actor_id uuid references public.profiles(id),action text not null,old_data jsonb,new_data jsonb,created_at timestamptz not null default now());
create or replace function private.part_history_trigger() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.part_history(part_id,actor_id,action,old_data,new_data) values(coalesce(new.id,old.id),auth.uid(),lower(tg_op),case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end); return case when tg_op='DELETE' then old else new end; end $$;
drop trigger if exists parts_history on public.parts; create trigger parts_history after insert or update or delete on public.parts for each row execute function private.part_history_trigger();

create table if not exists public.invoices(
  id bigint generated by default as identity primary key,invoice_number text not null unique,title text not null,expense_type text,account_party text not null,company_name text,project_id bigint references public.projects(id) on delete set null,vehicle_ref text,part_id bigint references public.parts(id) on delete set null,test_ref text,total_amount numeric(18,2) not null default 0 check(total_amount>=0),currency text not null default 'IRR',created_at_date date not null default current_date,due_date date,status text not null default 'initial',created_by uuid not null references public.profiles(id),follow_up_owner_id uuid references public.profiles(id),description text,contract_ref text,metadata jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now()
);
create table if not exists public.invoice_payments(
  id bigint generated by default as identity primary key,invoice_id bigint not null references public.invoices(id) on delete cascade,sequence_no integer not null,amount numeric(18,2) not null check(amount>0),percent_of_total numeric(7,3),planned_date date,paid_date date,status text not null default 'planned',document_no text,tracking_no text,payment_method text,payer_id uuid references public.profiles(id),approver_id uuid references public.profiles(id),notes text,receipt_path text,created_at timestamptz not null default now(),unique(invoice_id,sequence_no)
);
create table if not exists public.invoice_files(id bigint generated by default as identity primary key,invoice_id bigint not null references public.invoices(id) on delete cascade,file_type text not null,file_name text not null,storage_path text not null,uploaded_by uuid references public.profiles(id),created_at timestamptz not null default now());
create or replace function public.invoice_paid_amount(p_invoice_id bigint) returns numeric language sql stable set search_path='' as $$ select coalesce(sum(amount) filter(where status='paid'),0) from public.invoice_payments where invoice_id=p_invoice_id; $$;
create or replace function public.invoice_remaining_amount(p_invoice_id bigint) returns numeric language sql stable set search_path='' as $$ select greatest(coalesce((select total_amount from public.invoices where id=p_invoice_id),0)-public.invoice_paid_amount(p_invoice_id),0); $$;
create or replace function private.sync_invoice_status() returns trigger language plpgsql security definer set search_path='' as $$
declare invoice_id_value bigint; total numeric; paid_value numeric; due date;
begin
  invoice_id_value:=coalesce(new.invoice_id,old.invoice_id); select i.total_amount,i.due_date into total,due from public.invoices i where i.id=invoice_id_value; paid_value:=public.invoice_paid_amount(invoice_id_value);
  update public.invoices set status=case when paid_value>=coalesce(total,0) and total>0 then 'settled' when paid_value>0 then 'partially_paid' when due is not null and due<current_date then 'overdue' else 'awaiting_payment' end,updated_at=now() where id=invoice_id_value and status not in ('cancelled','returned');
  return case when tg_op='DELETE' then old else new end;
end $$;
drop trigger if exists invoice_payments_status on public.invoice_payments;
create trigger invoice_payments_status after insert or update or delete on public.invoice_payments for each row execute function private.sync_invoice_status();

create or replace function public.platform_can_access_project(p_project_id bigint)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.projects p where p.id=p_project_id and (p.created_by=auth.uid() or p.owner_id=auth.uid() or exists(select 1 from public.project_members m where m.project_id=p.id and m.user_id=auth.uid()) or public.organization_has_permission('project.view_subordinates',p.owner_id)));
$$;
create or replace function public.platform_can_access_part(p_part_id bigint)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.parts p where p.id=p_part_id and (p.created_by=auth.uid() or public.organization_has_permission('part.view',null)));
$$;
create or replace function public.platform_can_access_invoice(p_invoice_id bigint)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.invoices i where i.id=p_invoice_id and (i.created_by=auth.uid() or i.follow_up_owner_id=auth.uid() or public.organization_has_permission('invoice.view',null)));
$$;

do $$
declare t text; begin
  foreach t in array array['organization_roles','organization_units','organization_positions','organization_position_assignments','organization_position_acting','approval_policies','approval_policy_steps','organization_workflows','organization_workflow_steps','projects','project_members','project_items','project_dependencies','parts','part_bom','part_vehicle_links','part_project_links','part_test_links','invoices','invoice_payments','invoice_files'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('drop policy if exists %I_authenticated_read on public.%I',t,t);
    execute format('create policy %I_authenticated_read on public.%I for select to authenticated using(true)',t,t);
  end loop;
end $$;

drop policy if exists organization_manage_write on public.organization_positions;
create policy organization_manage_write on public.organization_positions for all to authenticated using(private.platform_can_manage_org()) with check(private.platform_can_manage_org());
drop policy if exists organization_assignments_manage_write on public.organization_position_assignments;
create policy organization_assignments_manage_write on public.organization_position_assignments for all to authenticated using(private.platform_can_manage_org()) with check(private.platform_can_manage_org());
drop policy if exists organization_units_manage_write on public.organization_units;
create policy organization_units_manage_write on public.organization_units for all to authenticated using(private.platform_can_manage_org()) with check(private.platform_can_manage_org());
drop policy if exists organization_roles_manage_write on public.organization_roles;
create policy organization_roles_manage_write on public.organization_roles for all to authenticated using(private.platform_can_manage_org()) with check(private.platform_can_manage_org());
drop policy if exists organization_permissions_manage_write on public.organization_role_permissions;
create policy organization_permissions_manage_write on public.organization_role_permissions for all to authenticated using(private.platform_can_manage_org()) with check(private.platform_can_manage_org());
drop policy if exists approval_policies_manage_write on public.approval_policies;
create policy approval_policies_manage_write on public.approval_policies for all to authenticated using(private.platform_can_manage_org()) with check(private.platform_can_manage_org());
drop policy if exists approval_policy_steps_manage_write on public.approval_policy_steps;
create policy approval_policy_steps_manage_write on public.approval_policy_steps for all to authenticated using(private.platform_can_manage_org()) with check(private.platform_can_manage_org());
drop policy if exists organization_workflows_authenticated_read on public.organization_workflows;
create policy organization_workflows_scoped_read on public.organization_workflows for select to authenticated using(
  exists(select 1 from public.change_requests r where r.id=request_id and r.requested_by=auth.uid())
  or exists(select 1 from public.organization_workflow_steps s where s.workflow_id=id and s.approver_id=auth.uid())
  or public.organization_has_permission('request.approve',null)
);
drop policy if exists organization_workflow_steps_authenticated_read on public.organization_workflow_steps;
create policy organization_workflow_steps_scoped_read on public.organization_workflow_steps for select to authenticated using(
  approver_id=auth.uid() or exists(select 1 from public.organization_workflows w join public.change_requests r on r.id=w.request_id where w.id=workflow_id and r.requested_by=auth.uid()) or public.organization_has_permission('request.approve',null)
);
drop policy if exists approval_policies_authenticated_read on public.approval_policies;
create policy approval_policies_manager_read on public.approval_policies for select to authenticated using(private.platform_can_manage_org());
drop policy if exists approval_policy_steps_authenticated_read on public.approval_policy_steps;
create policy approval_policy_steps_manager_read on public.approval_policy_steps for select to authenticated using(private.platform_can_manage_org());
drop policy if exists project_scoped_write on public.projects;
create policy project_scoped_write on public.projects for all to authenticated using(created_by=auth.uid() or owner_id=auth.uid() or public.organization_has_permission('project.edit',owner_id)) with check(created_by=auth.uid() or owner_id=auth.uid() or public.organization_has_permission('project.create',owner_id));
drop policy if exists part_scoped_write on public.parts;
create policy part_scoped_write on public.parts for all to authenticated using(created_by=auth.uid() or public.organization_has_permission('part.edit',null)) with check(created_by=auth.uid() or public.organization_has_permission('part.create',null));
drop policy if exists invoice_scoped_write on public.invoices;
create policy invoice_scoped_write on public.invoices for all to authenticated using(created_by=auth.uid() or follow_up_owner_id=auth.uid() or public.organization_has_permission('invoice.approve',null)) with check(created_by=auth.uid() or public.organization_has_permission('invoice.create',null));

drop policy if exists projects_authenticated_read on public.projects;
create policy projects_scoped_read on public.projects for select to authenticated using(public.platform_can_access_project(id));
drop policy if exists parts_authenticated_read on public.parts;
create policy parts_scoped_read on public.parts for select to authenticated using(public.platform_can_access_part(id));
drop policy if exists invoices_authenticated_read on public.invoices;
create policy invoices_scoped_read on public.invoices for select to authenticated using(public.platform_can_access_invoice(id));

drop policy if exists project_members_authenticated_read on public.project_members;
create policy project_members_scoped on public.project_members for all to authenticated using(public.platform_can_access_project(project_id)) with check(public.platform_can_access_project(project_id));
drop policy if exists project_items_authenticated_read on public.project_items;
create policy project_items_scoped on public.project_items for all to authenticated using(public.platform_can_access_project(project_id)) with check(public.platform_can_access_project(project_id));
drop policy if exists project_dependencies_authenticated_read on public.project_dependencies;
create policy project_dependencies_scoped on public.project_dependencies for all to authenticated using(exists(select 1 from public.project_items i where i.id=predecessor_item_id and public.platform_can_access_project(i.project_id))) with check(exists(select 1 from public.project_items i where i.id=predecessor_item_id and public.platform_can_access_project(i.project_id)));
drop policy if exists part_bom_authenticated_read on public.part_bom;
create policy part_bom_scoped on public.part_bom for all to authenticated using(public.platform_can_access_part(parent_part_id) or public.platform_can_access_part(child_part_id)) with check(public.platform_can_access_part(parent_part_id));
drop policy if exists part_vehicle_links_authenticated_read on public.part_vehicle_links;
create policy part_vehicle_links_scoped on public.part_vehicle_links for all to authenticated using(public.platform_can_access_part(part_id)) with check(public.platform_can_access_part(part_id));
drop policy if exists part_project_links_authenticated_read on public.part_project_links;
create policy part_project_links_scoped on public.part_project_links for all to authenticated using(public.platform_can_access_part(part_id) or public.platform_can_access_project(project_id)) with check(public.platform_can_access_part(part_id) or public.platform_can_access_project(project_id));
drop policy if exists part_test_links_authenticated_read on public.part_test_links;
create policy part_test_links_scoped on public.part_test_links for all to authenticated using(public.platform_can_access_part(part_id)) with check(public.platform_can_access_part(part_id));
drop policy if exists part_history_authenticated_read on public.part_history;
create policy part_history_scoped on public.part_history for select to authenticated using(public.platform_can_access_part(part_id));
drop policy if exists invoice_payments_authenticated_read on public.invoice_payments;
create policy invoice_payments_scoped on public.invoice_payments for all to authenticated using(public.platform_can_access_invoice(invoice_id)) with check(public.platform_can_access_invoice(invoice_id));
drop policy if exists invoice_files_authenticated_read on public.invoice_files;
create policy invoice_files_scoped on public.invoice_files for all to authenticated using(public.platform_can_access_invoice(invoice_id)) with check(public.platform_can_access_invoice(invoice_id));

alter table public.audit_trail enable row level security;
drop policy if exists audit_trail_read on public.audit_trail;
create policy audit_trail_read on public.audit_trail for select to authenticated using(actor_id=auth.uid() or private.platform_can_manage_org());
revoke insert,update,delete on public.audit_trail from anon,authenticated;

do $$ declare t text; begin foreach t in array array['projects','project_items','project_dependencies','parts','part_bom','part_vehicle_links','part_project_links','part_test_links','invoices','invoice_payments','invoice_files','organization_workflows','organization_workflow_steps','approval_policies','approval_policy_steps'] loop execute format('drop trigger if exists %I_audit on public.%I',t,t); execute format('create trigger %I_audit after insert or update or delete on public.%I for each row execute function private.platform_audit_trigger()',t,t); end loop; end $$;

notify pgrst,'reload schema';
