-- Explicit feature matrix, operational part handovers, and task due alerts.

-- ---------------------------------------------------------------------------
-- 1. The approved access matrix. A direct deny makes every other feature
-- source ineffective, so every active non-manager has one explicit row for
-- every active feature before the approved allow rows are applied.
-- ---------------------------------------------------------------------------
delete from public.feature_access_grants grant_row
using public.profiles profile
where grant_row.subject_kind='user'
  and grant_row.user_id=profile.id
  and grant_row.revoked_at is null
  and profile.active
  and coalesce(profile.role,'')<>'manager';

insert into public.feature_access_grants(
  feature_key,subject_kind,user_id,effect,
  can_view,can_create,can_edit,can_delete,can_export,can_manage_access,can_bypass_approval,
  metadata
)
select feature.feature_key,'user',profile.id,'deny',false,false,false,false,false,false,false,
  jsonb_build_object('source','20260922_explicit_access_matrix')
from public.app_features feature
cross join public.profiles profile
where feature.active and profile.active and coalesce(profile.role,'')<>'manager';

with desired(user_email,feature_key) as (
  select people.email,feature.feature_key
  from (values ('tanhaiyan@bamco.ir'),('a.zare@bamcofactory.ir')) as people(email)
  cross join public.app_features feature
  where feature.active
  union all
  select 'rasti@bamco.ir','letters'
  union all
  select people.email,feature.feature_key
  from (values ('rasti@bamco.ir'),('k.shahabadi@bamco.ir')) as people(email)
  cross join (values ('vehiclePermanent'),('vehicleTemporary'),('parts'),('tools')) as feature(feature_key)
)
update public.feature_access_grants grant_row
set effect='allow',
    can_view=true,
    can_create=true,
    can_edit=true,
    can_delete=true,
    can_export=true,
    can_manage_access=false,
    can_bypass_approval=false,
    metadata=jsonb_build_object('source','20260922_explicit_access_matrix')
from desired
join public.profiles profile on lower(profile.email::text)=desired.user_email and profile.active
where grant_row.subject_kind='user'
  and grant_row.user_id=profile.id
  and grant_row.feature_key=desired.feature_key
  and grant_row.resource_type is null
  and grant_row.resource_id is null
  and grant_row.revoked_at is null;

-- ---------------------------------------------------------------------------
-- 2. Part handover register. The columns intentionally match the operational
-- table shown in the parts workspace and the feature permission contract.
-- ---------------------------------------------------------------------------
create table public.part_handovers(
  id bigint generated by default as identity primary key,
  part_name text not null check(length(btrim(part_name))>0),
  technical_number text not null check(length(btrim(technical_number))>0),
  received_from text,
  received_by text,
  returned_from text,
  returned_by text,
  delivery_type text not null check(delivery_type in ('permanent','temporary')),
  return_due_date date,
  reason text,
  registered_at timestamptz not null default now(),
  notes text,
  created_by uuid not null default auth.uid() references public.profiles(id),
  updated_at timestamptz not null default now(),
  check(
    (delivery_type='temporary' and return_due_date is not null)
    or (delivery_type='permanent' and return_due_date is null)
  )
);

create index part_handovers_registered_at_idx
  on public.part_handovers(registered_at desc,id desc);

create or replace function private.touch_part_handovers_updated_at()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  new.updated_at=now();
  return new;
end;
$$;

create trigger part_handovers_touch_updated_at
before update on public.part_handovers
for each row execute function private.touch_part_handovers_updated_at();

alter table public.part_handovers enable row level security;
revoke all on public.part_handovers from public,anon;
grant select,insert,update,delete on public.part_handovers to authenticated;
grant usage,select on sequence public.part_handovers_id_seq to authenticated;

create policy part_handovers_feature_read on public.part_handovers
  for select to authenticated using(public.can_access_feature('parts','view'));
create policy part_handovers_feature_insert on public.part_handovers
  for insert to authenticated with check(
    public.can_access_feature('parts','create') and created_by=auth.uid()
  );
create policy part_handovers_feature_update on public.part_handovers
  for update to authenticated
  using(public.can_access_feature('parts','edit'))
  with check(public.can_access_feature('parts','edit'));
create policy part_handovers_feature_delete on public.part_handovers
  for delete to authenticated using(public.can_access_feature('parts','delete'));

revoke all on function private.touch_part_handovers_updated_at() from public,anon,authenticated;

-- ---------------------------------------------------------------------------
-- 3. A due-state is recorded once per task, recipient and due date. The
-- dispatcher groups newly discovered states into one push-friendly summary,
-- so turning on alerts cannot create a burst of browser notifications.
-- ---------------------------------------------------------------------------
create table private.task_due_alert_log(
  task_id bigint not null references public.tasks(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  due_state text not null check(due_state in ('warning','overdue')),
  due_date date not null,
  created_at timestamptz not null default now(),
  primary key(task_id,recipient_id,due_state,due_date)
);

create index task_due_alert_log_recipient_idx
  on private.task_due_alert_log(recipient_id,created_at desc);
alter table private.task_due_alert_log enable row level security;
revoke all on private.task_due_alert_log from public,anon,authenticated;

create or replace function private.dispatch_task_due_alerts()
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  with due_tasks as (
    select task.id,task.owner_id,task.due_date,
      case
        when task.due_date < current_date then 'overdue'
        when task.due_date <= current_date+greatest(coalesce(task.reminder_days,0),0) then 'warning'
      end as due_state
    from public.tasks task
    join lateral private.task_status_option(task.status) status_option on true
    where task.owner_id is not null
      and task.due_date is not null
      and not task.archived
      and coalesce(status_option.tracks_deadline,false)
      and status_option.kind not in ('completed','cancelled','registered')
      and task.due_date <= current_date+greatest(coalesce(task.reminder_days,0),0)
  ), recipients as (
    select due.id,due.due_date,due.due_state,owner_profile.id as recipient_id
    from due_tasks due
    join public.profiles owner_profile on owner_profile.id=due.owner_id and owner_profile.active
    union
    select due.id,due.due_date,due.due_state,manager_profile.id as recipient_id
    from due_tasks due
    join public.profiles manager_profile on manager_profile.active and manager_profile.role='manager'
  ), inserted as (
    insert into private.task_due_alert_log(task_id,recipient_id,due_state,due_date)
    select id,recipient_id,due_state,due_date from recipients
    on conflict do nothing
    returning task_id,recipient_id,due_state,due_date
  ), summaries as (
    select recipient_id,
      count(*) filter(where due_state='warning')::integer as warning_count,
      count(*) filter(where due_state='overdue')::integer as overdue_count,
      jsonb_agg(jsonb_build_object('task_id',task_id,'state',due_state,'due_date',due_date) order by task_id) as tasks
    from inserted
    group by recipient_id
  )
  insert into public.notifications(user_id,notification_type,title,body,entity_type,entity_id,action,metadata)
  select recipient_id,
    'task_alert',
    'هشدار وظایف',
    case
      when warning_count>0 and overdue_count>0 then warning_count::text||' وظیفه در هشدار و '||overdue_count::text||' وظیفه در دیرکرد است.'
      when overdue_count>0 then overdue_count::text||' وظیفه در دیرکرد است.'
      else warning_count::text||' وظیفه وارد بازه هشدار شده است.'
    end,
    'task_alert_summary',
    current_date::text,
    'open_tasks',
    jsonb_build_object('warning_count',warning_count,'overdue_count',overdue_count,'tasks',tasks)
  from summaries;
end;
$$;

create or replace function private.queue_task_due_alerts()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if tg_op='INSERT'
     or new.owner_id is distinct from old.owner_id
     or new.due_date is distinct from old.due_date
     or new.reminder_days is distinct from old.reminder_days
     or new.status is distinct from old.status
     or new.archived is distinct from old.archived then
    perform private.dispatch_task_due_alerts();
  end if;
  return new;
end;
$$;

drop trigger if exists task_due_alerts_queue on public.tasks;
create trigger task_due_alerts_queue
after insert or update of owner_id,due_date,reminder_days,status,archived on public.tasks
for each row execute function private.queue_task_due_alerts();

do $$
declare scheduled_job bigint;
begin
  for scheduled_job in select jobid from cron.job where jobname='bamco-task-due-alerts'
  loop
    perform cron.unschedule(scheduled_job);
  end loop;
  perform cron.schedule('bamco-task-due-alerts','*/5 * * * *','select private.dispatch_task_due_alerts()');
end;
$$;

revoke all on function private.dispatch_task_due_alerts() from public,anon,authenticated;
revoke all on function private.queue_task_due_alerts() from public,anon,authenticated;
